### ISSUE TITLE
Bug Mi-light: Some parameters of the Mi-light capabilitiesObj are not stored

### ISSUE THREAD

**Issue by satoer** [athombv/apps-sdk-issues#102]
**Bug**
A couple of Mi-light app firmware updates ago the (new registered) Mi-light bulbs are registered in a new way with new capabilitiesObj parameters. Sadly some of these parameters do not get stored. And it’s impossible to retrieve the current status of the lights using homey script.

**Why do I want to get the current status?:**
I want to store the status (on / off / white mode / color mode / brightness etc.) To go to full bright mode when someone is in the area (motion sensor) and go back to the previous state when the person leaves the area.

**Detailed description:**
The following parameters of the capabilitiesObj are not stored: 'enableWhiteMode' 'enableNightMode' 'toggleScene' These values are always “null”. You can however set them. Apparently this feature got "updated" from the old style: "light_mode" (this does store the settings). 

**Full readout of the CapabilitiesObj:**
```
[ 
   'onoff',
   'dim',
   'light_hue',
   'enableWhiteMode',
   'enableNightMode',
   'toggleScene'
],
capabilitiesObj:{ 
   onoff:{ 
      value:false,
      lastUpdated:'2019-07-02T20:57:41.108Z',
      type:'boolean',
      getable:true,
      setable:true,
      title:'Aangezet',
      desc:null,
      units:null,
      id:'onoff',
      options:[ 
         Object
      ],
      values:undefined
   },
   dim:{ 
      value:1,
      lastUpdated:'2019-07-02T19:47:44.918Z',
      type:'number',
      getable:true,
      setable:true,
      title:'Dim niveau',
      desc:null,
      units:'%',
      decimals:2,
      min:0,
      max:1,
      chartType:'stepLine',
      id:'dim',
      options:{ 

      },
      values:undefined
   },
   light_hue:{ 
      value:0.5,
      lastUpdated:'2019-07-02T19:47:28.458Z',
      type:'number',
      getable:true,
      setable:true,
      title:'Hue',
      desc:null,
      units:null,
      decimals:2,
      min:0,
      max:1,
      chartType:'stepLine',
      id:'light_hue',
      options:{ 

      },
      values:undefined
   },
   enableWhiteMode:{ 
      value:null,
      lastUpdated:null,
      type:'boolean',
      setable:true,
      title:'Activeer wit modus',
      desc:null,
      units:null,
      id:'enableWhiteMode',
      options:{ 

      },
      values:undefined
   },
   enableNightMode:{ 
      value:null,
      lastUpdated:null,
      type:'boolean',
      setable:true,
      title:'Activeer nacht modus',
      desc:null,
      units:null,
      id:'enableNightMode',
      options:{ 

      },
      values:undefined
   },
   toggleScene:{ 
      value:null,
      lastUpdated:null,
      type:'boolean',
      setable:true,
      title:'Activeer effect modus',
      desc:null,
      units:null,
      id:'toggleScene',
      options:{ 

      },
      values:undefined
   }
},

```

**Comment by satoer** [comment]
Serious Athom, I’ve tried to contact you with this bug trough Email, the user support forum, I’ve filled in a Google form and now in this issue tracker on Github… Got 0 response. I really don’t know what else I can do to get some response. For month’s I’m trying to make this bug get noticed but I’m really out of options right now. At least tell me something. Is this bug valid, isn’t it important enough, did I made a mistake? I’m sure there’s something wrong with the app. Even the MQTT App’s don’t sent any MQTT data when light mode is changed.

**Comment by WeeJeWel** [comment]
Because the milight bridge is stateless, these values are not available. This is a choice made in the milight app to deliver the best experience.

For your use case, you’re best off storing them yourself in a Logic variable using Flow.

Because this is not an SDK issue I am closing this issue.
