### ISSUE TITLE
Thermostat capability issue [iOS app]

### ISSUE THREAD

**Issue by deetmo** [athombv/apps-sdk-issues#103]
I’m trying to develop driver to support my Heat Pump.
I get some issues when adding multiple “measure_temperature” capabilities connected with “target_temperature”…

When I have X (let’s say 5) “measure_temperature” it working great, but when I want to add one more “target_temperature” my device after clicking on it hangs whole iOS app and I have to kill it.

Im using latest version of iOS app.

Steps to reproduce:
1. Create new app using cli
1. Create new driver inside app with capabilities:

  * "measure_temperature"
  * "target_temperature"
  * "measure_temperature.other"
3. Run app
1. Install new device
1. Click on device tile under "devices tab
1. Watch that whole app hangs - only white screen visible

**Comment by Christian-Athom** [comment]
I have tried to reproduce this problem, but after going through the steps i cannot reproduce your crash.
In the device i see the thermostat page for the measure_temperature and target_temperature, and the measure_temperature.other, measure_temperature.other2, etc are all visible on the sensor page.

**Comment by deetmo** [comment]
Christian,
I will try to reproduce it again on my side with latest sdk/app.
Hopefully tonight.

**Comment by deetmo** [comment]
I have managed to get some minimal setup with issue.
I have created one good device and one with issue.
Only difference is with capabilities:
Good one is using:
`[ "measure_temperature", "target_temperature" ]`
While one with issue:
 `[ "measure_temperature.t1", "target_temperature.t2" ]`

See attached project and shared movie from iOS app:
https://streamable.com/59tz0
[com.deetmo.issue-1.zip](https://github.com/athombv/homey-apps-sdk-issues/files/3860795/com.deetmo.issue-1.zip)

**Comment by Christian-Athom** [comment]
I your case the error is with the fact that there is no 'target_temperature' just the 'target_temperature.xxx'. The dot notation is for multiple capabilities of the same type, but in this case there is only one.

But taking it a step back, what is the scenario you are trying to implement?, e.g. multiple thermostats within 1 device?

Greetings,
Christian

**Comment by deetmo** [comment]
Remark:
I have just found an typo in my previous comment.
Capabilities with issue have same name after dot (attached project is correct) not t1 and t2:  
`[ "measure_temperature.t1", "target_temperature.t1" ]`

Same issue happens, when I have two pairs of measure/target temperature:
`[ "measure_temperature.t1", "target_temperature.t1", "measure_temperature.t2", "target_temperature.t2" ]`

I'm trying to develop Heat Pump driver in witch I have two separate circulation circuits with separate target temperatures.
Currently I'm not able to do this.
Dunno if I can build it with custom properties with thermostat ui component.

**Comment by Christian-Athom** [comment]
Does this device have have 2 separate circuits for target/measure temperature, or are you trying to combine multiple devices into 1 device for Homey?

**Comment by deetmo** [comment]
This is one physical device. 
It's common case, that Heat Pumps have 2-4 separate circuits + 1 for hot water.

**Comment by Christian-Athom** [comment]
Do you have the name of the device?

**Comment by deetmo** [comment]
Don't get it why this is needed.
Please check any heat pump on market how it works.

**Comment by Christian-Athom** [comment]
What you can do is when you are adding the device, create a separate device for every circuit.
The user can then select the circuits he/she wants to add. Then each circuit has it's own device in the overview, and can be controlled individually with regards to temperature etc.

**Comment by deetmo** [comment]
I totally understand this approach, but I consider it as an workaround rather than a final solution.
Heat Pump has also measure_voltage, measure_current, measure_power, etc. that are summed up with all circuits.

Anyway... we are going deep inside driver architecture rather that finding solution to actual issue.
So again...
Do Homey support multiple thermostats inside one device?
How to do that?

**Comment by WeeJeWel** [comment]
No, Homey does not support multiple thermostats in one device.
