### ISSUE TITLE
Alarm_battery capability initially null instead of false

### ISSUE THREAD

**Issue by jghaanstra** [athombv/apps-sdk-issues#104]
I have added the alarm_capability to one of my apps using the addCapability() method. As it's a boolean I'd expect it to be false (or perhaps even true) but instead it was null. Seems like a bug to me, it should initially be a valid boolean. Havent checked if this is the case with other capabilities as well but I can image it's not limited to the alarm_battery capability.

**Comment by WeeJeWel** [comment]
All capability values are initially null so this is actually expected behavior.
