### ISSUE TITLE
Emulating recorded signal doesn't do anything

### ISSUE THREAD

**Issue by kof** [athombv/apps-sdk-issues#105]
Hi,

I am recording and emulating using the tool (https://developer.athom.com/tools/signals). It's a 433,92MHz remote  (Jarolift Funkset Eco).

The recording does work, I get results like this for example, the receiver device also reacts to the signal from the original remote.

```
402,882,434,872,436,868,434,870,442,872,436,864,436,874,434,876,434,4334,880,442,864,442,434,878,874,436,872,434,442,870,874,434,448,866,874,436,876,432,882,436,882,426,440,870,444,866,878,428,446,864,876,446,874,434,878,426,882,436,876,434,442,872,434,866,446,866
434,876,874,438,432,872,444,858,890,432,442,862,880,434,434,870,438,874,440,862,876,436,446,862,440,872,440,862,886,434,436,866,882,434,878,436,434,874,872,444,870,438,874,436,436,870,884,434,876,438,876,436,880,428,880,434,876,446,876,434,874,444,870,440,878,430
880,434,878,444,870,434,882,432,442,872,436,870,434,870,442,872,870,442,878,34116
417,882,10,0,426,874,432,870,442,866,442,860,442,864,442,866,440,868
444,4330,890,436,874,442,432,872,872,442,880,436,434,866,874,444,432,872,876,442,880,434,882,434,874,434,444,866,438,874,878,436,434,872,874,434,884,434,882,436,874,432,882,434,444,872,436,864,444,864,436,874,878,438,432,880,436,866,882,436,436,874,874,432,444,862
448,864,436,874,876,432,440,874,436,872,430,872,882,436,432,874,880,432,872,444,438,862,882,438,874,432,880,442,432,868,888,426,884,436,872,442,880,428,884,436,872,434,882,436,874,432,886,436,874,436,882,428,890,430,882,434,878,430,444,862,438,874,442,862,446,862
882,432,882,42476
```

but emulating the same signal from the tool doesn't make the receiver react at all.

I am not sure where to start debugging it. Is the problem with the recording step or during emulation?

I noticed it recorded separate sequences separated by a new line, is that evtl. a problem?

**Comment by jeroenvollenbrock** [comment]
This is correct behaviour. Signal emulation emulates the supplied signal towards Homey, eg, it pretends it just received the supplied signal and attempts to deliver it to apps. Making homey transmit raw data is not possible without having an app which registered a signal.
