### ISSUE TITLE
Device ID clash causes `list_devices` not to show certain devices paired with a different app.

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#107]
Demo repo here: https://github.com/robertklep/homey-duplicate-id-test

Tested on v3.1.0

The repo contains two different apps that each have a driver that emits a new device entry for pairing, using the same device ID in both apps, namely `this-is-a-duplicate-id`.

When a device entry has been created with demo app #​1 and you try to pair a device with app #​2, the device entry will not be shown in the `list_devices` template because (apparently) Homey thinks the device has already been paired. Only when removing the first device entry, belonging to app #​1, will the device entry show up during pairing with app #​2.

This issue was found by @jghaanstra.

**Comment by jeroenvollenbrock** [comment]
Confirmed and fixed in the next Homey release.
