### ISSUE TITLE
AppApi is not working

### ISSUE THREAD

**Issue by Shakesbeard** [athombv/apps-sdk-issues#109]
Following the example of the SDK here: https://apps.developer.athom.com/ApiApp.html
I am unable to successfully call the remote api endpoint. The host app is not receiving anything.
However, calling that GET endpoint in the web browser works and the result is as expected.
When doing it from the test app however, I keep getting this permission error:
─────────────── Logging stdout & stderr ───────────────
2020-01-08 12:16:08 [log] [MyApp] MyApp is running...
2020-01-08 12:16:08 [log] [MyApp] Connected remote app... ApiApp {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  uri: 'homey:app:com.sdn.plextv-playlist-caster',
  type: 'app',
  id: 'com.sdn.plextv-playlist-caster' }
2020-01-08 12:16:08 [log] [MyApp] otherApp.getInstalled true
2020-01-08 12:16:08 [err] [MyApp] otherApp.get **{ Error: missing_permission
    at Remote IPC Process
 message: 'missing_permission' }**
2020-01-08 12:16:08 [log] [MyApp] otherApp.getVersion 1.2.0
───────────────────────────────────────────────────────
app.json:
  "permissions": [
    "homey:app:com.sdn.plextv-playlist-caster"
  ],
───────────────────────────────────────────────────────
app.js:
let otherApp = new Homey.ApiApp('com.sdn.plextv-playlist-caster');
otherApp.register();
this.log('Connected remote app...', otherApp);
otherApp
    .register()
    .on('realtime', this.log.bind(this, 'otherApp.onRealtime'))
    .on('install', this.log.bind(this, 'otherApp.onInstall'))
    .on('uninstall', this.log.bind(this, 'otherApp.onUninstall'))
    .get('/getPlaylists')
        .then( this.log.bind( this, 'otherApp.get') )
        .catch( this.error.bind( this, 'otherApp.get') )
───────────────────────────────────────────────────────
Obviously the remote app is being found. But any api call, even if the endpoints are made public is failing with the very same error message.
Any ideas what could possibly be wrong here?

**Comment by jeroenwienk** [comment]
If this is still an issue please reopen.
