### ISSUE TITLE
P1 monitor reports return energy as solar energy

### ISSUE THREAD

**Issue by Thalassa47** [athombv/apps-sdk-issues#110]
I’ve a SolarEdge converter connected with the solar panels and a smart grid meter.
Homey get the smart meter data via P1 monitor and the solar data via Zonnepalen app with the SolarEdge API key.

In the overview Homey makes in my opinion the wrong calculation.
Homey adds up the solar energy and the energy supplied!

**Comment by WeeJeWel** [comment]
Most likely the solar panels are reporting their value as a negative number. They should provide a positive number, e.g. `1000` (W).

**Comment by Thalassa47** [comment]
In my opinion is there a simple solution for this issue.
In the app P1 monitor under the tag P1-meter Verbruik ->settings->advanced settings there is the option “Bring energy in total yes / no”

I would also like this option for the P1-meter Teruglevering
