### ISSUE TITLE
i18n translation is not working for capabilities of type enum 

### ISSUE THREAD

**Issue by j0bro** [athombv/apps-sdk-issues#111]
1) Assume an `app.json` that defines a capability as below:
```
 "fruit": {
  "type": "enum",
  "title": {
    "en": "Fruit",
    "nl": "Fruit"
  },
  "getable": true,
  "setable": false,
  "values": [
    {
      "id": "apple",
      "title": {
        "en": "Apple",
        "nl": "Appel"
      }
    },
    {
      "id": "orange",
      "title": {
        "en": "Orange",
        "nl": "Sinaasappel"
      }
    }
  ]
}
```
2) Then also assume a Homey device like the following, which may receive a `fruit` event that has a `type` property which may be set to one of `['apple', 'orange']`:
```
'use strict';
​
const Homey = require('homey');
​
class FruitDevice extends Homey.Device {
  onFruitEvent(fruit) {
    this.setCapabilityValue('fruit', fruit.type);
  }
}
​
module.exports = FruitDevice;
```
3) Expected behaviour: Homey automatically translates device values into the applicable translated i18n strings.
4) Observed behaviour: Homey does not translate anything.
5) Workaround: Use a string type capability (instead of enum) and leverage the default i18n mechanism using `/locales/*.json` files.

This issue was filed after triage together with @WeeJeWel on the Homey Developers Slack channel 01-Feb-2020.

**Comment by RobinBol** [comment]
Hi! I tried to reproduce your issue, but without success:

![image](https://user-images.githubusercontent.com/5762579/74918839-fdcfb000-53c9-11ea-944f-04c3143daea4.png)

I used your exact example with:
```javascript
    this.setCapabilityValue('fruit', 'apple')
      .then(res => {
        console.log('success', res)
      })
      .catch(err => {
        console.error('error', err);
      })
```

I used the latest Homey firmware version (v4.0.0). Could you provide more information on your expectations and observations?

**Comment by WeeJeWel** [comment]
Closed due to inactivity.
