### ISSUE TITLE
Using addCapability / removeCapability crashes Android App

### ISSUE THREAD

**Issue by Thorarin** [athombv/apps-sdk-issues#112]
While developing my Homey App, I was experimenting with dynamically adding/removing capabilities from devices (for compatibility reasons). I've noticed the Android app is doesn't deal with this very well. Specifically, I frequently get completely white screens. I'm assuming this means something unexpected happened, because using the phone's "back" button caused the app to close as well.

Adding or removing capabilities **when saving device settings** is almost guaranteed to result in a  Android app crash. Only on rare timing occasions does this seem to work.

To work around this issue, I figured I would only add or remove capabilities only during device **during initialization** (`onMeshInit`). If the user changed a setting that affects capabilities, I would prompt them to restart my app. Unfortunately, most of the time this also results in the same crash/white screen.

I'm guessing this is related to the Android app making assumptions about devices not changing, but it could also be an issue with the App SDK itself. In any case, since it's directly linked to specific API calls, I thought it wouldn't hurt to post here.

Android App version: 3.2.0, 4.0.1
Homey version: 3.2.1, 4.0.0-rc5

**Comment by WeeJeWel** [comment]
Thank you for reporting this issue, we'll try to reproduce and fix it a.s.a.p.

**Comment by Christian-Athom** [comment]
Hi Thorarin,

Is it possible for me to test your application to see what the exact problem is?

**Comment by Thorarin** [comment]
> Is it possible for me to test your application to see what the exact problem is?

Yes, although you would need a Strips Guard/Comport/Drip to run the exact code. 

To place it into context:
What I was trying to do, is to make capabilities depend on device settings. Strips Comfort and Drip share a Z-Wave product ID, so they got added as a "hybrid" device with all the capabilities. I wanted to give users the option to hide the capabilities they may not be using.

This is my work-in-progress branch that I pushed in haste 🙂 
https://github.com/Thorarin/com.sensative/tree/feat/dynamic-capabilities

Here's a bit of commented out code to enable changing the capabilities when saving device settings:
https://github.com/Thorarin/com.sensative/blob/feat/dynamic-capabilities/drivers/1102011/device.js#L58

Right now, I have that disabled, and I prompt the user to restart the Sensative app. It crashes less often that way, but it's far from ideal.

**Comment by Christian-Athom** [comment]
Are you trying to add/remove maintenance actions?

**Comment by Thorarin** [comment]
Removing maintenance actions is one of the things that triggers it. Normally I wouldn't remove them, but HomeyKit gets confused by them (https://github.com/swttt/com.swttt.homekit/issues/187), so I wanted to give users the option of removing them if they use HomeyKit*.

However, removing maintenance actions is not my only use case. See the explanation about Strips Comfort/Drip. Also devices that were paired with an older version of the app lacked some capabilities which are added upon upgrading, but usually people aren't using the Android app right at that moment, so I imagine that usually won't be an issue.

*:  It's a workaround, but Robert Klep wasn't convinced that my pull request for HomeyKit (https://github.com/swttt/com.swttt.homekit/pull/188) solves it without negative side effects. It involves using `device.capabilitiesObj` instead of `device.capabilities`. It might not necessarily be always available though.

**Comment by Christian-Athom** [comment]
Hi,
I tested the add/remove of capabilities in the app, but i cannot reproduce your problem.
Is it possible that you DM or Email me an invite to your Homey so i can diagnose this problem?

Greetings,
Christian

**Comment by Thorarin** [comment]
The currently installed version of the app only changes the capabilities when the app starts, perhaps that is why. That particular crash happens less often, but still easily over 50% of the time for me.

1. Go to the device settings of Strips Drip/Comfort
2. Toggle maintenance actions on or off
3. Save
4. Return to the home screen
5. More → Apps → Sensative → gear icon
6. Choose Restart app
7. After a few seconds: blank screen

Here's a screen recording. Somehow it nerfed the quality on upload, but whatever:
https://1drv.ms/v/s!AqaRMuhaZ4Wxgs8-v-J87YmdIhPGrw?e=AxpABF

One additional note: I have all 3 strips devices as favorites.

If you prefer I can put back the version that tries to change the capabilities as soon as you save the device settings. Ideally I would like to be able to do that safely, because the procedure described above is already a workaround.
