### ISSUE TITLE
Signal strength and signal quality capability

### ISSUE THREAD

**Issue by MichalFoksa** [athombv/apps-sdk-issues#114]
Good day,

I would like to suggest a new capability to display signal strength and/or signal quality.

Signal strength measured in `db` and signal quality in percentage.

What do you think?

**Comment by WeeJeWel** [comment]
I don't think this is very useful as a system capability, but you can add it to your app yourself. Example:

```
{
  "type": "number",
  "title": {
    "en": "Signal Strength"
  },
  "units": "%",
  "min": 0,
  "max": 100,
  "getable": true,
  "setable": false,
  "icon": "/assets/capabilities/signal_strength.svg"
}
```


[signal_strength.svg.txt](https://github.com/athombv/homey-apps-sdk-issues/files/4305321/gardena_wireless_quality.svg.txt)

**Comment by MichalFoksa** [comment]
Thank you for hint!
