### ISSUE TITLE
Speakers' speaker_duration & speaker_position are not showing in the UI

### ISSUE THREAD

**Issue by Shakesbeard** [athombv/apps-sdk-issues#116]
Despite the capabilities being defined for the device and the values being updated accordingly the playback progress is not showing in the UI.

**Comment by WeeJeWel** [comment]
That's correct, and we don't have any short-term plans to show them.

Showing a progress bar is a tricky thing to do when the speaker doesn't emit realtime events. And in our experience, most devices don't. So for now I'll close this issue, but thanks for reporting!
