### ISSUE TITLE
api.js ignoring public true

### ISSUE THREAD

**Issue by davyrolink** [athombv/apps-sdk-issues#12]
I'm on 2.0-rc3 trying to create a app with a public api, but it seems to ignore the "public: true".

When opening `http://<my-homey-ip>/api/app/<my-app-id>/` I only get a 401 unauthorised response:
```
{
    "code": 401,
    "error": "not_logged_in",
    "error_description": "You need to log in to access this resource"
}
```
Same http 401 response when using `https://<cloudid>.connect.athom.com/api/app/<my-app-id>/`

Source of my api.js:
```
module.exports = [
    {
        method: 'GET',
        path: '/',
        public: true,
        fn: function (args, callback) {
            callback(null, 'OK')
        }
    }
];
```

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.8
