### ISSUE TITLE
Cannot POST /oauth2/callback/ message when using callbacks after end-user logged in with Apple Id

### ISSUE THREAD

**Issue by drme** [athombv/apps-sdk-issues#120]
in our homey app end-user can login with apple Id
unfortunately, it does not work, as in the authentication flow we have to provide call back URL that apple will call after successful end-user login.
however apple do POST instead of GET and your server just  shows error page.
Do we need new sdk, homey firmware, can be anything fixed on your side?

here is app in question: https://developer.athom.com/apps/app/no.adax.smart-heater.homey-app/build/4

In auth flow we go to address: https://callback.athom.com/oauth2/callback/?code=3b78HyqRDDD1fPJXhd1Ir0fuLSWMpQ&state=null
and we get response:
Cannot POST /oauth2/callback/

thanks

**Comment by WeeJeWel** [comment]
So Apple does `POST https://callback.athom.com/oauth2/callback/?code=3b78HyqRDDD1fPJXhd1Ir0fuLSWMpQ&state=null`?

**Comment by drme** [comment]
yes

**Comment by WeeJeWel** [comment]
Should work now!

**Comment by drme** [comment]
thanks, It works
