### ISSUE TITLE
Flow triggers for custom capabilities documentation wrong

### ISSUE THREAD

**Issue by Joolee** [athombv/apps-sdk-issues#122]
The documentation states:
> Calling ```setCapabilityValue('measure_my_number', 1)``` will try to start a Flow trigger with ID ```measure_my_number_changed```, with a Tag ```value```

The tag name should be (for this example) ```measure_my_number``` and _not_ ```value``` as written in the documentation. Otherwise, the cards will not be triggered.

**Comment by WeeJeWel** [comment]
You're absolutely right, it has been corrected!
