### ISSUE TITLE
Curtain switch control problem / BUG

### ISSUE THREAD

**Issue by smizaden** [athombv/apps-sdk-issues#125]
Hello, I'm having problem with compatibility app function ( opening and closing Blinds through app) . It's products compatible with homey. I'm having trouble to move blinds up and down with the app. I think there is problem with the application or coding because the Curtain controller (made by company NEO Coollcam) is physically working. I hope this description is clear. If you have some questions please let me know. I attached photo which is describing my problem.. when I move the button on application the curtain is not moving. And it is also not showing current position of blinds.

**Comment by WeeJeWel** [comment]
Hi @smizaden!

I'm sorry to hear you're having issues with your NEO Coolcam app.

However, this issue tracker isn't the right place, it's for SDK-issues only, where developers can submit issues they're having while developing a Homey app.

I suggest you take your issue to the developer of the NEO Coolcam app.

Good luck!

**Comment by smizaden** [comment]
Thank you for your answer.
Best regards

Denis Smizansky
