### ISSUE TITLE
Multiple `termostat` UI Component Support

### ISSUE THREAD

**Issue by StefanHolst** [athombv/apps-sdk-issues#126]
I'm currently experimenting with creating support for an oven in homey. This device has a thermostat for the oven itself and a temperature prope that activates an alarm when a target temperature is reached.

Ideally this device would use these capabilities:
- `target_temperature.oven`
- `measure_temperature.oven`
- `target_temperature.probe`
- `measure_temperature.probe`

This however, is not supported with the Homey, see [#103](https://github.com/athombv/homey-apps-sdk-issues/issues/103#issuecomment-555487656).

An alternative (although less ideal) would be to use the `slider` UI component, but the numeric value is not displayed for the user, see [#18](https://github.com/athombv/homey-apps-sdk-issues/issues/18).

**Comment by Christian-Athom** [comment]
Hi Stefan, i have created an internal issue for this so we can discuss how this can be implemented in the future.

**Comment by StefanHolst** [comment]
Hey @Christian-Athom, great. Looking forward to a solution.

**Comment by Christian-Athom** [comment]
This issue was solved in Mobile App version 6.2.0
