### ISSUE TITLE
Home Easy v1.5.2 SDK issue

### ISSUE THREAD

**Issue by chrisboer** [athombv/apps-sdk-issues#129]
Error message SDK version is not supported.

After update to Homey 5.0.0. rc17

**Comment by WeeJeWel** [comment]
This app is probably using Apps SDK v1, which has been removed in Homey v5.0.0.

**Comment by chrisboer** [comment]
It is an app created by Athom ? so why is this not updated !

**Comment by chrisboer** [comment]
Ik zie dat deze EOL is deze app maar wel vreemd dat iets door Athom b.v. ontwikkeld niet gecontinueerd wordt of herschreven wordt met nieuwe SDK werkte prima tot 5.0.0.0
