### ISSUE TITLE
Error `Invalid servicesFilter, expected Array` on BlePeripheral::discoverServices

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#13]
Trying to work around the issue: https://github.com/athombv/homey-apps-sdk-issues/issues/11

There is another issue i've triggered:

When calling:
```
service.discoverCharacteristics((error, characteristics) => {
   //....
}
```
(at line: https://github.com/koktaildotcom/homey-mi-flora/blob/29c34d9b7ec2153f2f1756405d32281449b6b6b7/lib/MiFloraDriver.js#L243)

I got a error:
```
(node:8955) UnhandledPromiseRejectionWarning: Error: Invalid servicesFilter, expected Array
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/BlePeripheral.js:1:1458)
    at Homey.app.discover.then.then (/lib/MiFloraDriver.js:236:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I've added the code to reproduce in: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-rewrite-discover-services-strategy

**Comment by koktaildotcom** [comment]
Still an issue on rc4

**Comment by koktaildotcom** [comment]
Still an issue with rc7

**Comment by koktaildotcom** [comment]
Still an issue with 2.0.0

**Comment by WeeJeWel** [comment]
I think the error is wrong because you should be getting `Invalid characteristicsFilter, expected Array`.

Anyway, the method is async, so providing a method as first argument makes it throw this exception.

**Comment by WeeJeWel** [comment]
See docs for reference: https://apps.developer.athom.com/BlePeripheral.html#discoverServices
