### ISSUE TITLE
SD3K onPair(session) oronPairListDevices keeps giving cannot read property name of undefined

### ISSUE THREAD

**Issue by dudz40** [athombv/apps-sdk-issues#131]
tried many ways, cannot get new devices in the app, it keeps giving cannot read property 'name' of undefined.

    onPair (v3session) {
        this.log('Pairing');
 
        v3session.setHandler('list_devices', async (data) => {
            let session = this.homey.settings.get('auth');
            await rachio.getDevices(session).then( (controllers) =>{
                Object.entries(controllers).forEach(function ([key, controller]) {
                    const devices = Object.entries(controller.zones).map(([key, zone]) => {
                        return {name: zone.name, data: {id: zone.id,},};
                    });
                    console.log(devices)
                    v3session.emit('list_devices', devices);
                });  
            });
        });

    }

**devices Map:**
`[
  {
    name: 'Gazon Achter',
    data: { id: '3563cbeb-591e-4487-a69b-64fdc2d16007' }
  },
  {
    name: 'Zone 8',
    data: { id: 'c098495a-8b9a-4192-afcc-caee51e1adee' }
  },
  {
    name: 'Druppel Links Achter',
    data: { id: 'f64b6228-4905-4961-b8f6-22b78c0dfbfb' }
  },
  {
    name: 'Zone 6',
    data: { id: '3bab3bae-98b1-4685-8400-809e99f419f3' }
  },
  {
    name: 'Zone 7',
    data: { id: '72e5e264-4d90-4eec-8593-356d8828feff' }
  },
  {
    name: 'Druppel Voor',
    data: { id: '3c777e1d-a66d-4e4f-81ad-7fe291289f4f' }
  },
  {
    name: 'Gazon Voor',
    data: { id: '6df42cdc-603d-41f2-ae81-b3c9ccf97a7e' }
  },
  {
    name: 'Druppel Rechts Achter',
    data: { id: '1ff6d08e-0bd1-4927-bff1-8c6ed92ce3fb' }
  }
]`

**Comment by WeeJeWel** [comment]
Hey! You almost got it working. Simply return the devices array from the handler function, instead of emitting it!

**Comment by dudz40** [comment]
-->Sorry forgot to put that piece of code back to what is was, tried to see if this made a differnce, it used to be: return devices, with the same result

**Comment by dudz40** [comment]
devices map assignment has to be outside the setHandler event code.  Then it works.
