### ISSUE TITLE
meter_power kWh unit misspelled

### ISSUE THREAD

**Issue by DiedB** [athombv/apps-sdk-issues#132]
See the screenshot in https://github.com/DiedB/Homey-SolarPanels/issues/110#issuecomment-664237413

Might be only in the Dutch translation, but the `meter_power` capability uses `KWh` as a unit, should be `kWh`.

https://en.wikipedia.org/wiki/Metric_prefix

**Comment by WeeJeWel** [comment]
You're absolutely right, thanks, it has been fixed and will be shipped in a future Homey release!
