### ISSUE TITLE
Black screen when use sub-capability of target_temperature

### ISSUE THREAD

**Issue by maxinminax** [athombv/apps-sdk-issues#134]
As the title, the Homey App will show device detail as black screen when I use sub-capability of target_temperature (exp. target_temperature.freeze) without any message in mobile app or dev console

**Comment by Christian-Athom** [comment]
@maxinminax What is the app repo you are working in?, so we can test this issue and see where the problem is located.

**Comment by Christian-Athom** [comment]
This issue was fixed in Mobile App version 6.2.0
