### ISSUE TITLE
SDK Ducumentation issue - Pairing System Views

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/apps-sdk-issues#135]
Under the Documentation Page of the Pairing and the Topic System Views the links are not the same as provided via the Menubar when access the System views menu item:

http://developer.athom.com/docs/apps/tutorial-Drivers-Pairing.html

![grafik](https://user-images.githubusercontent.com/28244954/90555803-3513f380-e198-11ea-9b82-b729d3de5672.png)
![grafik](https://user-images.githubusercontent.com/28244954/90555960-70162700-e198-11ea-9a27-c82722c090e7.png)
![grafik](https://user-images.githubusercontent.com/28244954/90555868-4d840e00-e198-11ea-9887-9ca1b7c006a6.png)

**Comment by tjallingt** [comment]
Thanks for reporting! Sorry for the slow reply, this will be fixed soon (whenever the next documentation deploy happens) :)
