### ISSUE TITLE
athom cli doesnt give correct sdk on homey with sdk 3

### ISSUE THREAD

**Issue by nattlip** [athombv/apps-sdk-issues#137]
![homey api 2 version 5 ](https://user-images.githubusercontent.com/7040452/90962367-bd9fd600-e4af-11ea-9831-c770b87d18f3.jpg)

**Comment by tjallingt** [comment]
This is actually the web api version which isn't the same as the SDK version.
However this is somewhat confusing and not very helpful information so we're removing it :) 
See: https://github.com/athombv/node-homey/pull/69
