### ISSUE TITLE
Homey Flow Webeditor - Cursor moves to end

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#139]
When there is a quote (") in the text field, all new characters is moved to the end of the text field. The mouse cursor is also moved to the end of the text field no matter where the cursor is placed in the text field.

**To recreate it:**
1. Put in some gibberish text in a text field in a flow card.
1. At the end, in the middle or at the beginning of this text, put in a quote character (")
1. No matter where you try to place the mouse cursor or go backwards in the text with the arrow keys, the cursor stays at the end or behind the last character. Every new character is placed at the end...

**This happens on the following devices and browsers (where i have tested it, probably happens on more):**

### OSX (10.15.6):
- Safari (13.1.2)
- Chrome (84.0.4147.135)

### Windows 10 (1909)
- Edge (80.0.361.54)
- Chrome (84.0.4147.125)

**Comment by mrlukasbos** [comment]
Thank you for reporting this issue. The Flow Web editor will be replaced with our [new Web App](http://my.homey.app). Because of the new Flow editor this issue won't be fixed.
