### ISSUE TITLE
Add support for batteries 'C'.

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#142]
I've a device that uses 'C' batteries. I cannot add them in the energy properties because they are not valid.

**Comment by WeeJeWel** [comment]
Thanks, we’ll add it. In the meantime, you can use OTHER.

**Comment by koktaildotcom** [comment]
Is this already implemented? I can add it with the new SDK 3 update.

**Comment by tjallingt** [comment]
Ah sorry slipped through my todo list. Ill pick it up on Monday :)

**Comment by tjallingt** [comment]
I added this yesterday, this will be available in 5.0.0.
The Homey CLI hasn't been updated yet but I'll make sure to do that soon :)

**Comment by koktaildotcom** [comment]
Thanks! I'll add the batteries into by app!
