### ISSUE TITLE
Bug: registerRunListener() accesses the wrong device

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#144]
Hi, I have the following situation:

- I have a device, this device has an internal api identifier in it's settings
- I have an action card that has an autocomplete arg
- The otpions for the autocomplete dropdown needs to be fetched from an external api and for this, the Id of the device is needed.

This is how the action looks like in the app.json:
    {
      "id": "recall_scene",
      "title":{
          "en": "recall a scene"
      },
      "args": [
          {
              "type": "autocomplete",
              "name": "scene",
              "placeholder": {
                  "en": "Search for scenes..."
              }
          }
        ]
    }

In the device.js I have the following:

		let recalSceneAction = new Homey.FlowCardAction('recall_scene');
		recalSceneAction
			.register()
			.registerRunListener(async (args, state) => {
				...
			})
			.getArgument('scene')
			.registerAutocompleteListener((query, args) => {
				return new Promise((resolve) => {
					this.log('recal scene for '+this.getName())
...

This appears to work fine, but the problem is the following: If I have multiple of this devices instanciated, this.getName() always returns the first device instance and never the one the user selected to create the card from!

**Comment by robertklep** [comment]
@MadMonkey87

I think this is because a `FlowCardAction` can only be registered once during the lifetime of a driver, which means it will be registered for the first device that calls this code (and hence will only call that particular handler). That's why it's typically registered in `driver.js`, not `device.js`.

I don't know specifically about autocomplete listeners, but if you want to pass device instances to regular run listeners, you can define a `device` argument in `app.json`:
```
"args": [
  {
    "name": "device",
    "type": "device",
    "filter": "driver_id=XXX"
  },
  …
]
```

Where `XXX` is the id of your driver.

In the listener, you can access it as `args.device`.

**Comment by MadMonkey87** [comment]
I tried exactly that and it kind of works, but it not what a user would expect: you choose a action card by selecting the device, then you have to select the device again in the flow card params.

Or in other words: inside the registerRunListener, how can I access the device the acrion card depends on?

**Comment by robertklep** [comment]
@MadMonkey87 can you explain how you think the action card can know on which device it depends? The user somehow needs to be able to set the device the action card is applied to.

**Comment by WeeJeWel** [comment]
Are you using driver.flow.compose.json? If so, then you do not need to add a device argument yourself, Homey CLI compose does it for you.

If you’re using compose, you can access the device with args.device.

**Comment by MadMonkey87** [comment]
I've learned a few things now;)
First, as mentioned above, the action card already has a hidden device arg. This can be used to access the selected device. Do not add this arg manually as you then kind of overwrite this and you then have a device selector in the action card (what you do not want as you already selected the device). 
Furthermore it is absolutely required that the listener gets registered only once and thus this should not be done in the device class itself. Last but not least I was accessing a property of the device that was setup dynamically so that does not work here.

**Comment by WeeJeWel** [comment]
@tjallingt what about a warning  in the console when you're overwriting a FlowCard run listener?
