### ISSUE TITLE
Bug: wrong units for PM2.5 capability

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#145]
According to the doc the unit for the capability PM2.5 should be μg/m3 -> https://developer.athom.com/docs/apps-reference

Unfortunately this is not the case as it is rendered as "ppm" which is wrong

Note: pm2.5 is an official capability while pm10 is a custom one with the correct units

![Screenshot_20200911-162044_Homey](https://user-images.githubusercontent.com/29612400/92936784-d403d680-f44a-11ea-8328-3d00196814ea.png)

**Comment by MadMonkey87** [comment]
Any update on this? Should be quiet easy to fix;)

**Comment by mrlukasbos** [comment]
Yep, that doesn't seem right. We will let you know in this thread when a fix is available!
