### ISSUE TITLE
Some typings for BLE-related classes are wrong

### ISSUE THREAD

**Issue by tobias-theobald** [athombv/apps-sdk-issues#146]
The typings for `ManagerBLE` at https://github.com/athombv/node-homey/blob/master/sdk/manager/ble.d.ts suggest that the functions `find` and `discover` run synchronously and directly return `BleAdvertisement` or an array thereof. 

This is not correct though. My experiments show that they return a promise of the mentioned values. Therefore

```
discover(serviceFilter?: string[], timeout?: number): BleAdvertisement[];
find(peripheralUuid: string, timeout?: number): BleAdvertisement;
```

should be 

```
discover(serviceFilter?: string[], timeout?: number): Promise<BleAdvertisement[]>;
find(peripheralUuid: string, timeout?: number): Promise<BleAdvertisement>;
```

Of course the JSDocs would also have to be modified.

---

The type of `BleAdvertisement.manufacturerData` at https://github.com/athombv/node-homey/blob/master/sdk/lib/BleAdvertisement.d.ts is given as `string`, where they are in fact returned as `Buffer | undefined`

--- 

The type of `BleAdvertisement.serviceData` at https://github.com/athombv/node-homey/blob/master/sdk/lib/BleAdvertisement.d.ts is given as `string[]`, where they are in fact returned as `{uuid: string, data: Buffer}[]`

**Comment by mrlukasbos** [comment]
The Typings have been fixed. Thanks for reporting!
