### ISSUE TITLE
Bug: Adding maintenance capability for unavailable device does not work

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#147]
I've just added a maintenance action to my app as described here: https://apps-sdk-v2.developer.athom.com/tutorial-Drivers-MaintenanceActions.html

As this also should work with devices created before my app update I did this not in the app.json but by code, i.e

				this.addCapability("button.repair")
				this.setCapabilityOptions(
					"button.repair", 
					{     
						"maintenanceAction": true,
						"title": { 
						"en": "Repair"
						},
						"desc": { 
							"en": "Attempts to repair a device after it has been re-added to deconz (i.e if there were connectivity issues and you needed to remove and pair the device again)."
						}
					})

This works perfectly fine for most devices, I just noticed that the maintenance action won't show in the UI for devices that have been set to unavailable. This is quiet unfortunate as you might want to perform maintenance actions especially on these kind of devices

**Comment by WeeJeWel** [comment]
This is by design. We think a device should auto-heal and a single button press is something that can be done programmatically in an interval as well!

For actual repairing where using input is required (e.g. a new pincode or pressing a button), there's the 'repair' views.
