### ISSUE TITLE
Homey 2.0 capabilites icons not show

### ISSUE THREAD

**Issue by Maxmudjon** [athombv/apps-sdk-issues#15]
![image](https://user-images.githubusercontent.com/23142922/50101572-c94fe980-0244-11e9-93c3-f142314321e3.png)
![image](https://user-images.githubusercontent.com/23142922/50101734-2f3c7100-0245-11e9-8845-5be45a35f422.png)

**Comment by koktaildotcom** [comment]
I can confirm this.

I've tried also with:
```
"uiComponent": "sensor"
```
In the `"capabilities"` root

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.8 and the newest app.

A custom capability can now have an `icon` property, that's a path [String] relative to the app's root. Example: https://github.com/athombv/com.rituals/commit/7fb943ad479d2b9a4558c2892b0e12bcf51f34ae

**Comment by koktaildotcom** [comment]
> Fixed in v2.0.0-rc.8 and the newest app.
> 
> A custom capability can now have an `icon` property, that's a path [String] relative to the app's root. Example: [athombv/com.rituals@7fb943a](https://github.com/athombv/com.rituals/commit/7fb943ad479d2b9a4558c2892b0e12bcf51f34ae)

I cannot find the example...

**Comment by WeeJeWel** [comment]
Whoops, that was a private repo.

Example custom capabilitity:

```
{
	"type": "string",
	"title": {
		"en": "Fill"
	},
	"getable": true,
	"setable": false,
	"icon": "/drivers/diffuser/assets/icon-fill.svg"
}
```

**Comment by Maxmudjon** [comment]
I can set custom icons for alarm_motion (alarm_motion.vibrate) ?

**Comment by WeeJeWel** [comment]
No you can't have different icons for sub-capabilities. You should create a capability `alarm_vibrate`.

**Comment by TedTolboom** [comment]
@WeeJeWel if you accept the PR (of November 8th), then the capabilities (alarm_vibration, alarm_drop, alarm_tilt and measure_tilt) I defined for the Aqara Vibration sensor can be re-used by @Maxmudjon: https://github.com/athombv/node-homey-lib/pull/135

**Comment by WeeJeWel** [comment]
I will in an update later than Homey v2.0, first we want to focus on getting that to stable.
