### ISSUE TITLE
unable to publish

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#150]
Hi, it seems publishing to the store is currently not possible anymore, I only get the following error:

![image](https://user-images.githubusercontent.com/29612400/97857003-63b45b80-1cfd-11eb-9c5c-e7dbcf090142.png)

I already tried with logging in again but had no success so far

Edit: it seems to do something in the store but doesnt look right:

![image](https://user-images.githubusercontent.com/29612400/97857175-9d856200-1cfd-11eb-982a-12d5b439d22b.png)

**Comment by WeeJeWel** [comment]
This has been solved last week. Thanks for reporting!
