### ISSUE TITLE
Homey.done clears screen, doesn't close

### ISSUE THREAD

**Issue by ultimate-tester** [athombv/apps-sdk-issues#153]
While working on my very first app, I'm having trouble with the pairing process.
I created a custom view, just 1. I've added a form, with a javascript listener attached to the submit event.
The event listener triggers and calls Homey.createDevice. In its callback I call Homey.done.
When I do this, I see the screen clears out (white). The title remains but that's it. When I manually close the pairing wizard, I can see the device has been created.

What am I missing to have the pairing wizard closed?

**Comment by ultimate-tester** [comment]
@Christian-Athom  is this still the correct channel to talk about these issues or am I following the wrong procedure?

**Comment by Christian-Athom** [comment]
Hi, at first glance it sounds like an issue within your app, and not the apps sdk itself. 

Have you tried our community developer forum or Slack channel to get help with this issue?

Best regards, 
Christian

**Comment by ultimate-tester** [comment]
Hi Christian, thanks, I'll be sure to go to Slack to try to get it resolved that way. Thanks!
