### ISSUE TITLE
Non-Persistent Control States

### ISSUE THREAD

**Issue by ultimate-tester** [athombv/apps-sdk-issues#156]
New feature request: Have an option to make the Up/Tilt/Down controls non-persistent.
My blinds use a protocol that doesn't support call backs or state-requests. In other words, Homey doesn't know whether it's up or down. Homey tries to remember the state by storing the last pressed button so when you open the screen again it highlights the button that Homey _thinks_ is the current state, I'm talking about this control:

![IMG_9146](https://user-images.githubusercontent.com/580758/102224119-d5c7b500-3ee5-11eb-9a4c-18cc28ed09d0.PNG)

However, if Homey has the wrong state, then there's no way to press the same button anymore. Let's say the stuck-state is Up, then I first have to press the Down button before pressing the Up button again. Especially with the small delay there is in this, it will result in hearing my blinds go down and then go up again. This is not even the worst, because if I go full-lazy-mode, I cannot tell my Google Assistant to simply send the Up command to the blinds because Homey blocks it (it thinks it's already Up), so I tell my Google Assistant to go down and then up which adds even more delay and already moves the blinds so much that my neighbors think I'm an idiot or a kid is playing with the blinds.

This can all be solved if Homey just doesn't try to remember the state. My advice is that there's an additional setting (automatically) added to the General- or Advanced Settings section of apps that use this control, to be able to uncheck the "State Persistence" mode.

**Comment by WeeJeWel** [comment]
You can create a custom capability with a `getable: false` and `ui: "ternary"`.
