### ISSUE TITLE
[Bug] Racing condition when writing variables

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#158]
Consider the following scenario:
- there is one logic variable "foo" (number), set to 0
- there are 2 flows that start at the same time (i.e the same trigger) that calcualte and set the variable foo to foo +1

The expected behaviour then would be that  the variable value is 2, but in reality it is always 1. The reason for that seems to be that homey has no locking mechanism for this. Is that a bug or is it intended? If it is intended: why?

**Comment by jeroenwienk** [comment]
There is indeed no locking mechanism.
