### ISSUE TITLE
Error 404 when trying to use Homey.api

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/apps-sdk-issues#159]
Hi there,

I don't know if this is the right git repo, but I have some issues when using the Homey.api function. I've been using this for over a decade in the Trashcan app, but it suddenly seems to have stopped working (maybe due to Homey 5.0 rc X).

The source of the app can be found here, if you want to debug locally: https://github.com/robertraaijmakers/com.trashchecker/tree/beta

What I'm trying to do is using Homey.api on the settings page of the app (when the user presses save changes).
This function should call a custom API in the 'root', and this API is located in api.js.

This has been working quite some time, but suddenly broke. Is this due to the new v3 SDK? 

index.html
```
Homey.api('POST', '/', {
        		"postcode":pc,
        		"housenumber":num,
        		"country":country,
				"api": apiSelected
        	}, function(err,result) {
```

response after calling the Homey.api
```
Request URL: https://192-168-178-xxx.homey.homeylocal.com/api/app/com.trashchecker/
Request Method: POST
Status Code: 404 Not Found
Remote Address: 192.168.178.xxx:443
Referrer Policy: strict-origin-when-cross-origin
```

```
{code: 404, error: "not_found", error_description: "Not found: POST /api/app/com.trashchecker/"}
code: 404
error: "not_found"
error_description: "Not found: POST /api/app/com.trashchecker/"
```

**Comment by tjallingt** [comment]
Hiya, sorry for the slow response over the holidays (and happy new years)

The API was indeed changed in SDK v3, see "web api improvements" in the SDK Changelog: https://apps-sdk-v3.developer.athom.com/tutorial-SDK%20Changelog.html and the "web api tutorial": https://apps-sdk-v3.developer.athom.com/tutorial-Web%20API.html

It is quite confusing that it fails silently though so I will add a warning when we detect an `api.js` without associated `api` specification in `app.json`.

To make your apps api work again you can do the following:

add the following to your `.homeycompose/app.json`
```json
  "api": {
    "validateUserData": {
      "method": "POST",
      "path": "/"
    }
  }
```

and update your `api.js` to
```js
"use strict";

module.exports = {
  async validateUserData({ homey, body }) {
    console.log(body);
    return new Promise((resolve) => {
      homey.app.updateAPI(
        body.postcode,
        body.housenumber,
        body.country,
        body.api,
        (isValid, obj, apiId) => resolve(isValid)
      );
    });
  },
};
```

Hope this helps, sorry for the inconvenience.

**Comment by tjallingt** [comment]
with the next release experimental release of homey apps will log warnings when we detect apis that are missing from `app.json`.
Closing this issue now

**Comment by robertraaijmakers** [comment]
Hi @tjallingt, thank you for the clear explanation! Completely overlooked the changes in the documentation. But it is working like a charm now.
