### ISSUE TITLE
npm error in homey app run

### ISSUE THREAD

**Issue by pfassberg** [athombv/apps-sdk-issues#161]
I'm new to Homey and just installed the Homey SDK v2 using the guidelines in https://apps-sdk-v2.developer.athom.com/tutorial-Getting%20Started.html.

For each "homey app run" I get this error:
**Error occurred during npm prune TypeError: prunePathsJson.removed.map is not a function
    at Function.getPrunePaths (/usr/lib/node_modules/homey/lib/Modules/NpmCommands.js:106:49)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /usr/lib/node_modules/homey/lib/App/index.js:696:26**

I'm using node 15.5.0 and npm 7.3.0 under Ubuntu 20.04.1 LTS.

// Peter

**Comment by ArtemSyromiatnikov** [comment]
I'm experiencing the same on Node 15.7.0, npm 7.4.3 on windows 10. Homey SDK version 2.9.7.

The code in %AppData%\Roaming\npm\node_modules\homey\lib\Modules\NpmCommands.js is executing `npm prune` command, expecting an JSON object with an array property `removed`

``` js
const { stdout } = await exec(`npm prune --production --dry-run --json`, { cwd: path });
const prunePathsJson = JSON.parse(stdout);
const prunePaths = prunePathsJson.removed.map(pruneObject => upath.normalize(pruneObject.path) + upath.sep);
return prunePaths;
```

Yet when I manually execute the `npm prune --production --dry-run --json` command, the result is 
``` json
{
  "added": 0,
  "removed": 0,   <-- this is a Number, not an Array
  "changed": 0,
  "audited": 0,
  "funding": 34
}
```

**Comment by tjallingt** [comment]
Thanks for debugging this @ArtemSyromiatnikov 

We rely on the output format of the NPM CLI version 6 and clearly that got changed in version 7.
This wasn't a big problem because version 7 wasn't stable yet but just this week it was declared "generally available": https://github.blog/2021-02-02-npm-7-is-now-generally-available/

We will look into fixing this and ensuring the Homey CLI works with both NPM CLI version 6 and 7.

**Comment by ArtemSyromiatnikov** [comment]
Awsome news, thanks @tjallingt!

**Comment by tjallingt** [comment]
Should have been fixed in the latest Homey CLI release, sorry that it took a bit longer than expected.
