### ISSUE TITLE
Tokens with some characters in id not selectable in flow

### ISSUE THREAD

**Issue by fpalsson** [athombv/apps-sdk-issues#163]
When creating tokens with [ and ] in token id it is not possible to select the token in a flow using the logic flow card. It shows up in the list of tokens, and it is possible to click on it in the list, but the card contians an empty token when the UI returns to the card.

What characters are allowed? 

Should the SDK return an error if not allowed characters are used in the id?

**Comment by WeeJeWel** [comment]
Try to use only `A-Za-z0-9.-_` in the token's ID.

We want to add validation but it might break now because some apps already use other characters.
