### ISSUE TITLE
Capability: target_temperature, change max value

### ISSUE THREAD

**Issue by djfanatix** [athombv/apps-sdk-issues#164]
Is it possible to raise the maximum temperature (currently 50 degrees celcius) for target_temperature, thermostats, etc.. to a higher value (for example 100 degrees)

I am developping an app to monitor and control stored hot water by means of a thermostat controller.
(on-off-auto) and temperature settings.

**Comment by WeeJeWel** [comment]
Yes, add:

```json 
"capabilitiesOptions": {
  "target_temperature": {
    "max": 100
  }
}
```

To the driver json.
