### ISSUE TITLE
iOS app url scheme slow + deep linking url

### ISSUE THREAD

**Issue by k4mrat** [athombv/apps-sdk-issues#165]
When launching homey app on iOS using url scheme homey:// it's super slow to launch unless the app is already running in background. This is never an issue when using the real icon. I think it's weird since url scheme should be the same as launching the app from its icon?

Also, it would be much appreciated and very handy if the iOS app could support deep links so that shortcuts and widgets could directly link to devices (and maybe even trigger actions) with something along the line of homey:device-[id]-measure_temperature or turnOn for example.

**Comment by mrlukasbos** [comment]
Thank you for bringing this issue to our attention. Starting the Homey app using the url scheme `homey://` indeed takes much longer than expected and we will look into it.

About the widgets and deep links: that is definitely a nice suggestion. Perhaps we will look into it in the future.

**Comment by RobinBol** [comment]
Thanks for letting us known @k4mrat . I have created an issue in our internal issue tracker, so we will pick this up at some point. Since this issue tracker is used for Apps SDK issues only I will close this.
