### ISSUE TITLE
Enhance invalid_capability error

### ISSUE THREAD

**Issue by ricott** [athombv/apps-sdk-issues#166]
Hi,

May seem like a simple thing but I get the error `(node:9742) UnhandledPromiseRejectionWarning: Error: invalid_capability` at some random cases like removing a device and re-adding it. Don't know why, and since your error message doesn't tell me which capability that is invalid it makes debugging hard. 

May I propose that you add the name of the capability that is invalid when you create this error? Something like the below would be very helpful!
`(node:9742) UnhandledPromiseRejectionWarning: Error: 'xyz' is not a valid capability`

**Comment by WeeJeWel** [comment]
This is a fine suggestion, but I do really advice you to catch your methods and add logging yourself :)

In a future Homey version your app will crash when unhandled promise rejections occur.
