### ISSUE TITLE
SDK3: Cannot get argument values, missing device argument.

### ISSUE THREAD

**Issue by XeroxQ** [athombv/apps-sdk-issues#167]
With sdk3, something about flow argument devices is mested up.
If I use the “old” filter structuur: "filter": "driver_id=my_driver" like explained on your site, I get an error when I try the next:
const flowTrigger = this.homey.flow.getDeviceTriggerCard('trigger_flow');
flowTrigger.getArgumentValues();
Error: Cannot get argument values, missing device argument.
at FlowCardTriggerDevice.getArgumentValues (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/FlowCardTriggerDevice.js:36:13)
at refreshFlowTriggers (/drivers/upnpserverdriver/driver.js:43:36)
at FlowCardTriggerDevice.<anonymous> (/drivers/upnpserverdriver/driver.js:30:13)
at FlowCardTriggerDevice.emit (events.js:311:20)
at FlowCardTriggerDevice._update (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/FlowCard.js:75:10)
at ManagerFlow._onFlowCardUpdate (/opt/homey-client/node_modules/homey-apps-sdk-v3/manager/flow.js:162:17)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
and running it with a normal triggerCard (the rest of you examples):
const myAction = this.homey.flow.getTriggerCard (https://apps-sdk-v3.developer.athom.com/FlowCardAction.html) ('trigger_flow');
myAction.on('update', () => {
this.log('update');
myAction.getArgumentValues (https://apps-sdk-v3.developer.athom.com/FlowCard.html#getArgumentValues) ()
.then(args => {
// args is [{
// "my_arg": "user_value"
// }]
});
});
Gives the error:
invalid_flow_card_id
Which is very weird, ¡ because I can register listeners and everything, but retrieving the getArgumentValues seems impossible.
After the error’s I played around a lot, and when I changed my definition to "filter": {"driver_id":"upnpserver"} (JSON object instead of text based), I directly got a error when running the app that I was missing the parameter in my titleFormatted.
So it somehow only picked it up after changing the filter to the new way, even though that isn’t supposed to be (device should not be mandatory in the titleFormatting).
Here is my manifest:
{
"id": "turned_on",
"title": {
"en": "Turned on"
},
"args": [
{
"name": "my_device",
"type": "device",
"filter": "driver_id=upnpserverdriver"
}
]
}
Or can't I use .getArgumentValues (https://apps-sdk-v3.developer.athom.com/FlowCard.html#getArgumentValues) () when there is a device arg?

**Comment by tjallingt** [comment]
Hey @XeroxQ 

You should pass the device class to `getArgumentValues()`, see the documentation for the `FlowCardTriggerDevice ` https://apps-sdk-v3.developer.athom.com/FlowCardTriggerDevice.html#getArgumentValues 

If you are calling it from your device class (the class you define in `device.js`) you can call it like:

```js
const Homey = require('homey');

class MyDevice extends Homey.Device {
  async onInit() {
    const flowTrigger = this.homey.flow. getDeviceTriggerCard('trigger_flow');
    const arguments = flowTrigger.getArgumentValues(this);
  }
}
```

**Comment by XeroxQ** [comment]
Ah, thanks m8!

Met vriendelijke groet,

Arie J. Godschalk
