### ISSUE TITLE
SDK3: this.homey.__() gives wrong language back

### ISSUE THREAD

**Issue by XeroxQ** [athombv/apps-sdk-issues#168]
In SDK3 something goes wrong with this.homey.__() from the App but also Driver and Device.
i have for example:
en.json
{
    "languagecode":"en-GB"
}
nl.json
{
    "languagecode":"nl-NL"
}

When in my app for example i have 
    console.log( this.homey.__('languagecode') );
the responseis : en-GB (wrong), but my language is set to Dutch.

If i change the App to SDK 2 and run
    console.log( Homey.__('languagecode') );
i get nl-NL (correct)
and i dont see anything in the developer-tutorial that could explain this as being correct behavier.

**Comment by tjallingt** [comment]
Hey, thanks for reporting this issue. I was able to reproduce and fix it. We will release the fix as soon as possible.

**Comment by XeroxQ** [comment]
Great!

Met vriendelijke groet,

Arie J. Godschalk

**Comment by tjallingt** [comment]
should be fixed in a release coming soon!
