### ISSUE TITLE
SDK3: getting/showing local time using `Date`

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#169]
Because SDK3 apps run with `TZ=UTC`, `Date` methods that are supposed to return local time don't return local time anymore.

The SDK3 changelog states that _"It is still possible to retrieve the current timezone by calling `this.homey.clock.getTimezone()`, the timezone can then be used to format a date to the users timezone."_

No further information is given on _how_ this can be done. Since a lot of Homey developers aren't JS-wizards, it wouldn't be out of place to provide an actual example on how to do this.

Besides just formatting local time, it might also be beneficial to show how to retrieve the current local hour for a user (a `Date#getHours()` equivalent that works for `TZ=UTC`).

Some Homeyscript users are already running into issues because Homeyscript has been upgraded to SDK3 and some of their scripts are now an hour off because `Date#getHours()` doesn't do what it's supposed to do anymore.

**Comment by tjallingt** [comment]
I think developers should Moment.js for this and we definitely should recommend these libraries and show and example. Once we update to Node 14 the `Intl` API has access to the full ICU and developers should probably use [date-fns-tz](https://www.npmjs.com/package/date-fns-tz) or Luxon.
Curious to hear your thoughts

**Comment by robertklep** [comment]
`moment` with timezone support weighs in at around 6MB and considered a legacy project; `luxon` is smaller (3MB) but still considerable in size for a storage/memory-constrained device, but it's basically the only viable solution for app developers.

Homeyscript users are left out in the cold though, unless Homeyscript starts shipping with any of these libs like it does with `lodash` (having to use `new Date().toLocaleTimeString('nl-NL', { hour12: false, timeZone: (await Homey.system.getInfo()).timezone }).split(':')[0]` to get the local time seems a bit convoluted).

Ultimately, I don't understand why apps are running in `TZ=UTC` to begin with, it seems to cause more problems than it solves (yes, if a user changes their timezone and an app doesn't restart, things may break, but how often is that actually an issue?).

**Comment by fpalsson** [comment]
Any update on this?

**Comment by janhjordie** [comment]
I also have issues with my local time. It always return UTC, and I'm in Copenhagen, Denmark

**Comment by robertklep** [comment]
@janhjordie that's not an issue, that's intentional.

**Comment by janhjordie** [comment]
Yeah, I know UTC is international. But if I use toLocaleTimeString() it always returns UTC, it's only if I use toLocaleTimeString("da-DK") is gives me the local time string

And the getTimezoneOffset() is always 0, and that should be -120 right now based on the danish timezone.

**Comment by robertklep** [comment]
Again, that's intentional (I didn't mean "international" 😉). No one from Athom has yet explained _why_ they did it like this, only that they did and all developers should work with it 😩

**Comment by WeeJeWel** [comment]
Now we can say why we did this :) Apps made for Homey Cloud run across various regions, and the timezone of the datacenter might not be the same as the user's timezone. That's why!

**Comment by robertklep** [comment]
@WeeJeWel it sounds like you're solving an XY problem, I don't see any need to run local apps with TZ=UTC because of that (I have plenty of other cloud-based apps running on my Mac that don't need such a radical solution).

**Comment by janhjordie** [comment]
Well, in my HomeyScript i fetch electric spot prices from an external api, with spot prices for every hour, all day. The hour property is a local time without timezone, so not UTC.
And since the current date on Homey is UTC, the Homey date is 2 hours behind (-120 minutes).

I just thought the script was run on my local Homey hardware, and used the local position to set the timezone. 
if I run getTimezoneOffset on my browser, it gives -120, if I run it in the HomeyScript, it gives 0.

So it seems I have to change my code to handle it

**Comment by robertklep** [comment]
@janhjordie even more fun when DST switches off in a few weeks...

**Comment by thomaswitt** [comment]
Just ran into the same issue. I should be able to get the current time of Homey in a line of code without libraries.

A simple "Good Morning, the time is xx:xx" via e.g. Alexa should be easy out of the box

**Comment by jghaanstra** [comment]
Why is still still an issue 3 years later. I'm not even gonna fix this in one of my apps. Each developer having to use (large) external libraries just to show a date/time in the user's timezone cant be good practice and should be fixed in Homey SDK.

**Comment by WeeJeWel** [comment]
Here's an example to format time without an external library:

```js
'use strict';

const Homey = require('homey');

class MyApp extends Homey.App {

  /**
   * onInit is called when the app is initialized.
   */
  async onInit() {
    this.log('MyApp has been initialized');

    const tz = await this.homey.clock.getTimezone();

    this.log(`The timezone is ${tz}`);

    // Define a function to get the time in a specific timezone
    const formatter = new Intl.DateTimeFormat([], {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false, // Use 24-hour format
      timeZone: tz,
    });
    const timeParts = formatter.formatToParts(new Date());
    const hour = timeParts.find(part => part.type === 'hour').value;
    const minute = timeParts.find(part => part.type === 'minute').value;

    this.log(`The time is ${hour}:${minute}`);
  }

}

module.exports = MyApp;
```

Output on my Homey Pro:

```
─────────────── Logging stdout & stderr ───────────────
2024-05-22T18:39:58.243Z [log] [MyApp] MyApp has been initialized
2024-05-22T18:39:58.250Z [log] [MyApp] The timezone is Europe/Amsterdam
2024-05-22T18:39:58.316Z [log] [MyApp] The time is 20:39
```

**Comment by jghaanstra** [comment]
> Here's an example to format time without an external library:

Thanx!

**Comment by WeeJeWel** [comment]
I've added an example in the Apps SDK documentation at https://apps.developer.homey.app/upgrade-guides/upgrading-to-sdk-v3#app-timezone-now-always-utc.
