### ISSUE TITLE
Add posibility to show value in top right corner of device tile

### ISSUE THREAD

**Issue by SailingDuck** [athombv/apps-sdk-issues#17]
Currently thermostat devices show the temperature in the top right corner of the device tile. This is an ideal possibility to show other numeric values, like a temperature sensor or dimvalues. 

At Slack it was allready discussed this area is restricted, but made this issue if we can open up this area for sensor values or dim values too. 

![](https://files.slack.com/files-pri/T04E9KJ7T-FEW2LSDRR/image.png)

**Comment by daneedk** [comment]
And not only other numeric values. For Heimdall I want to be able to show an indicator on either or both the Surveillance Mode Switch and Alarm Off button that the alarm has been activated. 
(This is consistent with how a motion sensors handles a detected motion)

**Comment by WeeJeWel** [comment]
Thanks for the suggestion. We do not keep track of enhancements in this issue tracker, but it's definitely noted internally.
