### ISSUE TITLE
Wrong language in notification time line

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#170]
I was debugging my app and needed the TriggerCard to trigger multiple times in a row. When a TriggerCard is triggered to many times in a minute, the flow will be deactivated.

The notification created in the notification time line is in Italian! My Homey is in Norwegian..

That's kind of strange...

![image](https://user-images.githubusercontent.com/25814673/108599493-b93a7400-7391-11eb-9170-b567b9f31791.png)

Homey firmware: 5.0.0
Homey: Early 2019

**Comment by RobinBol** [comment]
@runely Thanks for reporting this issue, we have removed the faulty translation in Homey v5.0.1, which is available as Experimental release. It will now default to English and in the near future should receive a new translation in Norwegian.
