### ISSUE TITLE
SDk3: Possible issue or change in default localication?

### ISSUE THREAD

**Issue by XeroxQ** [athombv/apps-sdk-issues#172]
Hello,

I have an App in which this happends, but it also happends in Homeyscript.
Before SDK:
var a = new Date();
console.log(a);
console.log(a.getHours() + ':' + a.getMinutes());

result used to be:
2021-02-22T08:09:10.432Z
9:9
It would give me (today/right now) the Dutch time, and not the UTC. (Like i wanted, else i would use the getUTCHours ofc)

But when i run it now, i get:
2021-02-22T08:09:10.432Z
8:9

The same happends in Homeyscript, so i think it has to do with SDK3.

Is there something changed in default Locatization, or is this a bug?

Or could this have to do with: https://github.com/athombv/homey-apps-sdk-issues/issues/168

**Comment by XeroxQ** [comment]
I see https://github.com/athombv/homey-apps-sdk-issues/issues/169 is almost the same, so i guess only question remains: Is this a bug or on purpose? 
Should i take this new way of local date into my app and rewrite the parts that use local dates/times?

**Comment by jeroenwienk** [comment]
This is indeed intented, for more discussion please refer to the other issue.
