### ISSUE TITLE
Then flowcard for lock state gives an error "invalid_type"

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/apps-sdk-issues#174]
When using an action flowcard of a lock device with capability 'lock_mode', the flow gives an error when setting that lock_mode:
![image](https://user-images.githubusercontent.com/2014478/108904761-34648a00-761f-11eb-97ef-23af2547e004.png)

The device is added with the Virtual Devices app, using class 'lock' and capability 'lock_mode' (a.o.).
The action-flowcard is provided by the class/capability. There is no code for this in the VD-app.

![image](https://user-images.githubusercontent.com/2014478/108904398-b99b6f00-761e-11eb-83f3-98c7638f0591.png)

PS: SDK version is 2.

**Comment by jeroenwienk** [comment]
Thank you for reporting this. Should be fixed in the next Homey release.

**Comment by RobinBol** [comment]
@ArjanKranenburg Thanks for reporting this issue, we have implemented a fix in Homey v5.0.1, which is available as Experimental release. Could you verify that this update fixes the issue for you?

**Comment by ArjanKranenburg** [comment]
Thanks for the quick fix. This works OK with homeyVersion  5.0.1-rc.1.
