### ISSUE TITLE
my.homey.app crashes with non-excisting droptoken

### ISSUE THREAD

**Issue by XeroxQ** [athombv/apps-sdk-issues#177]
If you create a flow in my.homey.app (since sdk3 as far as i know this happands) and you have lets say a Logic Equels with a droptoken. If that droptoken is removed in the background, my.homey.app crashes.
I cant even get into the flow anymore in my.homey.app. Needed to remove the droptoken from the conditioncard through Homey App.

**Comment by XeroxQ** [comment]
This error is repeatable

**Comment by mrlukasbos** [comment]
Thank you for reporting the issue. Since this is a Homey Web App issue and not an SDK issue I will close it here, but I will forward your report to our Web App team.

**Comment by jeroenwienk** [comment]
Fix is live
