### ISSUE TITLE
Optimize `Util#deepClone` to prevent memory warnings

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#178]
While debugging an issue where users with a lot of Shelly devices were getting memwarns (and eventually, a killed app), @jghaanstra found that [`Driver#getDevice()`](https://apps-sdk-v3.developer.athom.com/Driver.html#getDevice) is the cause of a memory leak.

Digging a bit deeper, it looks like the actual cause of the leak is `Util#deepClone`:
```
function deepClone(object) {
  const raw = v8.serialize(object);
  return v8.deserialize(raw);
}
```

This is used by `Device#getData()`:
```
  getData() {
    return Util.deepClone(this[sData]);
  }
```

I can trigger a memwarn by calling `device.getData()` repeatedly. It takes a lot of calls (~15K depending on the size of a device's data), but since `Driver#getDevice()` on average will run through half of the devices of a driver the issue will eventually pop up, especially for users that have lots of devices for a particular driver.

Test code:
```
const driver = this.homey.drivers.getDriver('test');
const device = driver.getDevices()[0];
for (let i = 0; i < 15000; i++) {
  const data = device.getData();
}
```

**EDIT**: I just benchmarked `Util#deepClone` and it seems very slow:
```
• Suite#1...

  ✔  JSON      850,275.87  ops/sec  ±0.38%    (93 runs)  -61.68%
  ✔  v8          2,121.11  ops/sec  ±199.60%  (9 runs)   -99.90%
  ✔  lodash  2,218,801.04  ops/sec  ±0.52%    (90 runs)  fastest

  ➔ Fastest is lodash

# benchr script
const v8   = require('v8');
const _    = require('lodash');
const data = { id : 'my-device-id-1234' };

function cloneJSON(o) {
  return JSON.parse(JSON.stringify(o));
}

function cloneV8(o) {
  const raw = v8.serialize(o);
  return v8.deserialize(raw);
}

function cloneLodash(o) {
  return _.cloneDeep(o);
}

module.exports = (suite, benchmark) => {
  benchmark('JSON',   () => cloneJSON(data));
  benchmark('v8',     () => cloneV8(data));
  benchmark('lodash', () => cloneLodash(data));
}

```

It's also very unstable (the RME is very high, 199%).

So if the SDK doesn't specifically need the extras that `v8.{de,}serialize()` provides, a lodash replacement is much faster and doesn't use nearly as much memory.

**Comment by tjallingt** [comment]
Hiya,

I'm certainly not surprised that its slower/more memory intensive but how _much_ slower is definitely a surprise.
The main reason for choosing `v8#Serializer` was that the HTML Structured Clone algorithm behaves exactly the way you'd expect without any external dependencies.

I do wonder how it is possible that lodash uses less memory, I guess the serialize/deserialize actually allocates the cloned data 3x (original, serialized, cloned) while lodash deepClone only allocates the cloned data 2x 🤔  (if this is the reason probably `JSON#parse/stringify` will also use more memory right?). Regardless I'm not really sure this is a memory leak since the data will probably be garbage collected however if we allocate it quicker than it is collected it will still cause issues.

Ultimately the best "fix" here would be to `deepFreeze` the device data, we only clone it to prevent mutations (so we can use the device data to identify the device). I'm afraid that apps may be relying on mutating the device data though so I'm not sure that'd be a safe change.

It certainly seems using lodash's `cloneDeep` is the best solution here 👍

**Comment by robertklep** [comment]
> I do wonder how it is possible that lodash uses less memory

> I'm not really sure this is a memory leak since the data will probably be garbage collected.

With the following script I see a clear difference between using v8 and using lodash: using v8 doesn't decrease RSS by a whole lot after a few GC cycles, whereas with lodash it does drop much more significantly. The v8 serializer also uses much more memory. I tested using Node v12.18.3. It defaults to the v8 serializer, pass a random argument (`node script.js okay`) to make it use lodash.

```
const v8              = require('v8');
const _               = require('lodash');
const { memoryUsage } = require('process');
const gc              = (require('gc-stats'))();

gc.on('stats', function (stats) {
  const { totalHeapSize, totalHeapExecutableSize, usedHeapSize, mallocedMemory, peakMallocedMemory } = stats.after;
  console.log(`\n-------- ${ new Date() } --------`);
  console.log(`RSS                    : ${ memoryUsage().rss }`);
  console.log(`totalHeapSize          : ${ totalHeapSize }`);
  console.log(`totalHeapExecutableSize: ${ totalHeapExecutableSize }`);
  console.log(`usedHeapSize           : ${ usedHeapSize }`);
  console.log(`mallocedMemory         : ${ mallocedMemory }`);
  console.log(`peakMallocedMemory     : ${ peakMallocedMemory }`);
});

function deepClone(object, useLodash = false) {
  if (useLodash) {
    return _.cloneDeep(object);
  } else {
    const raw = v8.serialize(object);
    return v8.deserialize(raw);
  }
}

const useLodash = process.argv.length > 2;
const data      = { id : 1234 };

console.log(`Starting: RSS = ${ memoryUsage().rss }, using ${ useLodash ? "lodash" : "v8" } for serialization`);

for (let i = 0; i < 10000; i++) {
  const x = deepClone(data, useLodash);
}

setTimeout(() => {}, 100000);
```

**Comment by tjallingt** [comment]
I don't see whats holding on to the memory so it seems like you might have found a bug in Node.js?
Wonder if its possible to trigger this in Chrome by using `window.postMessage` 🤔

**Comment by tjallingt** [comment]
Should be fixed in a release coming soon :)

**Comment by ThomasHoussin** [comment]
Hi, Do you know if this issue is solved in latest Homey release ? I have a similar problem in an app with frequent calls to getDevices, I wonder if it could be the same issue ?

**Comment by robertklep** [comment]
@ThomasHoussin this was fixed quite some time ago, the SDK now uses `lodash.deepClone()`.

Since `getDevices()` doesn't do a whole lot my guess is that your problem is being caused elsewhere ("frequent calls to getDevices" suggests that you're using some sort of timer/interval, which are typically a good cause for memory leaks).

Is your code online somewhere? Also, why exactly are you calling `getDevices()` frequently? Perhaps there's an alternative.

**Comment by ThomasHoussin** [comment]
Thanks for your feedback. Yes, I scan BLE devices every minute, and I use getDevices in the loop to list devices and pass the BleAdvertisement to the device (the device is updated with data contained in BleAdv). I guess I can avoid using getDevices each time... 

Code is here : https://github.com/ThomasHoussin/com.thomashoussin.ruuvitag/blob/test/drivers/ruuvitag/driver.js

**Comment by robertklep** [comment]
@ThomasHoussin as a quick test, you can move the `getDevices()` out of the `while` loop and see if you still get memory warnings, but this code looks rather suspicious too:
```
ruuvitag.emit('updateTag', foundDevices.then(devices => devices.find(bleAdv => bleAdv.uuid == ruuvitagData.uuid)));
```

I would suggest waiting on the promise and emitting its results:
```
let foundDevices = await this.homey.ble.discover([], scan_duration * 1000);
...
ruuvitag.emit('updateTag', foundDevices.find(bleAdv => bleAdv.uuid == ruuvitagData.uuid)));
```
