### ISSUE TITLE
Show dimvalue option for dimcontrol

### ISSUE THREAD

**Issue by SailingDuck** [athombv/apps-sdk-issues#18]
Better Logic had a device that used a slider to set a numeric value/variable. The former mobile card used a combination of a slider and a sensor value next to each other. The slider in the new layout isn't showing the actual value you are about to set. I can show it on another page but that way you have to check everytime what value you set. 

Something like this:
![image](https://user-images.githubusercontent.com/23644634/50253081-503dc700-03e9-11e9-8753-5f5e9ad3ccc1.png)

Used to be like this, actual value inmideately visible:
![](https://forum.athom.com/uploads/editor/ji/6xvbxd6rwga9.png)

**Comment by WeeJeWel** [comment]
Thanks for the feature request, we'll consider it!

I'm closing this issue here as it's not an Apps SDK related issue.
