### ISSUE TITLE
Improve error reporting: invalid_capability at Remote Process

### ISSUE THREAD

**Issue by jghaanstra** [athombv/apps-sdk-issues#188]
Sometimes I see this stacktrace in a diagnostic report:
```
(node:20512) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote Process
(node:20512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

Obviously I'm trying to update a capability the is not available but this error does not tell me more than that. With an app with 30 drivers and around 6 capabilities per driver there is no way I can track down where this issue comes from. So my request, is it possible to supply more info when this error occurs. For instance what capability, and preferably what driver has caused the issue.

**Comment by tjallingt** [comment]
Yea we can definitely improve this error message to make debugging easier 👍

**Comment by jghaanstra** [comment]
It's the same for:
```
(node:2279) UnhandledPromiseRejectionWarning: Error: out_of_range
    at Remote Process
```

What capability is out of range for what device / driver.

**Comment by jghaanstra** [comment]
Can this please get some love, it's really becoming unmanagable for the Shelly app.

**Comment by robertraaijmakers** [comment]
Suddenly got 2300 crashes of my app. Haven't updated it in over a year with the message "Invalid_capability". I'm truly wondering what has changed in the Homey core and what capability isn't there anymore... Would be nice to know which capability is invalid, but seems this won't be fixed any time soon?

@jghaanstra @WeeJeWel

**Comment by WeeJeWel** [comment]
We are testing a Homey firmware with Node.js 16, which throws upon unhandled promise rejections.

Most likely your app calls `Device#setCapabilityValue(capabilityId, value)` without `.catch(err => ...)`, using a `capabilityId` that is not linked to the device.

**Comment by robertraaijmakers** [comment]
Thanks @WeeJeWel! Is there also a best practice with how to (silently) log these messages and make sure that they somehow end up with the application developer? Or is that not possible?

**Comment by WeeJeWel** [comment]
We will deploy an update today that will silence the e-mails coming from these errors :)
