### ISSUE TITLE
homey app driver create Fails in homeycompose world :)

### ISSUE THREAD

**Issue by saiaman** [athombv/apps-sdk-issues#190]
homey@2.14.2

Running : homey app driver create

? What is your Driver's Name? test
? What is your Driver's ID? test
? What is your Driver's Device Class? Sensor (sensor)
? What are your Driver's Capabilities? 
? Do you want to create a Discovery strategy to find your device automatically in the IP network? Yes
? Seems good? Yes

>> Got the error : 

The found app.json does not contain the required properties for a valid Homey app!

app.json content : 

```
{
  "_comment": "This file is generated. Please edit .homeycompose/app.json instead."
}
```

**Comment by tjallingt** [comment]
I merged a fix for this issue, will be released soon (we want to make some other minor changes and I'm planning on releasing everything toghether). Thanks for reporting!
