### ISSUE TITLE
Search in autocomplete does not work

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#191]
An autocomplete argument on a flow card has a search functionality, but this seems not to work. The autocomplete properly receives the values from the app though. Is this a bug or do we need to do something in the app to support the search?

**Comment by RobinBol** [comment]
Hi! You should be using the `query` parameter to filter the results you return from the auto complete listener here: https://github.com/MadMonkey87/Homey.InsightTrends/blob/3c2e96a75e14dd3f98c9b120d73143f46795509d/ch.philippewechsler.trends/app.js#L258

**Comment by MadMonkey87** [comment]
Ah I was missing this one, thx!
