### ISSUE TITLE
Get all devices doesnt work anymore in v6

### ISSUE THREAD

**Issue by djfanatix** [athombv/apps-sdk-issues#192]
All the apps that require a list of all devices do not work anymore in RC4 6.0.0 (Homeykit, Heimdall,..)

**Comment by RobinBol** [comment]
Hi, could you perhaps be more precise? It is quite unclear what you expect to happen, what really happens, and what part of the SDK this might be related to.

**Comment by djfanatix** [comment]
Honestly I have no idea.
I think it are all the apps that use the Homey-api to get all the installed devices.
(This app can control your full homey)

All these apps don't work anymore with v6.0.0

**Comment by djfanatix** [comment]
For some unknown reason it works again after a reboot.
( I already did a few this morning)

**Comment by djfanatix** [comment]
Can you open this issue again.
I just re-appeared.

**Comment by RobinBol** [comment]
I'm sorry but you have to be more specific than "apps don't work". I installed the HomeyKit app and when I go to Settings > HomeyKit I see a list of all my devices. I'm also running v6.0.0-rc.4 and tried this a few times. Is the problem that you don't see the list of your devices in the settings page of the HomeyKit app?

**Comment by djfanatix** [comment]
Could you also install mqtt hub, after a while I get an error (could not get devices and could not get devicelist) and suddenly homeykit, heimdall, ... don't work anymore.

I will try to make it crash today and send a diagnostics report. 

This crash didnt happen before v6z

**Comment by RobinBol** [comment]
Alright, installed mqtt hub as well, but so far can't reproduce. Any more info you could give might help us to pinpoint this (potential) issue.

**Comment by djfanatix** [comment]
I just enabled MQTT hub again and enabled the broadcast, and Homey crashed within a minute and went offline.

I am trying to send a diagnostics report (when Homey is online again after a few minutes), but even then Homey crashes.

**Comment by RobinBol** [comment]
It might be that your Homey is under very heavy load and therefore has these weird symptoms. I don't think there really is a homey-apps-sdk related problem. We have been testing with the apps you mentioned and can not reproduce so far. We'll keep an eye out, but maybe it would be better if you could contact support, they might be able to help you troubleshoot further.
