### ISSUE TITLE
[Question] When should we set a capability value

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#193]
Quick question! Let's assume I have a device that gets polled: should I call device.setCapabilityValue always or only if the value has changed?

Background: see https://github.com/MadMonkey87/HomeyCONZ/issues/48
In the homey app in the device detail we can see when the capability has been updated the last time. What is Athoms idea here? Should it reflect the last time it has been updated or the last time it has changed?
![image](https://user-images.githubusercontent.com/29612400/114576288-48ba2000-9c7b-11eb-8633-9ba571dcb9cb.png)

PS: another option would be that all apps always calls setCapabilityValue and homey itself has the logic and could handle this globally

**Comment by WeeJeWel** [comment]
Hi there! Just call `setCapabilityValue` whenever you know what the most recent value is. Our SDK handles the rest.

The `1 minute ago` is when the capability has last _changed_.

**Comment by MadMonkey87** [comment]
Thx! All clear now
