### ISSUE TITLE
Could not find a valid Homey App at '.../.homeycompose'

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#198]
When i created my Homey App last year with Homey version **2.3.5**, with homeycompose enabled, the `app.json` file was created in the root project folder outside the .homeycompose folder.

Today when i updated Homey package from **2.12.1** to **2.17.1** i can no longer publish my app because it can't find my `app.json` file in the .homeycompose folder. This has never been an issue before.

I tried every version from **2.17.1** and backwards. This issue was introduced with Homey **2.15.0**

![image](https://user-images.githubusercontent.com/25814673/115969369-eabfef00-a53c-11eb-9b05-15b77a01731c.png)

**Comment by tjallingt** [comment]
Hey, thanks for reporting.
Newer Homey compose apps all have their `app.json` file in the `.homeycompose` folder which i guess is the recommended way to structure your app. However it should be pretty simple to fix so I can do so Monday.
