### ISSUE TITLE
Trigger cards missing in "speaker_playing" capability

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#199]
I noticed that with the Chromecast app, the device does not show the trigger cards for the state (started playing, stopped, paused, next track etc). While the state in the UI is showing this.

These cards are also not listed in the "speaker_playing" capability in the apps reference.
https://developer.athom.com/docs/apps-reference

Can you add these trigger cards?

**Comment by TedTolboom** [comment]
Bumped by Emile:
> WeeJeWel  4 minutes ago
> Can you create an SDK issue? Should definitely be a default Flow card!

;-P

**Comment by tjallingt** [comment]
Thanks for reporting Ted! These cards will automatically be added in the next Homey release
