### ISSUE TITLE
Sensors (and probably more) sub capabilities (measure_***.sensor1) not assigned properly

### ISSUE THREAD

**Issue by caseda** [athombv/apps-sdk-issues#2]
When a driver has sub capabilities
(like the fibaro binary sensor (FGBS-001), which has 2 general alarms (`alarm_general.input1` / `alarm_general.input2`) and 4 temperature sensor capabilities divided by a sub part `.sensor1`
they will not receive any values.
~and as the flow cards are also missing it most likely is just not assigned properly in the new homey app.~
flow cards do show up in 2.0.0 RC2

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.3
