### ISSUE TITLE
iOS app: callback arguments Homey.confirm in app settings is wrong

### ISSUE THREAD

**Issue by aartse** [athombv/apps-sdk-issues#20]
the SDK documentation says "The callback's 2nd argument will be true when the user pressed OK.":
https://developer.athom.com/docs/apps/tutorial-App%20Settings.html

But with homey 2.0 in the ios app, the first argument of the callback is true or false, the second is undefined. The app settings simulator on https://developer.athom.com works as described in the documentation and uses the 2nd argument.

Code to check:
```
Homey.confirm('test', 'info', function(err, result) {
    Homey.alert('err: ' + typeof err);
    Homey.alert('result: ' + typeof result);
});
```

**Comment by WeeJeWel** [comment]
Thanks, this will be fixed in the next app release.
