### ISSUE TITLE
Device is registered as offline if mDNS fails

### ISSUE THREAD

**Issue by jghaanstra** [athombv/apps-sdk-issues#200]
In most of my apps I use the mDNS discovery mechanism for discovering WiFi connected devices. This works quite well but for some users using mDNS is not an option (when using seperated LAN's or misconfigured routers). For this reason I'm also allowing users to manually pair a device by entering the IP address and user credentials by hand.

This has always worked fine but recently (with firmware 6.x ?!?) users are noticing that their manually paired device is shown as unreachable in Homey. I'm not setting the device as unreachable myself from my app and the device can actually be reached from Homey using the configured IP address. But it ofcourse does not function properly when it's being set as unreachable.

Appearantly the SDK is recently started with setting the device as unreachable when the mDNS discovery is not working. This is unwanted behaviour if you ask me as it wont allow manual pairing. Or developers should at least be given the option to avoid this behaviour.

An example app where this is happening is the DoorBird app.

**Comment by tjallingt** [comment]
Sorry for the late reply.

Devices with a discovery strategy are automatically set to unavailable if they are not found. You can workaround this with a short `setTimeout` in the `onInit` of your Device class.

```js
setTimeout(() => {
  this.setAvailable().catch(this.error);
}, 1000);
```

This behaviour likely changed when your app was updated to SDK v3. In SDK v3 `setUnavailable` called after `onInit`. The reason for this change is that the Device class's "discovery methods" such as `onDiscoveryResult` needed to be called after `onInit`.

We can probably mark the device unavailable before calling `onInit` and only call `onDiscoveryResult` etc after `onInit` so I'm going to look into fixing this. Thanks for reporting.

**Comment by tjallingt** [comment]
We discussed this internally and we think the behaviour is correct, if a device with a discovery strategy cannot be found it should be set to unavailable.
In your case you can either workaround the issue with the `setTimeout` or remove the discovery strategy from the device manifest and use the discovery strategy yourself:

```js
const discoveryStrategy = this.homey.discovery.getStrategy("my_strategy");
discoveryStrategy.on("result", discoveryResult => {
  this.log("Got result:", discoveryResult);
});
discoveryStrategy.getDiscoveryResults();
```

We will update the documentation so this behaviour and the philosophy behind it are described more clearly.
