### ISSUE TITLE
[Bug][WebApp] strange autocomplete behaviour

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#205]
Hi, one of my users reported a strange problem in the homey web app (see https://github.com/MadMonkey87/Homey.InsightTrends/issues/2). When performing a search in a drop down it seems the result is not always rendered correctly. As you can see in the screenshot bellow the api call made contains a different result set than the one rendered. It also appears to be fine in the android and ios app but not the web app. As the ajax response is correct and as the rendered result is different I doubt that this is a problem in my app. Strangley the behaviour is not always reproducable thouh

![image](https://user-images.githubusercontent.com/29612400/118156294-7aa8d880-b419-11eb-9680-249c870c7c34.png)

**Comment by jeroenwienk** [comment]
Sounds like a race condition. I will look into it thank you.

**Comment by jeroenwienk** [comment]
Should be fixed.
