### ISSUE TITLE
`setInterval` not accurate enough

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#206]
In SDK3 `ManagerCron` is removed and instead we are told to use `setTimeout` and `setInterval`.

This is fine for apps which just needs to do a job approximately at the same time every interval.

For my app, [IcalCalendar](https://github.com/runely/calendar-homey), which reads calendars and needs to fire flow cards at the exact minute (0th second) when the event occurs, this is not accurate enough.

I did a small test with a SDK3 app. All it did was to log out at what time each `setInterval` call was fired every minute. After just 18 minutes the `setInterval` calls was already over a minute off from the start time.

I know this is a limitation with how `setInterval` works in Javascript but this is not accurate enough in Homey for apps which needs to do a job every minute at exactly 0th second each time.

What can we use in Homey SDK3 to ensure the same accuracy we had with `ManagerCron` in SDK2?

### This is what my app did

```javascript
async onInit() {
    this.log('SDK3Test has been initialized');

    this.homey.setInterval(() => {
      this.log(`🪵: ${new Date().toISOString()}`)
    }, 60000)
    this.log(`SDK3Test interval setup at every ${new Date().getSeconds()}th second. Lets see how it plays out..`)
  }
```

### This is the output from a 28 minute test run
```javascript
[log] 2021-05-14 07:07:46 [MyApp] SDK3Test interval setup at every 46th second. Lets see how it plays out..
[log] 2021-05-14 07:08:46 [MyApp] 🪵: 2021-05-14T07:08:46.078Z
[log] 2021-05-14 07:09:46 [MyApp] 🪵: 2021-05-14T07:09:46.131Z
[log] 2021-05-14 07:10:46 [MyApp] 🪵: 2021-05-14T07:10:46.195Z
[log] 2021-05-14 07:11:46 [MyApp] 🪵: 2021-05-14T07:11:46.291Z
[log] 2021-05-14 07:12:46 [MyApp] 🪵: 2021-05-14T07:12:46.294Z
[log] 2021-05-14 07:13:46 [MyApp] 🪵: 2021-05-14T07:13:46.382Z
[log] 2021-05-14 07:14:46 [MyApp] 🪵: 2021-05-14T07:14:46.436Z
[log] 2021-05-14 07:15:46 [MyApp] 🪵: 2021-05-14T07:15:46.498Z
[log] 2021-05-14 07:16:46 [MyApp] 🪵: 2021-05-14T07:16:46.562Z
[log] 2021-05-14 07:17:46 [MyApp] 🪵: 2021-05-14T07:17:46.562Z
[log] 2021-05-14 07:18:46 [MyApp] 🪵: 2021-05-14T07:18:46.628Z
[log] 2021-05-14 07:19:46 [MyApp] 🪵: 2021-05-14T07:19:46.729Z
[log] 2021-05-14 07:20:46 [MyApp] 🪵: 2021-05-14T07:20:46.803Z
[log] 2021-05-14 07:21:46 [MyApp] 🪵: 2021-05-14T07:21:46.867Z
[log] 2021-05-14 07:22:46 [MyApp] 🪵: 2021-05-14T07:22:46.867Z
[log] 2021-05-14 07:23:46 [MyApp] 🪵: 2021-05-14T07:23:46.969Z
[log] 2021-05-14 07:24:47 [MyApp] 🪵: 2021-05-14T07:24:47.070Z
[log] 2021-05-14 07:25:47 [MyApp] 🪵: 2021-05-14T07:25:47.171Z
[log] 2021-05-14 07:26:47 [MyApp] 🪵: 2021-05-14T07:26:47.187Z
[log] 2021-05-14 07:27:47 [MyApp] 🪵: 2021-05-14T07:27:47.193Z
[log] 2021-05-14 07:28:47 [MyApp] 🪵: 2021-05-14T07:28:47.283Z
[log] 2021-05-14 07:29:47 [MyApp] 🪵: 2021-05-14T07:29:47.331Z
[log] 2021-05-14 07:30:47 [MyApp] 🪵: 2021-05-14T07:30:47.427Z
[log] 2021-05-14 07:31:47 [MyApp] 🪵: 2021-05-14T07:31:47.529Z
[log] 2021-05-14 07:32:47 [MyApp] 🪵: 2021-05-14T07:32:47.536Z
[log] 2021-05-14 07:33:47 [MyApp] 🪵: 2021-05-14T07:33:47.571Z
[log] 2021-05-14 07:34:47 [MyApp] 🪵: 2021-05-14T07:34:47.671Z
[log] 2021-05-14 07:35:47 [MyApp] 🪵: 2021-05-14T07:35:47.763Z
```

**Comment by WeeJeWel** [comment]
Why aren't you simply using setTimeout for the next occurrence? :)

**Comment by runely** [comment]
Because `setTimeout` also suffers from the same delay and keeps drifting off.

My app has flow cards that triggers when events starts and stops. There's also flow cards that triggers a set amount of mintes/hours/days before an event starts/stops. And because of this, there's no way (that i know of) to know exactly when the next flow card should trigger, and therefore the app needs to check every minute at 0th second if there's any flow cards to trigger.

I'm struggling to see why `ManagerCron` was removed and why there's no accurate enough substitue for it

**Comment by runely** [comment]
I have found a package which handles the interval execution every minute, as accurate as possible. This seems to do the job quite nicely, but i would really much prefer that core Homey would deal with this.

https://github.com/swimclan/interval-clock

**Comment by tjallingt** [comment]
We understand. `ManagerCron` wasn't necessarily more accurate though, it just prevented the "drift" you are seeing when using `setInterval`. We removed it because it was used by few apps, had some issues and was quite complex. Especially since packages like https://github.com/node-cron/node-cron exist that allow you to do the same thing very easily in app-space.

I'm closing this issue now. If more developers indicate that some cron like functionality is needed and packages like https://github.com/node-cron/node-cron or https://github.com/swimclan/interval-clock are not sufficient we may reconsider.

**Comment by MatsAnd** [comment]
Hi, I also agree with @runely that it would be better to have this handled by Homey Core, rather than by the apps. Wouldn’t it be more efficient to have one timer running globally, than one for each app?
