### ISSUE TITLE
thermostat_mode capability option

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/apps-sdk-issues#208]
Hi there,

I have build an app for a thermostat, and I noticed back then that I could not 'overwrite' the capability options for `uiComponent`.

`driver.compose.json` (removed none relevant JSON)
```json
{
  "id": "<id>",
  "class": "thermostat",
  "capabilities": [
    "target_temperature",
    "thermostat_mode"
  ],
  "capabilitiesOptions": {
    "target_temperature": {
      "step": 0.5,
      "min": 5,
      "max": 40
    },
    "thermostat_mode": {
      "uiComponent": null
    }
  }
}
```

The UI component is still available when I checked the device.

It does work for the `target_temperature` capability.

**Use case:** The thermostat does not support modes like "heat", or "cool" so I set the mode manually via `setCapabilityValue()`. I also want users to be able to add flow cards for these modes, but I want to prevent a user from setting these modes as they are not supported by the device. So removing the capability itself wasn't really an option.

I decided that I just removed the capability, but is this intended behavior?
Which `capabilityOptions` can be overwritten?

-- Edwin

**Comment by tjallingt** [comment]
Yea I think this is intended behaviour, you cannot disable the ui component for any of the built in capabilities.

If your thermostat doesn't support "heating" or "cooling" modes you should not add the `thermostat_mode` capability.
For the Flow cards it is probably best that you define your own Flow cards.

If your device has modes other than heating or cooling and you want to allow users to change these from the Homey Interface it is probably best to create a custom "enum" capability https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities
