### ISSUE TITLE
Use asterisks to highlight variable words not working

### ISSUE THREAD

**Issue by Xelium** [athombv/apps-sdk-issues#210]
> A short message describing the notification. Use asterisks to highlight variable words.
[https://apps-sdk-v3.developer.homey.app/ManagerNotifications.html](url)

![1](https://user-images.githubusercontent.com/6226403/120413527-bf5ccb00-c358-11eb-879c-37159462872a.png)
![2](https://user-images.githubusercontent.com/6226403/120413533-c1bf2500-c358-11eb-95dc-ebe5d8a7b7df.png)

**Comment by RobinBol** [comment]
Hi @Xelium , if I'm not mistaken you have to use double asterisks. Please let me know if that works for you and I'll update the documentation accordingly.

**Comment by Xelium** [comment]
Using double asterisks works. It makes the variable words bold in the timeline of the Homey app. In the actual notification on your phone it does nothing though.

**Comment by RobinBol** [comment]
Alright, thanks for getting back to me. I am not sure, but I don't think we can do bold in mobile app notifications.

I'll update the documentation to reflect this! Thanks for reporting.

**Comment by Xelium** [comment]
> Alright, thanks for getting back to me. I am not sure, but I don't think we can do bold in mobile app notifications.
> 
> I'll update the documentation to reflect this! Thanks for reporting.

It is possible with HTML styled notifications on Android and IOS:

https://help.pushwoosh.com/hc/en-us/articles/360000347463-Bold-italic-coloured-notification-text-for-iOS-and-Android

**Comment by frodeheg** [comment]
The documentation at https://apps-sdk-v3.developer.homey.app/ManagerNotifications.html still does not indicate that double asterisks should be used. it says:
> "A short message describing the notification. Use asterisks to highlight variable words."

It would probably be a good idea to update the documentation.

**Comment by RobinBol** [comment]
> The documentation at https://apps-sdk-v3.developer.homey.app/ManagerNotifications.html still does not indicate that double asterisks should be used. it says:
> 
> > "A short message describing the notification. Use asterisks to highlight variable words."
> 
> It would probably be a good idea to update the documentation.

Ah, the asteriks needed to be escaped I see, fix will be deployed shortly! Thanks.
