### ISSUE TITLE
Update icons for custom capability with ternary uiComponent

### ISSUE THREAD

**Issue by lovaere** [athombv/apps-sdk-issues#213]
When defining a custom capability, you are able to select the uiComponent of your choice. When selecting the **ternary** uiComponent then the icons are no longer shown in the UI:

![file](https://user-images.githubusercontent.com/46051301/121319853-e729d100-c90c-11eb-83dc-20c4b9b53398.jpeg)

Here is a sample of the capability definition:

```
{
    "type": "enum",
    "title": {
      "en": "Test Action"
    },
    "getable": false,
    "setable": true,
    "uiComponent": "ternary",
    "values": [
      {
        "id": "Up",
        "title": {
          "en": "Up"
        }
      },
      {
        "id": "Stop",
        "title": {
          "en": "Stop"
        }
      },
      {
        "id": "Down",
        "title": {
          "en": "Down"
        }
      }
    ]
  }
```
How can we pass the icons of the buttons?

**Comment by RobinBol** [comment]
Hi! Could you mention which version of the Homey mobile app you are using when you see this issue?

**Comment by RobinBol** [comment]
You can probably already fix this yourself by using `up`/`idle`/`down` as value id's.

**Comment by lovaere** [comment]
> Hi! Could you mention which version of the Homey mobile app you are using when you see this issue?

I'm using app version 6.7.1.732 with Homey version 6.1.0

**Comment by lovaere** [comment]
> You can probably already fix this yourself by using `up`/`idle`/`down` as value id's.

That's indeed a working fix. Thanks for your quick reply!
