### ISSUE TITLE
App trigger cards with a device argument

### ISSUE THREAD

**Issue by AdyRock** [athombv/apps-sdk-issues#217]
Maybe I'm being lazy but with 44 drivers and growing I didn't want to add a trigger to every device so I added an app global trigger as follows:

```
"flow": {
    "triggers": [
	{
		"id": "command_complete",
		"title": {
			"en": "A command completed"
		},
		"titleFormatted": {
			"en": "A command completed on device [[device]]"
		},
		"tokens": [
			{
				"name": "state",
				"type": "boolean",
				"title": {
					"en": "Successful"
				},
				"example": "true"
			},
			{
				"name": "name",
				"type": "string",
				"title": {
					"en": "Command Name"
				}
			}
		],
		"args": [
			{
				"name": "device",
				"type": "device"
			}
		]
	}
}

```
```
this.commandCompleteTrigger = new Homey.FlowCardTrigger('command_complete');
this.commandCompleteTrigger
	.registerRunListener(async (args, state) =>
	{
		return (args.device.getAppId() === state.device.appId);
	})
	.register();
```

`Homey.app.triggerCommandComplete(this, this.executionCmd, (element.newState === 'COMPLETED'));`

```
    // Trigger command complete
    triggerCommandComplete(device, commandName, success)
    {
        // trigger the card
        let tokens = { 'state': success, 'name': commandName };
        let state = { 'device': device };

        this.commandCompleteTrigger.trigger(tokens, state)
            .then(this.log)
            .catch(this.error);
    }
```

But the state.device is the device.appId and not an device object so I had to use the undocumented device.getAppId() to match the device.
This works perfectly but I don't like to use undocumented functions.

**Comment by tjallingt** [comment]
The fact that you are getting an `appId` in the `registerRunListener()` `state` argument is an issue. We probably won't change it but it's a bad idea to rely on a device instance turning into an object with the `appId`.

I'd recommend using a `"filter": "driverId=driver1&driver2&..."` for the device argument of your Flow card and `FlowCardTriggerDevice` in your app code. Unfortunately adding a filter like that will break existing Flows using the Flow card. So then you should probably deprecate the existing Flow card and create a new one with the filter.

An alternative solution is to put the driver id and device data into the trigger state and match these in the `registerRunListener` but I wouldn't recommend it over using a `FlowCardTriggerDevice`.

**Comment by tjallingt** [comment]
I'm going to close this but its fine to continue the conversation about the pros and cons of using a `FlowCardTriggerDevice` or a `FlowCardTrigger` here (or on Slack).

**Comment by AdyRock** [comment]
I have implemented your suggestion. But I think the "filter": "driverId=driver1&driver2&..." should be "filter": "driverId=driver1|driver2|..."
When I use the Ampersand the cards don't appear. It is a mighty long string of devices though so I hope there is no limit ;-)

**Comment by tjallingt** [comment]
Oh whoops yea you're right the `|` is used as an "or". You'll probably run into other limits before the length of the filter starts becoming an issue ;p
