### ISSUE TITLE
What does chartType do?

### ISSUE THREAD

**Issue by escabe** [athombv/apps-sdk-issues#219]
If we look at the built-in device capabilities:

https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html

For some:
` "chartType": "stepLine"`

or:

` "chartType": "spline"`

is set. This option isn't mentioned anywhere in the docs, I guess I'd have expected to see it in the custom capabilities section:

https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities

What does this do exactly? Which options are there? What is the default if I do not set it for my custom capability?

**Comment by WeeJeWel** [comment]
This is legacy from Homey v1.x and isn't used anymore :)
