### ISSUE TITLE
Full screen area can not be utilized in app settings

### ISSUE THREAD

**Issue by daneedk** [athombv/apps-sdk-issues#22]
Please give an app developer access to the full screen width and height. It's difficult as it is to fit all in and not having access to all available pixels just makes it harder and isn't really giving a user the best possible experience.

![image](https://user-images.githubusercontent.com/16610696/50513413-f481d680-0a97-11e9-9b09-9d4254f4be21.png)

**Comment by WeeJeWel** [comment]
Sorry, but we won't allow this. It's essential that the style is consistent throughout the app, which also means the same background color everywhere.

I understand that you would like to use the entire space but we have to be very strict in maintaining a consistent UI.

**Comment by daneedk** [comment]
I agree with you for 100% that users should get a consistent UI, but enforcing it in this way is nonsense. I truly can not understand how not giving us the full screen area is a way to achieve your goal.
You have an approval process for apps, you can enforce consistency there. You could give app developers some guidance on how you want it to look but you don't, you are limiting us in providing a best possible User Interface and User Experience, this to me feels like the community and me have been given the finger once again.

**Comment by SailingDuck** [comment]
Style is not consistent because the settings of the rest of the app can utilize that area, these pages also use a different background color for headers. I don't see why other developers can't do that. 

Next to that there's the gradient for the most of the pages, white background for the settings and black for the apps.
