### ISSUE TITLE
Homey update broke my app/Wrong app validation

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#222]
This is the follow up of https://github.com/athombv/homey-apps-sdk-issues/issues/221 because @tjallingt closed the original ticket too early.

Thx for the explanation @tjallingt but this issue is still not okay. If the error is still there in sdk v3 and if there is still no proper migration path then this is no solution as it will never be possible to upgrade the app to sdk v3 and higher (which is already in work).

So what is the plan?

**Comment by tjallingt** [comment]
Sorry the issue was closed too early. IMO its fine to continue the conversation in a closed issue or ask to re-open it if you feel that is necessary.

Its completely fine to keep your app on SDK v2, there are no plans for deprecating SDK v2 anytime soon.
If you do want to update to SDK v3 I think the we can unlist the SDK v2 version of your app from the app store and you publish a new SDK v3 version of your app. That way it doesn't need to be backwards compatible.

Would that be a solution for you? Do you have a suggestion that would solve this (without allowing duplicate Flow card ids)?

**Comment by MadMonkey87** [comment]
Doesn't matter if sdk v2 gets some long time support, at any time there will be a problem with sticking to sdk v2 and I won't develop and support two versions of the app. The ultimate result of this is that my users will need to rebuild their flows sooner or later.

If adapting the validation is so much rocket science and cannot be questioned why don't you at least offer upgrading the existing flow cards, i.e. allow renaiming?

No matter how you turn it, Athom made a decision without thinking this trough and now you have the mess. I won't be the one cleaning up, it is just easier for me to abandon the platform.

**Comment by MadMonkey87** [comment]
Any update on this?

**Comment by MadMonkey87** [comment]
I just got this message from a reviewer of an app update:
`
Thank you for submitting your app deCONZ for review.

It looks great, so we have gone ahead and approved your submission.

Just a quick reminder your app still supports SDK v2 this version has been deprecated for some time. We recommend updating your app to the latest version SDK v3. 
More information on this topic can be found here: 
https://apps.developer.homey.app/upgrade-guides/upgrading-to-sdk-v3`

So it is either not true what the reviewer states or it is not true what @tjallingt mentioned. 
@WeeJeWel please clarify on this issue or I have no other option than to leave homey forever...

**Comment by WeeJeWel** [comment]
Homey Apps SDK v2 has already been deprecated for a long time.
That doesn't mean it stops working :) It just isn't allowed for _new_ apps to use, but existing apps can still update. We're just nudging developers to upgrade to Apps SDK v3, because it's the current stable version.

**Comment by MadMonkey87** [comment]
okay but this is still not the answer I need because as mentioned here and in here https://github.com/athombv/homey-apps-sdk-issues/issues/221 I will never be able to upgrade. And this is due to athoms stupid decisions and lazyness that got you in trouble which you are unwilling to resolve. Is this right?

**Comment by WeeJeWel** [comment]
Please be kind and keep it friendly.

For now you can keep your app on Apps SDK v2.

**Comment by MadMonkey87** [comment]
I don't have any reason to stay friendly, this is by far not the first time athom messed things up. I am out, thx for nothing

**Comment by WeeJeWel** [comment]
Okay, thanks for all your efforts!
