### ISSUE TITLE
AppStore shows flowcards for devices which should be ruled out by the filters in the manifest

### ISSUE THREAD

**Issue by Shakesbeard** [athombv/apps-sdk-issues#223]
Example:
Looking at LIFX (LAN) v1.5.1 you can see the LIFX BEAM device showing the morph effect flowcard (id: activate_tile_morph).
The flowcard has a device filter as follows: "filter": "driver_id=lifxv2|lifxv2_a19|lifxv2_a19|lifxv2_a19nv|lifxv2_br30|lifxv2_br30nv|lifxv2_br30nv|lifxv2_beam|lifxv2_candle|lifxv2_candleww|lifxv2_hev|lifxv2_hue|lifxv2_hue_1000|lifxv2_hue_1000_br30|lifxv2_hue_650|lifxv2_dl|lifxv2_dlww|lifxv2_fa|lifxv2_fc|lifxv2_gu10|lifxv2_hue_mini|lifxv2_w_mini|lifxv2_ww_mini|lifxv2_ww_mini|lifxv2_ww_mini|lifxv2_original|lifxv2_switch|lifxv2_tile|lifxv2_800_w_hv|lifxv2_800_w_lv|lifxv2_900_w_br30_hv|lifxv2_900_w_br30_lv|lifxv2_z&capabilities=chain_device|matrix_device"

The LIFX BEAM has neither of the mentioned capabilities, yet the card is shown for that device.

**Comment by tjallingt** [comment]
Hey thanks for reporting, we'll take a look 👍

**Comment by WeeJeWel** [comment]
This is actually intended behavior. Because capabilities often change during pairing, the App Store shows all possible Flow cards — you could call it optimistic.

If you don't want this, remove the LIFX Beam's driver ID from the `driver_id` filter.
