### ISSUE TITLE
Update 7.1.4 fails, takes Homey down

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#226]
As the support wont answer I am posting this here. I've tried to update from 7.1.3 to 7.1.4 which seems to fail or at least the verdion is still at 7.1.3 after the update.
The bigger problem however is that homey won't boot properly anymore. All apps are in a suspended state and won't come back even after waiting for hours. Also deactivating and reactivating or restarting apps does not work. Sometimes there is an error (ENOMEM = no memory) although there seems to be enough memory. As everything worked just fine before the update I can only assume that 7.1.4 is faulty or broke my homey. What should I do?

![Screenshot_20211002-195829_Homey](https://user-images.githubusercontent.com/29612400/135727955-443d07e4-b627-4a41-a9bf-4cf32de76f28.png)
![Screenshot_20211002-200002_Homey](https://user-images.githubusercontent.com/29612400/135727956-7e41c47b-089d-425e-853b-8dc7d5c4b82e.png)
![Screenshot_20211002-195807_Homey](https://user-images.githubusercontent.com/29612400/135727957-cdf78d45-f397-4878-80e3-1ad4ef1ee2d3.png)
![Screenshot_20211002-195754_Homey](https://user-images.githubusercontent.com/29612400/135727959-908685a4-af05-4ab0-b9ae-33c659b9566c.png)

**Comment by WeeJeWel** [comment]
Hi, try updating Homey from setup mode. Looks like you have an app that's claiming a lot of memory.
