### ISSUE TITLE
`Pruning dev dependencies` doesn't work on node `16.10.0`

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#227]
When i have node `16.10.0` installed `homey app install` fails to prune dev dependencies.

When i revert to node `14.11.0` `homey app install` successfully prunes dev dependencies.

![image](https://user-images.githubusercontent.com/25814673/136292148-9137332d-4b7a-4214-b1bf-aa1e00d31a53.png)

**Comment by tjallingt** [comment]
Thanks for reporting!

Thats pretty strange, the CLI uses its own copy of NPM 12 just so pruning works independently of the Node or NPM version you have installed. Please make sure you have the latest version of the Homey CLI. I have already made some changes that will hopefully make this step of building a Homey app more robust but those haven't been released yet.

 I'll look into whether I can reproduce and fix this.

**Comment by runely** [comment]
Sorry.. I had homey `2.7.0` installed after some testing a while ago with where my `app.json` file was located..

Updated to `2.22.6`, and pruning works on node `16`
