### ISSUE TITLE
App validation argument errors (verified)

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/apps-sdk-issues#228]
Hi there,

When I run the validation on the command line with `--level verified`, I get these errors when I use arguments in the trigger card.

```
✓ Validating app...
✖ Homey App did not validate against level `verified`:
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'].type should be equal to one of the allowed values ["device"]
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'] should have required property 'filter' 
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'] should have required property 'title' 
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'].type should be equal to one of the allowed values ["text","autocomplete","device","date","time","color"]
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'] should have required property 'title' 
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'].type should be equal to one of the allowed values ["number","range"]
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'] should have required property 'title' 
manifest.flow.triggers['operating_mode_changed'].args['operating_mode'] should match some schema in anyOf
```

It does compile correctly. I am using Homey Compose.
You can try it out with the Plugwise app. These builds _should_ fail too.

It looks like it is having trouble with the extra arguments (`args`), as it must merge with the `type=device` argument.

My trigger flow is located in `./.homeycompose/drivers/flow/triggers/operating_mode_changed.json`.
I added this flow in `drivers/<driver>/driver.flow.compose.json`.

When I run the validate command with level publish, it doesn't show these errors.

Is this a known issue, or is the validation plain wrong right now?

<details>
  <summary>operating_mode_changed.json (shortened)</summary>
  
```json
{
  "title": {
    "en": "Operating mode has changed"
  },
  "titleFormatted": {
    "en": "Operating mode has changed to [[operating_mode]]"
  },
  "args": [
    {
      "type": "dropdown",
      "name": "operating_mode",
      "values": [
        {
          "id": "program",
          "label": {
            "en": "Program"
          }
        },
        {
          "id": "boost",
          "label": {
            "en": "Boost"
          }
        },
        {
          "id": "constant",
          "label": {
            "en": "Constant"
          }
        }
      ]
    }
  ]
}

```
</details>

<details>
  <summary>driver.flow.compose.json (shortened)</summary>
  
```json
{
  "triggers": [
    {
      "$extends": "operating_mode_changed"
    }
  ]
}
```
</details>

**Comment by WeeJeWel** [comment]
Try adding `title` to every `args.operating_mode`. Quite odd, but should resolve your issue.

**Comment by tjallingt** [comment]
Yea these errors are a limitation of the way the validation works, it tries to suggest every possible option instead of telling you what the most likely fix is. Something we really want to fix but that is unfortunately would take a lot of work to resolve.

I'm closing this now because I'm assuming you can fix this by adding the `title` to the Flow card argument. If that is not the case or you run into another issue feel free to respond to the closed issue or create a new one :)
