### ISSUE TITLE
homey v2.23.0 and up creates a build directory

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#229]
Starting with **homey v2.23.0**, including the latest **homey v2.23.3**, `homey app build` creates a `build` folder in the app root folder containing a copy of the app...

This makes git flag that there’s a lot of new uncommited files...

Is this a bug? If not, how to turn this off?

**Comment by tjallingt** [comment]
Its not a bug, it actually fixes some behaviors and allows you to easily inspect what files are being published as part of your app.

You can add `build/` to a `.gitignore` file to prevent the build folder from being added to git. https://www.atlassian.com/git/tutorials/saving-changes/gitignore
