### ISSUE TITLE
Homey App Run not working

### ISSUE THREAD

**Issue by Marinosbitter** [athombv/apps-sdk-issues#230]
Hi,

When I run `Homey App Run` it fails with the folowing error:

✓ Pre-processing app...
Command failed: node C:\Users\marij\AppData\Roaming\npm\node_modules\homey\node_modules\npm\lib\npm.js ls --parseable --all --only=prod
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! missing: source-map@0.7.3, required by nl.marinosbitter.test@1.0.0
npm ERR! missing: source-map-support@0.5.20, required by nl.marinosbitter.test@1.0.0
npm ERR! missing: buffer-from@1.1.2, required by source-map-support@0.5.20
npm ERR! missing: source-map@0.6.1, required by source-map-support@0.5.20

This happens on a newly generated homey app
Node: On both 14.18.1 and 17.0.1
Npm: 8.1.1
Homey: 2.23.3

**Comment by tjallingt** [comment]
Yea sorry, due to previous incompatibilities with npm 7 the Homey CLI uses npm 6 internally. It seems some incompatibility with npm 8 causes version 6 to stop working as expected.

For now you can install npm 6 by running

`npm install --global npm@6`

We'll look into a better fix soon

**Comment by Marinosbitter** [comment]
Yes that worked, I needed to re-create the app though. So the problems seems to be with creating ( `homey app create`) the app with newer npm versions, not just running them.

Maybe it's an idea to add the npm@6 requirement to the [developer documentation](https://apps.developer.homey.app/the-basics/getting-started) so new developers won't run into the same issue.

Anyway thanks for the help :)

**Comment by tjallingt** [comment]
Good to hear that fixed your issue. We don't want to be dependent on any particular version of NPM so if this can be fixed that would be ideal. Otherwise we should definitely add this to the documentation.

**Comment by Marinosbitter** [comment]
One last FYI for other people who might run into the same issue. You don't need to reinstall the homey app as mentioned above, only reinstall the npm modules again. after you've switched to npm 6.
So to fix:
1. Run `npm install --global npm@6`
2. Run `npm install`
