### ISSUE TITLE
Cannot add some Z-Wave devices via S2 

### ISSUE THREAD

**Issue by maginawin** [athombv/apps-sdk-issues#231]
After Homey was updated to v7, some of my Z-Wave devices could not be successfully added to Homey.

Homey’s pairing process lasts approximately 15 seconds, and then Homey determines that the Z-Wave pairing timed out and aborts the pairing process. In fact my Z-Wave device takes about 45 seconds to response the Z-Wave Security Key (S2).

Many users have purchased this device which works on Homey v6, but it cannot use on Homey 7. I cannot help them. What should I do next? Can Homey extend the pairing time of the Z-Wave device to more than 45 seconds, such about 1 minute?

**Comment by tjallingt** [comment]
Hey, thanks for reporting this issue.

Yea we can increase the timeout duration :)
What device is it? Also do you know what particular message homey is waiting for (I'm assuming `KEX_SET`)?
If you have a diagnostic report of this happening that would be very helpful. You can make a diagnostic report in the mobile app by going to: More > Settings > General > Create Diagnostic report.

**Comment by maginawin** [comment]
Hi @tjallingt ,

I'm glad to receive your message, thanks for your detailed guidance.

I'll provide you the Log and Diagnostic Report next week because the device isn't here yet.

**Comment by maginawin** [comment]
Hi @tjallingt ,

I uploaded Log when I failed to add a Z-Wave device.
[pairing_log.txt](https://github.com/athombv/homey-apps-sdk-issues/files/7450204/pairing_log.txt)

The diagnostic report is 84B10A

**Comment by tjallingt** [comment]
Thanks for sharing, that report is not what I was expecting. It seems there is actually a "no ack" error.
That error is actually coming from our Z-Wave chip... I don't understand why the device in question won't send an acknowledgement. It does seem to send more messages at a later point though, going to look into this some more but it unfortunately doesn't appear to be as easy of a fix as I presumed.

**Comment by maginawin** [comment]
Hi @tjallingt ,

What else can I do to solve this problem?

This device works on Homey V5 or V6.

**Comment by tjallingt** [comment]
Yea I guess it works on pre-v7 because those versions didn't support S2.
 I'll look into the Z-Wave specification to see what Homey should be doing in this case.
 
 What is the device in question? Maybe we can buy one to test with.
 And are you the developer of the Homey app? We could choose to disable S2 for this device in the meantime.

**Comment by maginawin** [comment]
Hi @tjallingt ,

It is Namron's 4512717 - Z-Wave Plug, it seems that they are out of stock now. If you really need it, I can get it from the manufacturer.

Yes, I'm a Homey App developer, and I'm working on the Namron App. Please help us disable S2 for this device so that users can use it properly first.

**Comment by tjallingt** [comment]
To disable S2 please remove `requireSecure` and/or `includeSecure` from the `zwave` property in your drivers manifest (if you are using them).
You can then add `"security": ["none", "S0"],` to indicate that your app can control the device both unsecured and using S0 security.

When I fix this issue, it'd be great if you can test the fix and update your app to support S2 again by updating it to  `"security": ["none", "S0", "S2"],` :)

**Comment by maginawin** [comment]
Should I add `"security": ["none", "S0"]` in `app.json` or `driver.compose.json`? Will this affect users who have already added other devices as S2?

**Comment by tjallingt** [comment]
it goes in the `driver.compose.json` file under the `"zwave"` property. Same place as the `requireSecure` would be (but replacing it) https://apps.developer.homey.app/wireless/z-wave#require-secure-communication

This property will be documented soon, it was not documented to ensure issue like this would be reported :)

**Comment by maginawin** [comment]
It's awesome, the device is now working properly. Thank you very much! @tjallingt :)
