### ISSUE TITLE
Typescript compilation failed

### ISSUE THREAD

**Issue by sekarmaeu** [athombv/apps-sdk-issues#233]
Hi!
I posted this in the Homey community and was adviced to post it here instead.
I followed a tutorial on youtube ([App creation tutorial 1](https://apps.developer.homey.app/the-basics/getting-started)) on how to create your own app. The only thing I have done differently was selecting typescript when creating the app. Now, when I’m trying to run the app it fails saying

✓ Pre-processing app…
✓ Typescript detected. Compiling…
× Error occurred during while running tsc

Typescript compilation failed.

What have I done wrong?

![Homey](https://user-images.githubusercontent.com/93839901/140621219-edb3be2b-32ba-46d1-b107-131b0f117501.png)

I was also adviced to run ` npm run build`

This is the result
![Homey1](https://user-images.githubusercontent.com/93839901/140621246-edee9319-e649-4a86-80da-21265aa9efea.png)

Since I'm a beginner I really could need some help. :)

**Comment by RobinBol** [comment]
Looks like there is something in your code that makes Typescript unable to compile. But the error message is not very helpful. Could you run `npx tsc` in your app dir and post the output?

**Comment by sekarmaeu** [comment]
![Homey2](https://user-images.githubusercontent.com/93839901/140647649-59755408-6228-4e43-b8cf-540693aa61f8.png)

This is what I get, nothing?! I haven't changed anything in the code from the tutorial (at least that I know of). In the tutorial, Typescript is not selected, could that be a problem?

**Comment by tjallingt** [comment]
What are your NPM, Node, TypeScript and Homey CLI versions?

- `npm --version`
- `node --version`
- `npm ls typescript`
- `homey --version`

What happens if you run `npx typescript` outside of your app folder? It should print a list of usage instructions.
And what does it print if you run `echo %ErrorLevel%` after running `npx typescript` _inside_ your app folder?

**Comment by sekarmaeu** [comment]
Hello! :)
See below screenshots.

`npm --version`
![Homey3](https://user-images.githubusercontent.com/93839901/140780872-c4a272fa-a0c4-44ce-b034-09ae7e737824.png)

`node --version`
![Homey4](https://user-images.githubusercontent.com/93839901/140781045-3cd08a0b-700b-4942-be00-39e9566f7998.png)

`npm ls typescript`
![Homey5](https://user-images.githubusercontent.com/93839901/140781123-8e3878d6-00e5-4491-a84a-ce33386697dd.png)

`homey --version`
![Homey6](https://user-images.githubusercontent.com/93839901/140781202-a23c10c7-0efe-41e6-b598-e5d60b171b43.png)

`npx typescript` (Outside)
![Homey6_5](https://user-images.githubusercontent.com/93839901/140781327-5944480b-3b48-409c-b93b-4226fceb300a.png)

`npx typescript` (Inside) + `echo %ErrorLevel%`
![Homey7](https://user-images.githubusercontent.com/93839901/140781491-bb78bd31-eca3-41e3-9df2-2b5d1f1ca7a4.png)

I attach the error logs as well.

[2021-11-08T16_30_09_966Z-debug.log](https://github.com/athombv/homey-apps-sdk-issues/files/7498590/2021-11-08T16_30_09_966Z-debug.log)
[2021-11-08T16_30_33_510Z-debug.log](https://github.com/athombv/homey-apps-sdk-issues/files/7498591/2021-11-08T16_30_33_510Z-debug.log)

**Comment by tjallingt** [comment]
Thanks for all the information, that was very helpful!

This issue should be fixed in version `2.23.5` of the Homey CLI, you can install it by running `npm install --global homey@latest`.

**Comment by sekarmaeu** [comment]
No, I thank YOU!! 😀
Your instructions helped me solve the problem!
Thanks again!
