### ISSUE TITLE
Unhandled \r\n in homey 2.23.6 (NpmCommands.js)

### ISSUE THREAD

**Issue by h3rman** [athombv/apps-sdk-issues#234]
Installed Windows 11 yesterday and couldn't run my homey app anymore. I don't know if this is because the os switch or if I got another version of some dependency but nonetheless `getProductionDependencies()` should handle this.

The output of `npm ls --parseable --all --only=prod` now has `\r\n` on all lines but the last that only has `\n`. On my Windows 10 machine all rows has `\n`

To fix this for myself I added a row that replaces all `\r\n` with `\n`.
`stdout.replace(/\r\n/g, '\n')` (in homey\lib\NpmCommands.js)

```
@@ -47,7 +47,8 @@ class NpmCommands {
     // This means we can end up with "extra" packages that are still present in node_modules but not
     // listed in package.json or package-lock.json.
     // The --package-lock-only flag prevents this but then it will throw when there is no lock file.
-    const { stdout } = await exec('npm ls --parseable --all --only=prod', { cwd: appPath });
+    var { stdout } = await exec('npm ls --parseable --all --only=prod', { cwd: appPath });
+       stdout = stdout.replace(/\r\n/g, '\n')

     return stdout
       .split('\n')
```

**Comment by tjallingt** [comment]
Thanks for reporting this, curious that it was changed for win 11.

**Comment by tjallingt** [comment]
Should be fixed in the next Homey CLI release 👍
