### ISSUE TITLE
Generate diag. report for app fails with 413

### ISSUE THREAD

**Issue by Shakesbeard** [athombv/apps-sdk-issues#237]
One of my users has reported that when trying to create a diagnostic report them received an error: 413 request entity too large when I try to create the report

**Comment by tjallingt** [comment]
Thanks for reporting. It surprises me that a diagnostic could become large enough to run into this issue, I wonder how much data it contains... We'll look at what we can do to either prevent diagnostics that are too large or to allow uploads of larger diagnostics.
