### ISSUE TITLE
BLE - Filtering and discovering does not work

### ISSUE THREAD

**Issue by jenzoa** [athombv/apps-sdk-issues#241]
When filtering for manufacturer ID and discovering service UUID's does not work.

When filtering for Secuyou manufacturer ID no devices are discovered. Here is the code:

     .filter(advertisement => advertisement.manufacturerData[0] == 0xD4 && advertisement.manufacturerData[1] == 0x02) // 02D4

Also when trying to discovering devices with a specific UUID no devices are discovered. Here is the code snippet:

      const advertisements = await this.homey.ble.discover([this.DISCOVERY_SERVICE_UUID()]).catch(this.error);

We have experienced that devices are found with filtering and service UUID specific discovery, but only once. If you try to repeat the process then no devices are discovered.

The current HOMEY app is discovering all BLE devices in proximity, but that is incovinient for the user.

**Comment by mrlukasbos** [comment]
What are the values when you `console.log` advertisement.manufacturerData? And what value would you expect instead?

For the discovery; it only shows results of devices that are not connected; do you happen to connect to a device? That would cause the discovery to not return your device the second time.

**Comment by jenzoa** [comment]
The values from the advertisement.manufacturerData are correct.

We have done some testing and the problem is that the device is still connected as you allude to. 

We try to disconnect in case of a failure in pairing procedure in order for the user to retry. So the problem must therefore be the function ‘disconnect’.

**Comment by mrlukasbos** [comment]
OK. You could simply store the advertisement in the variable and use it to reconnect. 

However, If I understand you correctly it appears that the `BlePeripheral#disconnect()` method does not behave as you expect? Does the method resolve or reject with a timeout, or does something else happen? 


Please note that there is a known issue where "BlePeripheral.isConnected()" does not show a correct value. A fix for that will be available soon.

**Comment by jenzoa** [comment]
Hi Lukas,

Yes, problem is that BlePeripheral#disconnect() does not work.

the log says the following:

[log] [Homey:61811aecf9159a0bab4e1046] [ManagerDrivers] [Driver:v22] [Device:c50e028e-a4e5-4b4d-9bca-06073ff80331] Could not disconnect when deleting device

It appears directly after deleting the device. So no time-out.

Ok, I will built in storing of the device.

Best regards
Jens



> Den 13. dec. 2021 kl. 11.37 skrev Lukas Bos ***@***.***>:
> 
> ertisement in the variable and use it to reconnect.

**Comment by mrlukasbos** [comment]
That log is not from Homey but a log in your app. Would you mind sharing a code snippet? 

If `BlePeripheral#disconnect()` resolves then the device is disconnected successfully; however it should then reappear in the discovery results (Note: those results could be cached up to 60s so it may take a while for the device to reappear)

If `BlePeripheral#disconnect()` rejects then we could not disconnect from the device for some reason; or a timeout has occured.

**Comment by jenzoa** [comment]
Here is a code-snippet

async onDeleted() {
    this.log('Secuyou Lock has been deleted');
    try {
      await this.peripheral.disconnect();
    
      // Reset the lock state and app state
      lockState = stateDevice.KEY_GENERATION;
      appState = stateApp.INITIAL;
    } catch (error) {
      this.log ('Could not disconnect when deleting device')
    }
  }

**Comment by mrlukasbos** [comment]
What is the message if you add `this.log(error)` to the `catch` block?

**Comment by jenzoa** [comment]
That is very strange. No error is printed out. 

Why?

**Comment by mrlukasbos** [comment]
That is very strange indeed. I have checked our codebase for empty error messages that could be thrown, however, I did not find any. But, the `error` object should contain at least something. What value are you logging? You could maybe try attaching a debugger or something similar.

Something else: I notice that `lockState` and `appState` are defined as global variables. I highly recommend not using global variables since those will cause problems with your app on Homey Cloud.

**Comment by jenzoa** [comment]
Going back to the original problem of filtering manufacturerData. 
The reason for failing filtering is that:

advertisement.manufacturerData[0]

results in nothing. Meaning the I cannot read the first value in the buffer. 
I can read out the buffer just fine - and the data I am searching for is present. 
But why is it not possible to read out the first value in the buffer?

**Comment by mrlukasbos** [comment]
So to clarify: 

```
// This returns something, probably "<Buffer xx xx xx xx>"
console.log(advertisement.manufacturerData); 

// This then returns nothing?
console.log(advertisement.manufacturerData[0]); 
```
If this is the case it does not look like a bug in our SDK. 

`advertisement.manufacturerData` is a Buffer, not an array, so reading by index (using `[0]`) is tricky. When you try to read data from a buffer you have to specify how the data will be interpreted. This depends on your manufacturer data. You probably want something like [`Buffer.readInt16()` ](https://nodejs.org/api/buffer.html#bufreadint16beoffset ).

What are the contents of the buffer when running `console.log(advertisement.manufacturerData);`?

**Comment by jenzoa** [comment]
Yes, you are correct. Just read about buffers from https://nodejs.org/en/knowledge/advanced/buffers/how-to-use-buffers/ <https://nodejs.org/en/knowledge/advanced/buffers/how-to-use-buffers/> 

The content of a buffer is for example: <Buffer 4c 00 09 06 03 e9 c0 a8 00 22 0a 01 00>

We will try with Buffer.readInt16()

**Comment by mrlukasbos** [comment]
Okay, I think all your questions have been answered. Good luck with further development of your app.
