### ISSUE TITLE
BLE - Disconnected from Homey. Reason: ping timeout

### ISSUE THREAD

**Issue by jenzoa** [athombv/apps-sdk-issues#242]
If there is no communication or action (between Homey and device) then the Homey (Pro and Bridge) disconnects. 

Do we need to keep the connection live by sending some random communication to the Homey?

**Comment by mrlukasbos** [comment]
What does Homey disconnect from? your BLE peripheral or your app session?

Ping timeouts are usually not BLE related. Does the issue occur when you run your app in the Homey CLI? (`homey app run`)

For BLE you won't need to keep the connection live; when you connect the connection will stay open until you or your BLE peripheral explicitly close it.

**Comment by jenzoa** [comment]
It disconnects from the app session.

It occurs when running the app from Homey CLI.

Okay, so keeping the connection is straight forward. 

Thank you for the quick answer.
