### ISSUE TITLE
Typescript declaration incorrect for FlowCard.d.ts ArgumentAutoCompleteCallback and ArgumentAutocompleteResults

### ISSUE THREAD

**Issue by StefanIndustries** [athombv/apps-sdk-issues#247]
Hi,

ArgumentAutocompleteCallback doesnt expect an array type of ArgumentAutocompleteResults based on type declaration. If no array is provided in the callback the homey autocomplete list doesnt function.

![image](https://user-images.githubusercontent.com/46961126/160269031-72809862-0bf7-49ad-ac8f-f533867c8259.png)

The above does compile but doesnt function, while the following in JS is the only way to get autocomplete functioning (also based on SDK3 docs):
![image](https://user-images.githubusercontent.com/46961126/160268970-c6e85750-7294-44a6-be0d-60dda6080300.png)

Trying to encapsulate the result in an array in TS results in the following compilation error:
![image](https://user-images.githubusercontent.com/46961126/160269097-f47e4cc2-df84-4d79-bb3d-b412b65cceac.png)

Besides the array problem the following also occurs:
ArgumentAutoCompleteResults doesnt allow additional properties like stated in the documentation here:
https://apps-sdk-v3.developer.homey.app/FlowCard.html#:~:text=//%20You%20can%20freely%20add%20additional%20properties%20to%20access%20in%20registerRunListener
![image](https://user-images.githubusercontent.com/46961126/160268940-0822e2aa-be0c-4bd1-abb3-01b2213a1608.png)
![image](https://user-images.githubusercontent.com/46961126/160268949-7389496a-e3d9-4b51-997f-3ea8f01073ca.png)

Solution I found is modifying the FlowCard.d.ts on line 92 by modifying the resulting types with array parenthesis and by adding my required properties to the ArgumentAutocompleteResults type.

`type ArgumentAutocompleteCallback = (query: string, args: any) => Promise<FlowCard.ArgumentAutocompleteResults[]> | FlowCard.ArgumentAutocompleteResults[];`

**Comment by jeroenwienk** [comment]
Nice find we will probably ship a fix for this tomorrow.

```
type ArgumentAutocompleteResult = {
  name: string;
  description?: string | undefined;
  icon?: string | undefined;
  image?: string | undefined;
  [key: string]: any;
}

type ArgumentAutocompleteResults = Array<ArgumentAutocompleteResult>;
type ArgumentAutocompleteCallback = (query: string, args: any) => Promise<FlowCard.ArgumentAutocompleteResults> | FlowCard.ArgumentAutocompleteResults;
```

https://github.com/athombv/node-homey-apps-sdk-v3-types/blob/master/lib/FlowCard.d.ts

**Comment by jeroenwienk** [comment]
Fixed in https://www.npmjs.com/package/homey-apps-sdk-v3-types/v/0.3.1
