### ISSUE TITLE
Re-enable option to use multiple pickers in 2.0.0 app; needed e.g. for several thermostat devices

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#25]
The 2.0.0 app (0.18.0.241) only shows 1 picker element (thermostat_mode), where for multiple thermostats 2 or 3 (fan_mode, fan_speed) are defined.
Example is the Remotec app (or many of my other apps): https://github.com/TedTolboom/hk.com.remotec/tree/development

Current view in 2.0.0 app (0.18.0.241):
![image](https://user-images.githubusercontent.com/17163431/50571385-0ec5f800-0da9-11e9-9c97-aff7898cc01c.png)
Code has been updated to have for all capabilities "uiComponent": "picker", added

Example as shown in the mobile interface on 1.5.13:
![image](https://user-images.githubusercontent.com/17163431/50571300-fce35580-0da6-11e9-867c-994867a38e54.png)

Please make sure that the 2.0.0 app supports multiple pickers (with label). 
Combining the thermostat mode, fan mode and fan speed into one picker will not give the right user experience.

**Comment by TedTolboom** [comment]
Affected apps (devices):
* Remotec (ZXT-120, ZXT-600)
* MCO Home (MH7)
* Daikin

**Comment by WeeJeWel** [comment]
A dropdown on top will be added for the following components:

* Picker
* Toggle
* Ternary
* Battery

**Comment by WeeJeWel** [comment]
This has now been implemented.
