### ISSUE TITLE
Error `Device not available` when adding new capabilities on device details.

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#253]
I have an app that remove/add capabilities with the uiComponent: "sensor" based on configuration.

Result:
When the app is open on the device settings and when removing the capability an error occur: `Device not available`.

Expected result:
When the app is open on the device settings and when removing the capability the sensor should be gone.

Steps to reproduce:
```
        setInterval(async() => {
            if (!this.hasCapability('some_capability')) {
                await this.addCapability('some_capability');
            } else {
                await this.removeCapability('some_capability');
            }
        }, 5000);
```

**Comment by koktaildotcom** [comment]
Note: Om the web version of the app this bug does not exist

**Comment by RobinBol** [comment]
Thanks for reporting, we'll take a look!
