### ISSUE TITLE
Radio element in new app results in unreadable text

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#26]
The current implementation of the radio element in device (advanced) settings, results in un-readable text / options.

See examples of the Fibaro app (FGD-212, force_auto_calibration):
![image](https://user-images.githubusercontent.com/17163431/50571533-53ec2900-0dad-11e9-8305-01fb64af2e51.png)
https://github.com/athombv/com.fibaro/blob/beta/drivers/FGD-212/driver.settings.compose.json#L407

or the Xiaomi temperature sensor:
![image](https://user-images.githubusercontent.com/17163431/50571535-5cdcfa80-0dad-11e9-97d0-77f0d7a08057.png)
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/config/drivers/weather.json#L58

I would suggest a vertical structuring of the radio element

**Comment by Christian-Athom** [comment]
This will be available in the Mobile App version 2.0.3.247
