### ISSUE TITLE
Not receiving device events while using homey-api

### ISSUE THREAD

**Issue by daneedk** [athombv/apps-sdk-issues#262]
Hi,

While rewriting Heimdall for SDK3 I'm also switching from `athom-api` to `homey-api` but unfortunately I'm running into problems.
I am not able to receive events for devices. Using the `athom-api` I used this code to register for events:
```
        this.homeyApi.devices.on('device.create', async(id) => {
            this.log('New device found!')
            ... payload removed

        });

        this.homeyApi.devices.on('device.delete', async(id) => {
            this.log('Device deleted:            ',id)
        });
```
and that worked fine. I'm trying to use the same code agains `homey-api` but I'm not receiving anything. The documentation I used is this: https://athombv.github.io/node-homey-api/HomeyAPIV3Cloud.ManagerDevices.html#.event:%22device.create%22
Other commands against `homey-api` such as getting devices, zones, capabilities etc still work.

I hope you can help me out, tell me what I'm doing wrong.

Thanks!

**Comment by jeroenwienk** [comment]
> 

You need to `await devices.connect()` first.

**Comment by daneedk** [comment]
That fixed it, thanks for the fast response!
