### ISSUE TITLE
Url to sigh the [Contributor License Agreement] returns a 404 

### ISSUE THREAD

**Issue by frekel** [athombv/apps-sdk-issues#263]
When creating an app with the SDK3, a CONTRIBUTING.md file is created. In the last line there is a link to the [Contributor License Agreement], but that gives a (kind of) 404 

```
## Speeding up your pull request
Merging pull requests takes time. While we always try to merge your pull request as soon as possible, there are certain things you can do to speed up this process.

* Ask developers to review your code changes and post their feedback.
* Ask users to test your changes and post their feedback.
* Keep your changes to the minimal required amount, and dedicated to one issue/feature only.
* If your PR introduces new features or more than just a small fix, please sign our [Contributor License Agreement](https://go.athom.com/cla).
```

![Screenshot from 2022-10-17 22-20-48](https://user-images.githubusercontent.com/31908/196275594-f44da978-e1ca-4236-8748-5bee4de66391.png)

**Comment by WeeJeWel** [comment]
Thanks! Fixed in https://github.com/athombv/node-homey/commit/8160cf648bb9d38a10da5ce17de9556713b7f087
