### ISSUE TITLE
Values well recorded but wrongly displayed

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#267]
Hi,

### Video
https://user-images.githubusercontent.com/88216225/199022193-670a12c6-6fab-4de2-90f0-ea71b784e218.mov

### Description
- when I manually go from **Fan** or **Dry** to **Heat**, **Cool** or **Automatic**: no problem
- on the other hand: when I manually go from **Heat**, **Cool** or **Automatic** (mapped to built-in `thermostat_mode`) to **Fan** or **Dry**: it automatically returns back to the previous values (without any manual action from my side) **but** as you can see in the video, **Fan** or **Dry** has been well recorded.

### RCA
The issue does not occur when I remove from the code [this condition](https://github.com/OlivierZal/com.melcloud/blob/2881bdff38c3821b264d831e365ede0953df5785/drivers/melcloud/device.js#L205), but objectively it shouldn't cause such an issue since the value has been well recorded despite the display: it's only a display issue.

**Note**: I set the warning message to orientate the end users.

**Comment by OlivierZal** [comment]
Hi,

I have another example of the same display issue, which occurs in similar conditions – that is, when changing manually a given capability modifies another capability.

Display issue because actually the right value is registered (as we can see in the video).

https://user-images.githubusercontent.com/88216225/225350488-359f99cc-b069-4703-a5ca-1cccdb7ea4ea.MP4

**Comment by OlivierZal** [comment]
Hi @regnerus,

I have another example of the same display issue, which occurs in similar conditions – that is, when changing manually a given capability modifies another capability.

It's a display-only issue because actually the right value is registered (as we can see in the video).
Even if it's not backend-related, [here](https://github.com/OlivierZal/com.melcloud/blob/ff5fb3428fcf7b8b17ad135f2527be428a03d45a/drivers/melcloud_atw/device.ts#L75) is where the magics happen (multiple lines and methods are involved though...).

https://user-images.githubusercontent.com/88216225/225350488-359f99cc-b069-4703-a5ca-1cccdb7ea4ea.MP4

**Comment by OlivierZal** [comment]
Hi @regnerus, @WeeJeWel,

I've encountered this issue again in another app.

I can confirm that it's not a backend issue (the values are correctly registered), but a frontend issue.

Context: when a capability is changed from the UI, and triggers the change of another capability in backend (via a `setCapabilityValue()` call), as a a result the displayed capability shifts to the top value, even though the correct value is properly registered in the backend.

This is quite confusing for users, who might get the impression that Homey isn't functioning properly – which isn't the case.
Do you have any idea when this issue might be resolved?

**Comment by regnerus** [comment]
Issue should be fixed in version 8.0.0 (as confirmed by @OlivierZal).
