### ISSUE TITLE
Homey App crashes

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#270]
The Homey app (at least on iPhone) crashes when i remove the trigger card with tokens from the flow (and those tokens are in use in the flow) and replaces the trigger card with some other card that doesn't have these tokens.

If the tokens are not in use in the flow, all is good.

**Comment by regnerus** [comment]
Hi @runely, thanks for submitting an issue with the Homey Mobile App! I tried to replicate your issue myself in the app on iPhone however here it shows the correct behavior (removing the token in the action card, when the trigger card is removed).

Do you have an example of a Flow that breaks and some information about the Mobile app- and Homey version you are using (both can be found under More -> Settings -> General)?

**Comment by runely** [comment]
An example can be found here: https://homey.app/f/iWx4ri

I have tested this with builtin flow triggers and triggers from my own apps, and in all cases the mobile app crashes!

1. Open the flow
2. Remove the trigger card (in this case Presence -> Someone came home)
3. Add a different trigger card (for example Flow -> This flow has been started) _(no matter which as long as it doesn't contain the tokens from the original trigger card)_
    1. As soon as i click the check mark to choose this flow card as a trigger, the mobile app crashes

I can take a screen recording of the crash if you'd like

Mobile app version: 6.11.7.1003
Homey firmware: 8.0.8

**Comment by regnerus** [comment]
@runely thanks for the information! A screen recording would be very helpful, I still cannot reproduce this error.

**Comment by runely** [comment]
Here's a screen recording of two flows that crashes. The timeline notification action uses one of the tokens from the trigger in both flows:

https://user-images.githubusercontent.com/25814673/203600262-cb2633c8-0475-4c0a-8849-ff403fc97a48.mp4

**Comment by runely** [comment]
This is still happening @regnerus

**Comment by shaarkys** [comment]
Yep, happens as well on Android.... not usable like for last 6 months or so.

**Comment by WeeJeWel** [comment]
Oof, we’re sorry about that!
@regnerus can you have a look at this?
