### ISSUE TITLE
Zigbee "Repair View"

### ISSUE THREAD

**Issue by kraineff** [athombv/apps-sdk-issues#272]
Hello! When I add "Repair View" for non-Zigbee driver it works as needed. But when I add same "reapar:" configuration in Zigbee driver manifest it shows me a "Repair" button in Frontend, but on click it shows me error:

https://192-168-1-10.homey.homeylocal.com/api/manager/drivers/pairsession
Request:
{ 
"type": "repair", 
"deviceId": "88b22984-a066-4dc9-9961-b7078c22cd0e", 
"driverUri": "homey:app:com.aqara.home", 
"driverId": "lumi.curtain.agl001" 
}

Response:
{ 
"code": 500, 
"error": "Cannot read property 'name' of undefined", 
"error_description": "Cannot read property 'name' of undefined" 
}

**Comment by kraineff** [comment]
It looks like that Homey cannot create a PairSession for "repair" inside Zigbee device.

**Comment by kraineff** [comment]
This feature is very necessary to display Custom Views, or it would be better if you added the ability to display Custom View using Maintenance Actions

**Comment by kraineff** [comment]
https://user-images.githubusercontent.com/7906418/204615286-ce25b4cc-1f4b-40c9-9ee9-74307bb57d4e.mp4

**Comment by RobinBol** [comment]
Hi @Kraineff , unfortunately it is not possible to create custom (re-)pair views for Zigbee drivers. This is because Homey already provides built-in pair views, as they are the same for all Zigbee drivers.

**Comment by kraineff** [comment]
@RobinBol Thanks for the answer! Yes, it's logical that you can't use your own Pair and Repair for Zigbee, but what about what I wrote above? Enable developers to show their own Views using Maintenance Actions! Calibration is an excellent example of this, which is simply impossible to implement through the usual 2-3 buttons, which requires a more comprehensive approach, the point of Maintenance Actions is just to use them for such device configuration scenarios!

**Comment by kraineff** [comment]
To implement the opening of Custom Views through Maintenance Actions, will require you to add minimal code and will be a great addition to the wonderful Homey interface!

**Comment by RobinBol** [comment]
@Kraineff thanks for the suggestion, unfortunately this is not something we currently have plans to implement. Could you explain the detailed use case, maybe we can come up with another solution?

**Comment by kraineff** [comment]
An example of use, I showed above, so that, for example, for the Aqara Curtain Driver E1 device to open the calibration screen, which is complex and has different calibration strategies: Manual or Auto calibration.

The user opens this special View through Maintenance Action called "Calibration", the user selects the type of calibration, and depending on the type of calibration, the necessary actions are displayed to him that he needs to perform in order.

**Comment by RobinBol** [comment]
Thanks for the info! For now maybe a few maintenance actions (one for each strategy) with a detailed description could suffice.
