### ISSUE TITLE
`Version bump` updates app version in `.homeycompose/app.json` and `app.json` but not in `package.json`

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#273]
**App**: https://github.com/OlivierZal/com.melcloud
**Example of a commit**: https://github.com/OlivierZal/com.melcloud/commit/034c21b4b3e7ea88614db82215be5d84894db05a
**Note**: the main language of the app is  `typescript`

**Comment by WeeJeWel** [comment]
That's actually intended behavior! Your package.json is only there for node_modules management.
