### ISSUE TITLE
`this.homey.i18n.__("non-existent-key")` returns null despite what documentation states

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#275]
The [documentation](https://apps-sdk-v3.developer.homey.app/ManagerI18n.html) for `this.homey.i18n.__()` states that it will return a string.

However, when you pass it an unknown key, it returns `null`.

**Comment by WeeJeWel** [comment]
Thanks. The behavior is correct, the docs are not. I'll update the docs asap.

**Comment by daneedk** [comment]
Same problem when passing it a known key which holds an empty string:

```
let message = this.homey.__("notification.smodeset1") + this.readableMode(value) + this.homey.__("notification.smodeset2")
```

where `notification.smodeset2` is needed for German:

```
    "notification": {
        "smodeset1": "**Überwachungsmodus** auf ",
        "smodeset2": " eingestellt"
    }
```

results in `this.homey.__("notification.smodeset2")` returning `null` for languages where `notification.smodeset2` is not needed:

```
    "notification": {
        "smodeset1": "**Overvågnings Tilstand** sat til ",
        "smodeset2": ""
    }
```

In SDK2 this nicely returned an empty string, which makes more sense

**Comment by robertklep** [comment]
Agreed, it should be able to return an empty translated string.

**Comment by WeeJeWel** [comment]
Nice find! This was a bug in the object parser :-)

It's fixed in upcoming releases for Homey Pro & Homey Cloud.

**Comment by WeeJeWel** [comment]
The docs have been updated: [https://apps-sdk-v3.developer.homey.app/ManagerI18n.html#__](https://apps-sdk-v3.developer.homey.app/ManagerI18n.html#__)
