### ISSUE TITLE
`Homey.alert` and `Homey.confirm`’s `String icons` don’t work

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#279]
**Homey version:** 8.1.1

```
Homey.alert('Authentication failed', 'error')
```

But:

![2FAB5A8B-547B-4F6E-AB14-B752530C4CC8](https://user-images.githubusercontent.com/88216225/210132245-58f0ea4b-aa94-4326-b61b-bc8a2dc92543.png)

Same with `'info'`

**Comment by RobinBol** [comment]
Thanks for reporing, I took a quick look and indeed it seems this is currently not supported. I've created a ticket for this on our backlog!

**Comment by WeeJeWel** [comment]
This is a remnant of Homey v1.x where we had a Web UI with custom icons.

Maybe we can show our own icons in the future.

**Comment by RobinBol** [comment]
@OlivierZal for now we have removed the icons property from the documentation. We will keep this issue on our backlog and maybe bring it back in the future.
