### ISSUE TITLE
req object missing on args in api.js handler

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#28]
Issue on rewriting app to Homey V2 support. 
api.js:
```
{
    description: 'x',
    method: 'GET',
    path: '/',
    public: true,
    fn: function (args, callback) {
      if (args.req === {}) return callback(`missing request IP`)
      if (!onWhitelist(args.req.remoteAddress)) return callback(`not on whitelist`)
//etc    
    }
  }
```
fails because `req` is missing on `args`

**Comment by WeeJeWel** [comment]
Because Homey v2.0 is transport layer agnostic (meaning it can get request over HTTP but not exclusively) we've had to remove the req object altogether.

**Comment by irritanterik** [comment]
In that case I need some guidance on how to implement IP-filtering / origin address filtering for the HTTP App. 
A workable solution would be to return an object `origin` on args with `{type: "http", address: "192.168.0.10"}`

**Comment by jghaanstra** [comment]
I have the same issue with two of my apps (DoorBird and Sonarr/Radarr app). I have now removed the check on origin IP address making the apps less secure but at least they work again.

@WeeJeWel, I can't believe that this is what Athom wants for their product. Hopefully the origin IP can be made available again or supply us with a different secure method that would still allow devices to communicate with Homey on the local network even if the local device is not able to use special HTTP headers.

@irritanterik, is it an idea to at least temporary have the HTTP app use the app API with the public: true option?

**Comment by robertklep** [comment]
@weejewel at some point, everyone that needs this functionality is going to run their own HTTP server on Homey. How desirable is that?

And in terms of security, it's a step back, because now developers can't implement white-/blacklisting based on IP anymore.

I agree with what @jghaanstra suggests, at least expose an origin IP.

**Comment by irritanterik** [comment]
@jghaanstra the non whitelist endpoint can be made public by the existing setting for dis/enabling authorisation.
If there will not be a solution available within the sdk I'll make an option to run a http server like @robertklep suggested

**Comment by WeeJeWel** [comment]
I strongly advice against ip whitelisting because within a LAN it's very easy to spoof.

However if you insist, then running your own webserver is a fine solution.

**Comment by robertklep** [comment]
I would pose that in 99,9% of the cases, Homey's are part of a LAN that can be trusted. 

IP whitelisting is mostly meant to whitelist _external_ IP-addresses (for instance, webhook calls from cloud services).

**Comment by irritanterik** [comment]
@WeeJeWel thanks for your prompt response. I'll ask the community if they appreciate whitelisting on LAN/WAN considering the spoofing risk there.
I'm still hoping Homey APP SDK will one day expose the api.js origin in one way or another.

**Comment by WeeJeWel** [comment]
If you want to validate a WAN IP I'd suggest you create a webhook. You can check the origin IP there.

**Comment by robertklep** [comment]
Can apps dynamically create webhooks?

**Comment by irritanterik** [comment]
Think so

Op za 5 jan. 2019 11:13 schreef Robert Klep <notifications@github.com:

**Comment by jghaanstra** [comment]
But webhooks use the cloud right? Defeats the purpose of local communication between devices 

On 1.5.x the app API was reachable through WAN as well using the cloud URL. Checking on IP whitelist was a simple extra security measure if the app API needed to be available without token.

**Comment by irritanterik** [comment]
I'll knutsel what and decide on best solutions that are configurable, understandable and max cloud independend.

**Comment by WeeJeWel** [comment]
Creating a request to Homey from an external server requires the Cloud anyway, if you're using https://<id>.homey.athom.com (or https://<id>.connect.athom.com on Homey v2.0). So using webhooks would be the preferred approach here, because those are defined as HTTP-capable.

In the scenario you're using LAN request, checking the IP is not secure due to the risk of spoofing. But it's arguable that a user's home network can be considered secure.

The last options would be opening ports in the router but I hope we can all agree that's not desirable...

**Comment by mruiter** [comment]
Worried about op spoofing on local lan , what a Joke. Just worry about the alian attack in Enschede . Thats more likely to be a Security issue .

Bogus Security

**Comment by jghaanstra** [comment]
I understand the point of view for requests from the WAN.

But using the app API with no extra security measures on the LAN is better than doing an extra IP origin check because that might be spoofed?

**Comment by WeeJeWel** [comment]
Rationally speaking it doesn't matter. Checking the IP might _feel_ more secure but it simply isn't.

**Comment by robertklep** [comment]
Because sure, who else uses IP-checking nowadays anymore (apart from firewalls, SMTP spam lists, every major HTTP server, every major database server, ...)

**Comment by cbho** [comment]
And this kind of expose that the approach of increasing dependence of something that requires cloud connection is making the system prone to being not secure...
As far as I can figure out, Homey was able to be the core of a system independent of internet access before, but is now increasingly more dependent on cloud access - and thereby losing a major advantage to other products on the market...
The more you have to rely on external factors, the higher is the risk that you cannot control your house - thus decreasing the usability of Homey as the central part of a serious home automation system...
Correct me if I'm wrong, @weejeweel...

**Comment by WeeJeWel** [comment]
Unfortunately you're wrong. A local system is insecure to begin with when looking at the communication on a LAN network.

Homey is still very independent off the cloud but if a developer is using a remote service that operates outside of the user's network then obviously Homey becomes cloud dependent for that specific device.
