### ISSUE TITLE
Homey css issue with type `number`

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#280]
**Homey version**: 8.1.1

```
<input class="homey-form-input" id="interval" type="number" value="0" min="1" max="60" step="1" />
```
returns a `string` and `min` / `max` / `step` are ignored

**Comment by WeeJeWel** [comment]
Can you share a screencast? This might be a browser issue.

It's expected that a string is returned, by the way.

**Comment by OlivierZal** [comment]
Yes, will do so. Tested on the iPhone Homey app (latest version).

My point was that the behaviour is the same than type `string` – I forgot to precise that letters are accepted.

**Comment by WeeJeWel** [comment]
This might help you: https://stackoverflow.com/questions/45096670/input-type-number-not-working-on-ipad

**Comment by OlivierZal** [comment]
ok, it could explain. Thanks @WeeJeWel
