### ISSUE TITLE
flow.getToken

### ISSUE THREAD

**Issue by magtimmermans** [athombv/apps-sdk-issues#291]
Hi,

 let token = await this.homey.flow.getToken('unkown token');

throws an error instead of returning null.

Secondly:
`        todaysTime.forEach(async event => {
            this.homey.log(`${event.localName} : ${event.dateValue.toLocalDateString(this.lang,this.tz)}`);
            try {
                let token = await this.homey.flow.getToken(event.id);
                if (token)
                {
                    await token.setValue(event.dateValue.toLocalTimeString(this.lang,this.tz));  
                }
            } catch (error) {
                  if (error.toString().includes('token_not_registered')) {
                    try {
                        const newToken = await this.homey.flow.createToken(event.id, {
                            type: 'string',
                            title: event.localName
                        }); 
                        if (newToken)
                            await newToken.setValue(event.dateValue.toLocalTimeString(this.lang,this.tz)); 
                    } catch (error) {
                        this.homey.error(`Event: ${event.id} / '${error}'`); 
                    }
                  } else
                     this.homey.error(`Event: ${event.id} --- '${error}'`);              
            }
        });
`
The wierd thing is if I after that create the token (when it is not registered) I got sometimes:

Event: moonRise / 'Error: flowtoken_already_exists'

This I do not understand. Could this be a site affect of async work or is this a bug.

**Comment by jeroenwienk** [comment]
It's intended to throw so not a bug. 

It's also possible your code might be creating the token at some other point in time so thats why you could get `flowtoken_already_exists` errors.
