### ISSUE TITLE
[i18n][French] wrong translation of `number` in flows

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#295]
Into French `number` can be translated either `nombre` (most frequent case) or `numéro`.

At least in the context of flow, it should be `nombre`:

![334912724_5569790263130838_4009893415559848975_n](https://user-images.githubusercontent.com/88216225/223477411-eb367b5d-e793-4755-a212-e2bb878877bc.jpg)

**Comment by OlivierZal** [comment]
Note: as far as I know, in the context of Homey, `number` should always be translated by `nombre` (and never `numéro`).

**Comment by regnerus** [comment]
Issue should be fixed in version 8.0.0 (as confirmed by @OlivierZal).
