### ISSUE TITLE
Inform/warn/instruct message on app upgrades

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#30]
I'd like an option to add migration instructions to end users on upgrading apps.
So when a braking update is published (x.0.0) automatic update is blocked and a message before or after install is shown with changed or removed functionality. 
Without it testing and looking for appstore.md files is needed after every app update, while most app updates are minor non breaking changes.

**Comment by daneedk** [comment]
Great suggestion!

**Comment by WeeJeWel** [comment]
Thanks for the suggestion, I've noted it internally for consideration.

Closing this issue now because we want to keep this tracker issue-only.
