### ISSUE TITLE
Custom boolean capability title not working

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/apps-sdk-issues#307]
Hi there,

When adding the `titleTrue` and `titleFalse` properties to a custom **boolean** capability as mentioned [here](https://apps.developer.homey.app/the-basics/devices/capabilities#boolean-capability-options) in your documentation, it does not reflect this value on the device screen.

<details>
  <summary>Capability details</summary>

  ```json
  {
    "id": "sound",
    "title": { "en": "Geluid" },
    "type": "boolean",
    "getable": true,
    "setable": true,
    "insights": true,
    "insightsTitleTrue": { "en": "... aan" },
    "insightsTitleFalse": { "en": "... uit" },
    "titleTrue": { "en": "Aan" },
    "titleFalse": { "en": "Uit" },
    "uiComponent": "sensor"
  }
```
</details>

This is shown on the device screen:

![Screenshot 2023-07-13 at 00 43 26](https://github.com/athombv/homey-apps-sdk-issues/assets/9265514/448ed6b8-1dc5-4113-9e94-69e0076538b5)

I expected to see "**Uit"** instead of **"Nee"**.

Best regards,
Edwin

**EDIT:** These properties are not mentioned in [this part](https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities) of the docs. Little bit confusing...
See the part below: "_When the capability type is boolean the following additional..._"

**Comment by jeroenwienk** [comment]
> 

We dont currently support `titleTrue` and `titleFalse` on a capability level. The only possibility is to override them from the capabilityOptions from a driver.

**Comment by edwinvdpol** [comment]
Ah! My bad, thanks!
