### ISSUE TITLE
[Homey Pro 2023][Regression] Peer temperature sub-capabilities (`measure_temperature.xxx` / `target_temperature.xxx`) are not displayed together on Homey Pro 2023

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#309]
**Firmware Homey Pro 2023:** every version 10+ (including the latest `10.0.0-rc.139`)
**App version:** every version 7+ (including the latest `7.3.0 (1236)`)

- temperature peer [main] capabilities (`measure_temperature` / `target_temperature`) are displayed together on Homey Pro 2019 and Homey Pro 2023
- temperature peer sub-capabilities (`measure_temperature.xxx` / `target_temperature.xxx`) are displayed together on Homey Pro 2019
- **however**, temperature peer **sub**-capabilities (`measure_temperature.xxx` / `target_temperature.xxx`) are **not** displayed together on Homey Pro **2023**

Here are screenshots of the same app/device but on 2 different Homey Pros.

**Homey Pro 2019:**

![IMG_2778](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/ac601229-b5fd-4ce3-8c07-4ed971f5cc72)

**Homey Pro 2023:**

![IMG_2777](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/3a4c894a-a7d8-4b7b-923e-2a3654be1614)

**Comment by RobinBol** [comment]
This issue should be fixed in Homey Pro (Early 2023) v10.0.2-rc.1 (currently in beta). Please let me know if this resolves the issue for you.

**Comment by OlivierZal** [comment]
Awesome 👏
