### ISSUE TITLE
[i18n][French] wrong translation of `early` in `Homey Pro (early 2023)`

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#314]
In the context of `Homey Pro (early 2023)`, `early` does not mean `version préliminaire` (~ `preview`) and then should be translated by `début` (~ `at the beginning of 2023`).

**Comment by WeeJeWel** [comment]
Where did you see this piece of text?

**Comment by OlivierZal** [comment]
@WeeJeWel 

![image](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/1ba095de-1bc8-4136-89fd-966825652b8c)

**Comment by WeeJeWel** [comment]
Thank you!

@regnerus These shouldn't be translated at all. Can you please fix this?

**Comment by regnerus** [comment]
This issue is fixed in an upcoming release of the Homey Mobile App, closing this issue.
