### ISSUE TITLE
[HomeyCompose] Unexpected when a same flow is used by multiple drivers

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#318]
When a same flow template is defined under `.homeycompose/drivers/flow/<triggers|conditions|actions>` extends multiple drivers, the following error is raised:

```
✖ Error: Found multiple Flow card triggers with the id "mode_changed", all Flow cards should have a unique id.
```

The reason is that 2 different cards are created in `app.json`:

```
"flow": {
    "triggers": [
      {
        "id": "mode_changed",
        "title": {
          "en": "The mode has changed",
          "fr": "Le mode a changé"
        },
        "tokens": [
          {
            "name": "mode",
            "type": "string",
            "title": {
              "en": "Mode",
              "fr": "Mode"
            },
            "example": {
              "en": "Eco",
              "fr": "Éco"
            }
          }
        ],
        "args": [
          {
            "type": "device",
            "name": "device",
            "filter": "driver_id=heatzy"
          }
        ]
      },
      {
        "id": "mode_changed",
        "title": {
          "en": "The mode has changed",
          "fr": "Le mode a changé"
        },
        "tokens": [
          {
            "name": "mode",
            "type": "string",
            "title": {
              "en": "Mode",
              "fr": "Mode"
            },
            "example": {
              "en": "Eco",
              "fr": "Éco"
            }
          }
        ],
        "args": [
          {
            "type": "device",
            "name": "device",
            "filter": "driver_id=heatzy_1"
          }
        ]
      }
    ],
...
```

although we would expect only one card as follows (with all drivers in `filter`):

```
"flow": {
    "triggers": [
      {
        "id": "mode_changed",
        "title": {
          "en": "The mode has changed",
          "fr": "Le mode a changé"
        },
        "tokens": [
          {
            "name": "mode",
            "type": "string",
            "title": {
              "en": "Mode",
              "fr": "Mode"
            },
            "example": {
              "en": "Eco",
              "fr": "Éco"
            }
          }
        ],
        "args": [
          {
            "type": "device",
            "name": "device",
            "filter": "driver_id=heatzy,heatzy_1"
          }
        ]
      }
    ],
...
```

Here's the code to adapt: https://github.com/athombv/node-homey/blob/master/lib/HomeyCompose.js#L341

Otherwise we miss the interest of having templates...

**Comment by OlivierZal** [comment]
Note: I know I can add different ids in order to differenciate them.

**Comment by WeeJeWel** [comment]
While Homey Compose enabled you to define Flow cards on a driver-leve, in reality Flow cards are available app-wide.

If you 'share' a Flow card between drivers, you need to move it to the app level, so in `.homeycompose/flow/.../my_card.json`.

Then add a filter `"filter": "driver_id=mydriver1|mydriver2"`. Here `|` means 'or'.

**Comment by OlivierZal** [comment]
@WeeJeWel, thanks for your answer.

I do mean at the driver level, that is some drivers (and not others).

**Comment by WeeJeWel** [comment]
That's why you need to target those drivers with `driver_id=mydriver1|mydriver2|...` :)

**Comment by OlivierZal** [comment]
Yes @WeeJeWel, and it works well (that's why I closed this issue in the first place), but if I do as you suggest I notice a difference of behaviour between having flows under `.homeycompose/drivers/flow/` (1st screenshot) or having them under `.homeycompose/flow/` with `$filter=driver_id=...` (2nd screenshot):

![IMG_3542](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/8ffb02e2-e618-43c4-9b0a-2aa6785cd822)

![IMG_3543](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/a27767a4-7d2c-484d-a4ae-14433fd8c988)

**1st screenshot:** flow cards are available only at the device level
**2nd screenshot:** flow cards are available at the device level **and** at the app level

Is that expected?

**Comment by OlivierZal** [comment]
Yes @WeeJeWel, and it works well (that's why I close the issue).
