### ISSUE TITLE
Flow cards wrongly created

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#320]
_@WeeJeWel, issue created as you requested._

I tried to migrate flows from `.homeycompose/drivers/` to `.homeycompose/` + using filters on devices (on the following model: `"filter": "driver_id={driver_id1}|{driver_id2}|..."`) and I found an unexpected behaviour when using a capability in the filter (e.g. `"filter": "driver_id=melcloud_atw&capabilities=operation_mode_zone.zone1"`):
- if there is a device with this capability added: a flow card is created under this given device (expected behaviour)
- **however, if there is a device without this capability added:** the flow card is created at the app level instead of not being created

Here the branch of my tests: https://github.com/OlivierZal/com.melcloud/pull/199/files

You can compare the following screenshots (before / after migration):
![IMG_3542](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/56f2bd73-f145-4503-90e3-c73c17d26665)
![IMG_3543](https://github.com/athombv/homey-apps-sdk-issues/assets/88216225/13a43da3-6324-480a-9865-1f13f4547248)

**Comment by OlivierZal** [comment]
@jeroenwienk, I don't know if it is related, but in the PR above we can see that all the "args/device" sections disappear from the `app.json` while it is the ones containing the device filter:

```
- "args": [
-            {
-              "type": "device",
-              "name": "device",
-              "filter": "driver_id=melcloud_atw&capabilities=alarm_generic.eco_hot_water"
-            }
-          ]
```

**Comment by jeroenwienk** [comment]
Is this on the new Homey Pro (2023)?

**Comment by OlivierZal** [comment]
Yes @jeroenwienk

**Comment by OlivierZal** [comment]
In the end I'm not so sure it's not expected behaviour: I don't know if something missing in the documentation or if I wrongly understood the way to configure, but I succeed in setting up what I want.

Kind regards
