### ISSUE TITLE
[Security] `got@^9.6.0` (required by `homey@3.0.7`) allows a redirect to a UNIX socket

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#321]
The got package before 11.8.5 and 12.1.0 for Node.js allows a redirect to a UNIX socket.

homey@3.0.7 requires got@^9.6.0 via a transitive dependency on package-json@6.5.0

The earliest fixed version is 11.8.5.

**Comment by hmeerlo** [comment]
Won't fix. Requires bigger changes for ESM compatibility.
