### ISSUE TITLE
[Adding new devices]: failing through the Android app but succeeding through the web app

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#324]
Over the past year, numerous **users have failed in adding new devices through the Android app**.
They consistently received the error message: "No device found."

Despite this, the app logs have shown no signs of failures.
What's intriguing is that **these users always found success when using the web app** instead.

Could this problem be tied to a timeout issue within the "add new device" feature on the Android app?

For reference, here are some of the issues reported on GitHub:

https://github.com/OlivierZal/com.melcloud/issues/17
https://github.com/OlivierZal/com.melcloud/issues/24
https://github.com/OlivierZal/com.melcloud/issues/109
https://github.com/OlivierZal/com.melcloud/issues/185
https://github.com/OlivierZal/com.melcloud/issues/186
https://github.com/OlivierZal/com.melcloud/issues/215
https://github.com/OlivierZal/com.melcloud/issues/251

Additionally, I've received further reports via private messages on the Homey Community Forum.
There were also issues reported from the earlier GitHub project, which have since been archived and removed by its owner.

**Comment by hmeerlo** [comment]
Closing this issue as it is not an apps-sdk issue. Please report these issues either through our normal support channels, or when you are a verified developer, through the verified developer portal.

**Comment by OlivierZal** [comment]
Ok, let's use the "normal support channel".
