### ISSUE TITLE
ApiApp "install" and "uninstall" events are no longer called

### ISSUE THREAD

**Issue by cgHome** [athombv/apps-sdk-issues#327]
During the HP2023 beta time in spring, I reported to Emil that the "install" and "uninstall" events were no longer being called in the ApiApp interface. 

He confirmed this and told me that he would put this on the ToDo list and fix the problem as soon as possible. Unfortunately, the events are still not being called, which means that apps sometimes work when booting the Homey and sometimes not, depending on how fast the respective app starts.

THX Chris

**Comment by RobinBol** [comment]
Hi @cgHome, thanks for reporting this issue. It has been fixed and will be released in Homey Pro (Early 2023) v10.3.1. This released is scheduled in a couple of weeks.
