### ISSUE TITLE
`Homey.createDevice()` doesn't pass errors

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#330]
If `Homey.createDevice()` fails (for instance, when trying to add a device with an id that already exists), an error is shown on screen but the call to the method returns without any clue that it failed (no exception thrown, no `undefined` returned, no `error` passed when using callbacks).

**Comment by dskantz** [comment]
Adding some details here:

In a custom Pair View I have the following script:

```` javascript
<script type="text/javascript">
  (function () {
    const $create = document.getElementById("receiver-add-create");
    let creatingDevice = false;

    $create.addEventListener("click", (e) => {
      if (creatingDevice) return;
      creatingDevice = true;
      
       ... 

      Homey.createDevice(device)
        .then(function () {
          return Homey.done();
        })
        .catch(function (err) {
          creatingDevice = false;
          return Homey.Alert(
            "There is already a device with that House Code and Unit Code combination."
          );
        });
    });
  })();
</script> 
````

EXPECTED: Display an alert if any error happens and if Home.createDevice() is successful paring window will be closed.

ACTUAL WEB APP (Chrome and Edge):  Regardless of outcome from Homey.createDevice `then()` is called, `catch()` is never called on errors, and if an error occurs Homey will display an error toast I cannot get rid of.

ACTUAL IPHONE APP:  When not failing, the `then()` call is made, but `catch()` is not called when it fails.

So it seems like in Edge or Chome in the Web App, `catch()` is never called, `then()` is always called.
In the IPhone App, `catch()` is never called, `then()` is only called on success.

**Comment by jeroenwienk** [comment]
> If `Homey.createDevice()` fails (for instance, when trying to add a device with an id that already exists), an error is shown on screen but the call to the method returns without any clue that it failed (no exception thrown, no `undefined` returned, no `error` passed when using callbacks).

I've tested this with the Pro 2023 and it's indeed an issue in the web app. The mobile app is working as intended and the .catch is executed.

I've created a fix for the web app and it will be live soon.
