### ISSUE TITLE
measure_battery check is overwriting custom capabilities in tile indicator settings

### ISSUE THREAD

**Issue by RonnyWinkler** [athombv/apps-sdk-issues#332]
It seems, that the device tile indicator selection is filtering device capabilities using `startsWith(mearure_battery)` and not `== measure_battery`? 
This way, all custom capabilities starting with `measure_battery` are recognizes as standard capability.

Result: 
In indicator selection, only "Battery" is shown instead of all existing measure_battery_* capabilities:

Fix: 
Check using `( capability == 'measure_battery')`
or if subcapabilities should be found, too:
Check using `( capability == 'measure_battery' || capability.startsWith('measure_battery.')`

---

Example:

Capabilities:
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/43ef446b-bd6c-4d10-9ad1-f9932b011531)

Device indicator selection: All capabilities are hidden behind the single "Battery":
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/71db1df4-fc10-4b58-888b-054a43998202)

If e.g. measure_battery_usable is selected, the GUI is showing the value different:
WebApp: Showing as battery icon:
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/aef3e1cf-0dac-41c7-a502-1b4ccbaca914)
MobileApp: Showing correct as percentage
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/749472b7-9b66-4f57-a365-053e8ad71c31)

**Comment by jeroenwienk** [comment]
> It seems, that the device tile indicator selection is filtering device capabilities using `startsWith(mearure_battery)` and not `== measure_battery`? This way, all custom capabilities starting with `measure_battery` are recognizes as standard capability.
> 
> Result: In indicator selection, only "Battery" is shown instead of all existing measure_battery_* capabilities:
> 
> Fix: Check using `( capability == 'measure_battery')` or if subcapabilities should be found, too: Check using `( capability == 'measure_battery' || capability.startsWith('measure_battery.')`
> 
> Example:
> 
> Capabilities: ![grafik](https://private-user-images.githubusercontent.com/49495550/296837460-43ef446b-bd6c-4d10-9ad1-f9932b011531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAwODQsIm5iZiI6MTcyNDI0OTc4NCwicGF0aCI6Ii80OTQ5NTU1MC8yOTY4Mzc0NjAtNDNlZjQ0NmItYmQ2Yy00ZDEwLTlhZDEtZjk5MzJiMDExNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2JmYzFjMWRiZWQyMjc2MTJiMDAwNWQ0YjA0ZThiYjRmNTMwNTBjNGNiMmEwYjI1OTc3NTYxYmQzYWE4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbK9igACDEAQ9zdOv4qBkDFRcoKgR2FJUEd20rjDL4E)
> 
> Device indicator selection: All capabilities are hidden behind the single "Battery": ![grafik](https://private-user-images.githubusercontent.com/49495550/296837601-71db1df4-fc10-4b58-888b-054a43998202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAwODQsIm5iZiI6MTcyNDI0OTc4NCwicGF0aCI6Ii80OTQ5NTU1MC8yOTY4Mzc2MDEtNzFkYjFkZjQtZmMxMC00YjU4LTg4OGItMDU0YTQzOTk4MjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzA2YmNlNjI4MTUzMzc3NWE1MTkxYzhkMjA4ZTY0MzE3N2FjODMyYmQ3YTUzYTczOGYyZTdjODFhNjQ1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yedRFKzY_8xp49xezEbX6HVnOe_cXZwEw5YeZasKm1Y)
> 
> If e.g. measure_battery_usable is selected, the GUI is showing the value different: WebApp: Showing as battery icon: ![grafik](https://private-user-images.githubusercontent.com/49495550/296838118-aef3e1cf-0dac-41c7-a502-1b4ccbaca914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAwODQsIm5iZiI6MTcyNDI0OTc4NCwicGF0aCI6Ii80OTQ5NTU1MC8yOTY4MzgxMTgtYWVmM2UxY2YtMGRhYy00MWM3LWE1MDItMWI0Y2NiYWNhOTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MzA2NDY2NjY5OWQxOWE1NmM1NWQ3Y2JiYzczNTdlNmI5Zjg3MGQ3OWI0NWE1YTBlYjg3ZmRhOGQ1ZTYxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTo5rpyXVqvHBSQ6xfyu9hipewIqD4QwCgxhInkoAw0) MobileApp: Showing correct as percentage ![grafik](https://private-user-images.githubusercontent.com/49495550/296838261-749472b7-9b66-4f57-a365-053e8ad71c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAwODQsIm5iZiI6MTcyNDI0OTc4NCwicGF0aCI6Ii80OTQ5NTU1MC8yOTY4MzgyNjEtNzQ5NDcyYjctOWI2Ni00ZjU3LWEzNjUtMDUzZThhZDcxYzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDE5MjRiYmE3NzQ0ZTIzZWU5ZTE5NzRhNmI5Mjc0MWFlNGEwYTg4YTY2NTYzYTdkZWE4NTdmNDQ4NWQxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ns9f__zTAee2SBW-wenl-djzXdn99u1-yxBhlJnw9gQ)

I have fixed this issue in the web app which will probably be shipped with v1.11.12. For the selecting I have created an issue in the mobile app which will be fixed at some point. Thank you for the report.
