### ISSUE TITLE
WebApp device tile indicator: string measure* capabilities are read as numeric 

### ISSUE THREAD

**Issue by RonnyWinkler** [athombv/apps-sdk-issues#334]
Hello Athom team,

I got screenshots from a user with different behaviour of WebApp and Mobile app.

The app uses a `measure_generic` custom capability, type `string`.
This capability is set as tile indicator in mobile app.

The value is show corrently in mobile app:
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/377360ce-1c25-4166-a809-f52a573d67dd)

WebApp seems to parse measure* named capabilities only as numeric values and is not checking the type.
![grafik](https://github.com/athombv/homey-apps-sdk-issues/assets/49495550/91b5eefd-abc3-4f4a-b45b-48449fc6dd64)

Could you add a type check for WebApp that the value is shown as string in this case even if the capability is named measure*?

Thanks and regards
Ronny

**Comment by jeroenwienk** [comment]
Why is a measure_ used for a non number capability. This is not how it's supposed to be used.

https://apps.developer.homey.app:8443/the-basics/devices/capabilities#device-indicators-and-custom-capabilities

We currently support string indicators in the mobile app and it will be added in the web app soon.
