### ISSUE TITLE
Error in Homey.__(...) translation function for HP2023

### ISSUE THREAD

**Issue by frodeheg** [athombv/apps-sdk-issues#337]
If I in my locales/en.json define something as a multi line string like this (for readability for very long strings):
```
"multilineString": ["First line <!--",
                    "-->Second line <!--",
                    "-->Third line"],
```
Then in the settings/index.html I have
`<p data-i18n="multilineString"></p>`

Then on Homey 2019 this will display as:
`First line Second line Third line`
But on Homey 2023 this will display as:
`[object Object]`

The reason is that Homey.__('multilineString') return this differently

HP2019 returns this as an array:
`["First line <!--", "-->Second line <!--", "-->Third line"]`
HP2023 returns this as an object:
`{0: "First line <!--", 1: "-->Second line <!--", 2: "-->Third line"}`

**Comment by jeroenwienk** [comment]
> If I in my locales/en.json define something as a multi line string like this (for readability for very long strings):
> 
> ```
> "multilineString": ["First line Second line Third line"],
> ```
> 
> Then in the settings/index.html I have `<p data-i18n="multilineString"></p>`
> 
> Then on Homey 2019 this will display as: `First line Second line Third line` But on Homey 2023 this will display as: `[object Object]`
> 
> The reason is that Homey.__('multilineString') return this differently
> 
> HP2019 returns this as an array: `["First line <!--", "-->Second line <!--", "-->Third line"]` HP2023 returns this as an object: `{0: "First line <!--", 1: "-->Second line <!--", 2: "-->Third line"}`

What is this syntax ?

I dont see anywhere we support arrays in locale files. The key should be string and the value too. 

Doesn't \n work?

**Comment by frodeheg** [comment]
The origin of this was to avoid having a 2000-character long line in the JSON-file when the comment is long.
Using an array of strings made it possible to spread it on multiple lines in the json-file.

The point of this report was not whether or not it is a normal thing to do or if it's stupid to use the array. The point here was that there is a discrepancy between how HP2019 and HP2023 on how this is displayed. Thus I had no idea that my apps was not displaying this correctly on HP2023 before now.

So whatever you choose to do I don't really care, because I have already changed to the string-syntax in my apps. But I wanted to make you aware that there is a HP2019 and HP2023 discrepancy.

**Comment by jeroenwienk** [comment]
> The origin of this was to avoid having a 2000-character long line in the JSON-file when the comment is long. Using an array of strings made it possible to spread it on multiple lines in the json-file.
> 
> The point of this report was not whether or not it is a normal thing to do or if it's stupid to use the array. The point here was that there is a discrepancy between how HP2019 and HP2023 on how this is displayed. Thus I had no idea that my apps was not displaying this correctly on HP2023 before now.
> 
> So whatever you choose to do I don't really care, because I have already changed to the string-syntax in my apps. But I wanted to make you aware that there is a HP2019 and HP2023 discrepancy.

I'm just wondering where you learned to do this. Also is `<!--` something that actually does anything or is it just for your example? Since you omitted it from the parsed string `First line Second line Third line` I dont know that that is.

**Comment by frodeheg** [comment]
If you just use an array of strings
`["This", "is", "an", "array", "of", "strings"]`

Then it is displayed as 
`This, is, an, array, of, strings`
By the array.toString function

Thus, I just use the html-tags `<!--` and `-->` to hide the commas because this is the html-syntax for hidden comments in a html-file

**Comment by frodeheg** [comment]
So, it's just a rather stupid workaround to allow multiline strings in a json file :-p

And I came to this idea myself, I haven't seen anyone else using this approach...
