### ISSUE TITLE
Please delete the "org.cflat-inc.homepageApi" App in "Developer Tools > myApps"

### ISSUE THREAD

**Issue by cgHome** [athombv/apps-sdk-issues#339]
Since I had to change my app from "org.cflat-inc.homepageApi" to "org.cflat-inc.homepageExtender" at your request, could you delete it in Developer Tools > myApps ?

BDW: Wouldn't this be a good idea if the developer could do this himself ?

THX Chris

**Comment by jeroenwienk** [comment]
Please contact support for this.

**Comment by cgHome** [comment]
Hi @jeroenwienk 

I did it and the support team sent me to you !🤷‍♂️!  > see (Request (118447)

![image](https://github.com/athombv/homey-apps-sdk-issues/assets/1766853/583cad36-0854-4ace-98df-7c6351da2ce4)

**Comment by jeroenwienk** [comment]
> 118447

Ok something went wrong in communication then I will see if I can delete the app.
