### ISSUE TITLE
Missing module with `"@types/homey": "npm:homey-apps-sdk-v3-types@^0.3.5"`

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#341]
`@types/homey/tsconfig.json`:

```json
{
  "extends": "@tsconfig/node12/tsconfig.json"
}
```

raises a TypeScript error:
```
File '@tsconfig/node12/tsconfig.json' not found.
```

**Comment by jeroenwienk** [comment]
> `@types/homey/tsconfig.json`:
> 
> ```json
> {
>   "extends": "@tsconfig/node12/tsconfig.json"
> }
> ```
> 
> raises a TypeScript error:
> 
> ```
> File '@tsconfig/node12/tsconfig.json' not found.
> ```

Is this still relevant @OlivierZal ?

**Comment by OlivierZal** [comment]
Yes @jeroenwienk, I checked yesterday when I raised https://github.com/athombv/node-homey-apps-sdk-v3-types/pull/31 and the error is still here.

**Comment by OlivierZal** [comment]
Just a precision @jeroenwienk: the error is raised when the module is installed in another app.

**Comment by jeroenwienk** [comment]
> Just a precision @jeroenwienk: the error is raised when the module is installed in another app.

Do you have an example repo for me where this issue occurs?

**Comment by OlivierZal** [comment]
I've realized maybe it's the way VSCode (wrongly) analyzes module's tsconfigs once opened.

Anyway does not have any impact neither on code or Homey types, I close to avoid useless investigation.
