### ISSUE TITLE
Missing command classes

### ISSUE THREAD

**Issue by 4braincells** [athombv/apps-sdk-issues#342]
E.g. TIME,  TIME_PARAMETERS
and others, compared e.g. to  github.com/OpenZWave repo, are missing.

Maybe this is a misunderstanding on my side, so I would appreciate if somebody explains how HOMEY works with time synchronization:
Starting point of my "research" was that I wonder why my MCO MH7H thermostat did not update on Sunday for CET DST (+1h).
a) Should the device do this, similar to an ntp client? How?
b) Or should HOMEY set the time actively?
c) Or should this be done by a flow?

a seems not to be the case, for b and c the zwave driver should implement the respective COMMAND_CLASSES, which are exposed by the device.

thx for ur ideas

**Comment by ttherbrink** [comment]
The command class TIME is used by devices to ask the controller the current time. Homey does not have this feature implemented at this moment. If this commandclass is required for this device we will add this to our feature requests

**Comment by 4braincells** [comment]
> If this commandclass is required for this device we will add this to our feature requests

Well, at least I suspect this is the reason why MCO MH7H doesnt switch CET / CET-DST and does not adjust when time differs from homey, which (hopefully?) will sync using ntp (See also https://community.homey.app/t/time-server-ntp/25119).
So I would appreciate if s.o. could confirm my assumption.

**Comment by ttherbrink** [comment]
Your assumption is correct.
Homey syncs its time using ntp.
At the moment the time stored on Homey is not available on the Z-Wave network due to the lack of the implementation of the commandclass TIME on Homey.
I will add this to our list of feature requests
