### ISSUE TITLE
Decimal / step capabilitiesOptions for measure_temperature and target_temperature incorrect

### ISSUE THREAD

**Issue by gslender** [athombv/apps-sdk-issues#343]
Is this a bug in Homey or a mistake in my configuration/setup of the capabilities?

```
  "capabilitiesOptions": {
    "measure_temperature": { "step": 0.1 , "decimals": 1},
    "target_temperature": { "step": 0.1 , "decimals": 1 }
  }
```
In the pic below the tile for the device shows decimals with 1 and 2 places and the config card shows the opposite places and switched around. Both are wrong and I want just single 1 decimal place to be consistent for `measure_temperature` and `target_temperature`

![image](https://github.com/athombv/homey-apps-sdk-issues/assets/2344457/7b14de7d-c875-4124-ab76-defb8e0a02de)

**Comment by jeroenwienk** [comment]
> Is this a bug in Homey or a mistake in my configuration/setup of the capabilities?
> 
> ```
>   "capabilitiesOptions": {
>     "measure_temperature": { "step": 0.1 , "decimals": 1},
>     "target_temperature": { "step": 0.1 , "decimals": 1 }
>   }
> ```
> 
> In the pic below the tile for the device shows decimals with 1 and 2 places and the config card shows the opposite places and switched around. Both are wrong and I want just single 1 decimal place to be consistent for `measure_temperature` and `target_temperature`
> 
> ![image](https://private-user-images.githubusercontent.com/2344457/330630044-7b14de7d-c875-4124-ab76-defb8e0a02de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzk2MTEsIm5iZiI6MTcyNDIzOTMxMSwicGF0aCI6Ii8yMzQ0NDU3LzMzMDYzMDA0NC03YjE0ZGU3ZC1jODc1LTQxMjQtYWI3Ni1kZWZiOGUwYTAyZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTEyMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFiNDJkNGE1YWNlN2UxYjM3NDQ3NzcwMDAyMjhhNTYwNWZiNDRlMGI2Y2I1ZWJjOWU5ZDVjYjFmNjg1NjUzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b2lhrvq24X4YXcc9M1PriMa9cjSVSvInWXIafFFjS4o)

It seems this was a bug in the webapp. This will be fixed a a next release of the web app. (v1.11.11)
