### ISSUE TITLE
Trigger card automatically created/derived from app code (not custom flow triggers) but Homey firmware based trigger card

### ISSUE THREAD

**Issue by jtebbens** [athombv/apps-sdk-issues#344]
I am developer for HomeWizard app and the trigger cards that are created by Homey itself (so not a custom card in my app) seems not to trigger. Added screen shot shows example of those that don’t seem to hit at all.

Example is for voltage (see screencapture from community forum. Voltage triggered card is created automatically from Homey OS/firmware based on capability that comes from the P1 driver code but is not a custom trigger developed me.

![image](https://github.com/athombv/homey-apps-sdk-issues/assets/18558267/b9fb01eb-1789-4efc-8989-2e7f7a2973ff)

Link to post
https://community.homey.app/t/app-pro-homewizard/19267/1411?u=jeroen_tebbens

**Comment by RobinBol** [comment]
Hi @jtebbens, that is strange, can you provide a minimum reproduction so we can verify the bug is cause by Homey and not your app? By the way, from the forum post, I can't conclude that the voltage value actually changed to a value higher than 250 or lower than 220 (note it must exceed the threshold before the Flow card triggers).

**Comment by jtebbens** [comment]
Hi @RobinBol, thanks for you reply. I haven't replicated myself (yet) but pretty sure my app user Theo de Koning did as per screenshot. I just raise it on his behalf as its not a trigger card my code controls at all. Its derived from the measure_voltage.l1 per P1 energy driver. Let me try to replicate it myself as well.

**Comment by jtebbens** [comment]
Alright, tested myself now and it does work (as designed of course).
Only the event or moment triggers the card not ever pull of data of the device and check. Havent tested it yet with a variable that is updated on the fly (like max volt a d reset with newer max volt). 
![IMG_0889](https://github.com/athombv/homey-apps-sdk-issues/assets/18558267/c3d08b8a-ee71-4c74-830b-5c67b94b5974)
![IMG_0678](https://github.com/athombv/homey-apps-sdk-issues/assets/18558267/95820197-4406-41da-8d3e-6369c34a233e)
![IMG_0888](https://github.com/athombv/homey-apps-sdk-issues/assets/18558267/9c4b2458-1f16-4116-99de-19d8df28f4ed)

**Comment by RobinBol** [comment]
That is great! Not sure what you mean with this exactly though: "Only the event or moment triggers the card not ever pull of data of the device and check. Havent tested it yet with a variable that is updated on the fly (like max volt a d reset with newer max volt)."

This issue can be closed?

**Comment by jtebbens** [comment]
I mean the passing moment of the volt value going from   x < 238v ->         x > 238v.
Af that if x is still higher than 238v nothing will trigger next time until it drops below 238v and that condition is reset and card will trigger again when that moment happens again.

Yes will close.

**Comment by RobinBol** [comment]
I see, that is correct indeed. That is how those cards are meant to work.

**Comment by jtebbens** [comment]
One last comment/question on this. What *if* that variable is changing. So instead of a hardcoded 238v in my example. But a custom variable that holds the value 238, then in the flow it updates from 238 to 239. Does that active condition in the first card that holds that variable card (which now is not 238 but 239). Would it then trigger or does the flow need to be stopped/started to reset that condition?

**Comment by RobinBol** [comment]
I am not 100% sure to be honest, I believe it is best to use static values as input for trigger cards.
