### ISSUE TITLE
ApiApp "install" and "uninstall" events do not work properly when deactivating/activating the OtherApp

### ISSUE THREAD

**Issue by cgHome** [athombv/apps-sdk-issues#349]
I have noticed that the fix for the [issue](https://github.com/athombv/homey-apps-sdk-issues/issues/327) in v11.1.1 is still not working properly.

If you deactivate the OtherApp, the event is sent "uninstall" once, then you can activate/deactivate the OtherApp and no more events arrive at my app.

Chris

**Comment by RobinBol** [comment]
Hi @cgHome , could you elaborate a bit? Perhaps provide a reproduction scenario?

I've tried to reproduce myself, created an app (app X) that listens for install/uninstall events from a different app (app Y). When I disable Y I get the uninstall event in X, then I enable Y and get the install event in X. I can repeat this as often as I'd like and the events keep arriving.

**Comment by RobinBol** [comment]
Hi @cgHome for now I'll close the issue due to inactivity, but please let us know if this is still an issue for you, then we'll re-open.
