### ISSUE TITLE
Device with Capability dim is not triggered when capability is changed in other flow

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/apps-sdk-issues#35]
I have 2 flows. In the first flow a device called 'main_dimmer' with capability dim is set to a value.
A second flow is triggered when the device is changed (and then sets the dim-value of 2 other dim-devices).
When changing the 'main_dimmer' manually, the second flow is triggered as it should and the 2 other dimmers are set as well.
However when the first flow is triggered, the 'main_dimmer' is updated, but the second flow is not triggered.

The output:
```
2019-01-14 19:36:21 [log] [ManagerDrivers] [virtual_switch] [52] Issue trigger -> Capability changed: {"button":null}
2019-01-14 19:36:22 [log] [ManagerDrivers] [virtual_switch] [48] main dimmer -> Capability changed: {"dim":0.58}
```

The code-snippet from device.js is as follows:
```
  onInit() {
    this.log('Virtual Device (' + this.getName() + ') initialized');

    let thisDeviceChanged = new Homey.FlowCardTriggerDevice('press');
    thisDeviceChanged.register();

    // When capability is changed
    this.registerMultipleCapabilityListener(this.getCapabilities(), (changedCapabs, optsObj) => {
      this.log(this.getName() + ' -> Capability changed: ' + JSON.stringify(changedCapabs));

      process.nextTick(async () => {
        await sleep(100);
        thisDeviceChanged.trigger( this, {}, changedCapabs )
          .catch( this.error );
        })

      return Promise.resolve();
    }, 500);
  }
```

Where the flow.trigger 'press' is defined in app.json:
```
      {
        "id": "press",
        "title": {
          "en": "Pressed / changed",
          "nl": "Ingedrukt / veranderd"
        },
        "args": [
          {
            "name": "device",
            "type": "device",
            "filter": "driver_id=virtual_switch"
          }
        ]
      },
```

See also:
https://github.com/ArjanKranenburg/virtual-devices/issues/80

**Comment by WeeJeWel** [comment]
Can you post a few screenshots of your Flows? I find it very hard to understand the actual issue.

**Comment by ArjanKranenburg** [comment]
If you value my feedback than don't close issues like #33 and #34 before I can properly respond. The USB cable didn't work either (same issue) and the icons could be set before, so there are now lot's of users with a multi-mode that do not know which mode is which. Would the custom capability allow them to set the icon when pairing?

Now, for this issue:
The first flow:
![image](https://user-images.githubusercontent.com/2014478/51440543-a643aa00-1cc8-11e9-91c1-719464eeb0b1.png)
![image](https://user-images.githubusercontent.com/2014478/51443898-7b6d4c00-1cf0-11e9-8028-ea130603313f.png)
![homey _screenshot](https://user-images.githubusercontent.com/2014478/51524723-06546080-1e2f-11e9-82b0-81a0e5cbb59a.png)

En the second flow:
![image](https://user-images.githubusercontent.com/2014478/51443918-c0917e00-1cf0-11e9-9349-52ce7d66d0c3.png)
![image](https://user-images.githubusercontent.com/2014478/51443921-cbe4a980-1cf0-11e9-9211-43fe2592a6d2.png)

**Comment by ljsvv** [comment]
Sorry for my brutal disturbance.
First flow is a bit different, it adds a relative dim % to a virtual device. 
After this, the value of that dimmer becomes a value with a lot of digits... so for example dim value was 0,5 add 10%, dim gets 0,55000001. When this value has a lot of digits, the second flow does not bring over that tag value to the actual devices. Only a value with 2 digits after the comma.

**Comment by ArjanKranenburg** [comment]
I've updated the comment above, since the 3rd screenshot was not correct.

Because of ljsvv's comment, the first thing I tried was with a fixed dim-value (58%), but that does not work either.

**Comment by ljsvv** [comment]
@WeeJeWel is someone from Athom willing to answer this developer?

**Comment by WeeJeWel** [comment]
I've read the issue multiple times but really have a hard time understanding it.

@ArjanKranenburg Maybe you can create a simple Homey app with only this functionality so I can reproduce the issue myself?

**Comment by WeeJeWel** [comment]
Closed due to inactivity.

**Comment by ljsvv** [comment]
Really? It took 22 days to respond from Athom side and now you’re Not even giving a dev more than 5 days to respond????
