### ISSUE TITLE
Booleans on Insights

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#350]
Hi,

On https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities I learn about the property "insights" for all custom capabilities. Further down I learn that for booleans there are also "insightsTitleTrue" and "insightsTitleFalse". Thus, for my custom capability alarm_filter (see below), I would expect it to show up in Insights. However, it doesn't.
```
{
    "type": "boolean",
    "title": { "en": "Filter change needed" },
    "getable": true,
    "setable": true,
    "uiComponent": "sensor",
    "uiQuickAction": "true",
    "icon": "/assets/icon.svg",
    "insights": true,
    "insightsTitleTrue": { "en": "Filter change needed" },
    "insightsTitleFalse": { "en": "Filter OK" }
  }
```

I'm unsure if I'm doing something wrong, but Athom support referred me to this place, which is why I'm filing it as an issue here.

Thanks,
Jonatan

**Comment by RobinBol** [comment]
Hi @wentzel , boolean capabilities are not available in Insights, only numeric capabilities. Boolean capabilities will be shown in the device timeline.

**Comment by wentzel** [comment]
Thanks for the quick reply! In that case my suggestion is to include that information in the documentation. I have spent countless number of hours trying to understand what I'm doing wrong.
