### ISSUE TITLE
Status Indicator for class thermostat

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#351]
Hi,

There seems to be a bug with the selection of Status Indicator for the class `thermostat`.

In the Web App I can select from many of the device's capabilities:
![image](https://github.com/athombv/homey-apps-sdk-issues/assets/2807352/80080c61-d912-4c4c-8bb9-d02fd8d80838)

However, the setting doesn't seem to have any effect:
![image](https://github.com/athombv/homey-apps-sdk-issues/assets/2807352/6777cff6-d63c-474b-b77b-77c0a9128df4)

In the Mobile App, it tells me the Status Indicator is "Not configurable".

The rumor in the forum is that thermostats cannot have he status indicator configured. If that's sadly the case, then there is a bug in the Web App in that it still let's the user choose from the dropdown. Also, it would be great to add this limitation to the documentation.

Finally, if indeed the thermostat does not support the configuration of the status indicator, please do consider this issue a feature request to change that. And also to make sure that the soon-to-be-released `heatpump` will have the status indicator configurable.

Thanks!

**Comment by jeroenwienk** [comment]
> Hi,
> 
> There seems to be a bug with the selection of Status Indicator for the class `thermostat`.
> 
> In the Web App I can select from many of the device's capabilities: ![image](https://private-user-images.githubusercontent.com/2807352/346570569-80080c61-d912-4c4c-8bb9-d02fd8d80838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTAwMzEsIm5iZiI6MTcyMTY0OTczMSwicGF0aCI6Ii8yODA3MzUyLzM0NjU3MDU2OS04MDA4MGM2MS1kOTEyLTRjNGMtOGJiOS1kMDJmZDhkODA4MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTIwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE3OGNiNTcyMmE3NWVhYzk5ZDc2NDAxYTgyZjFlYzllMWU3NWJlZjkyNWJmYmU2MTNkOGMxMTdhZmM4M2NhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ECVG7VOhXxWHnSdPIxc22L8jWyeItXkCAg33cvz5Pf0)
> 
> However, the setting doesn't seem to have any effect: ![image](https://private-user-images.githubusercontent.com/2807352/346570680-6777cff6-d63c-474b-b77b-77c0a9128df4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTAwMzEsIm5iZiI6MTcyMTY0OTczMSwicGF0aCI6Ii8yODA3MzUyLzM0NjU3MDY4MC02Nzc3Y2ZmNi1kNjNjLTQ3NGItYjc3Yi03N2MwYTkxMjhkZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTIwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNmM2QyYWE1N2FkYWI1ZmRlZmU0Njk4MGVmODA5OGQwOWM3NTI0YWI5YTY1YzU5YzVkNTVmYmRmOTEwYWFhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EpKpykEfRnGAebZrKN64yaddoobNI7KLD8EHtqQOW-I)
> 
> In the Mobile App, it tells me the Status Indicator is "Not configurable".
> 
> The rumor in the forum is that thermostats cannot have he status indicator configured. If that's sadly the case, then there is a bug in the Web App in that it still let's the user choose from the dropdown. Also, it would be great to add this limitation to the documentation.
> 
> Finally, if indeed the thermostat does not support the configuration of the status indicator, please do consider this issue a feature request to change that. And also to make sure that the soon-to-be-released `heatpump` will have the status indicator configurable.
> 
> Thanks!

A fix for this is currently being worked on for the web app. Thank you for reporting this.

**Comment by snibbit** [comment]
@wentzel This was indeed a bug in the Web App. As is the case in the Mobile App, the status indicators of thermostats shouldn't be configurable. The issue should now be fixed!
