### ISSUE TITLE
Missing documentation: Description of limitations of boolean capabilities

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#352]
As a developer I would expect to find information about how custom capabilities work in the documentation. Currently, incorrect information is given in https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities.

The page states that the property `insights` "can be set for all custom capabililties". However, as the developers has explained in another ticket, it cannot for `boolean` type capabillities. Perhaps there are other types that also cannot be shown in insights? I would suggest to add a sentence on the description of the `insights` property that clarifies this.

The page also states that the properties `insightsTitleTrue` and `insightsTitleFalse` are "A translation object which describes the title when shown in a Timeline". I would suggest to add a sentence to clarify that despite the name of these properties, this does NOT mean that they will show up in Insights. I would also like to suggest to mark these properties as deprecated and introduce new properties called `timelineTitleTrue` and `timelineTitleFalse` to not mislead developers with the naming of these properties.

**Comment by jeroenwienk** [comment]
> As a developer I would expect to find information about how custom capabilities work in the documentation. Currently, incorrect information is given in https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities.
> 
> The page states that the property `insights` "can be set for all custom capabililties". However, as the developers has explained in another ticket, it cannot for `boolean` type capabillities. Perhaps there are other types that also cannot be shown in insights? I would suggest to add a sentence on the description of the `insights` property that clarifies this.
> 
> The page also states that the properties `insightsTitleTrue` and `insightsTitleFalse` are "A translation object which describes the title when shown in a Timeline". I would suggest to add a sentence to clarify that despite the name of these properties, this does NOT mean that they will show up in Insights. I would also like to suggest to mark these properties as deprecated and introduce new properties called `timelineTitleTrue` and `timelineTitleFalse` to not mislead developers with the naming of these properties.

I've added your first suggestion. As for you second one we cant't just change property names the impact will too large to make it worth the improvement.
