### ISSUE TITLE
Missing documentation: Limitations and consequences of using a specific Device Class

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#353]
As a developer I would expect to find information in the documentation about how my choice of device class impacts my app. Currently, significant information about the `thermostat` class i missing. And perhaps also for other classes?

Through [discussions in the forum](https://community.homey.app/t/users-choice-of-status-indicator-doesnt-work/112548) I've understood that there are limitations in what can be done with the `thermostat` class. E.g. it seems like you have placed a lock on the ability for the user to choose Status Indicator. Perhaps there are even more limitations/consequences when using this class?

There doesn't seem to be any documentation for these kinds of limitations/consequences - the only documentation seems to be the extremely short descriptions on the [Device Classes Reference page](https://apps-sdk-v3.developer.homey.app/tutorial-device-classes.html).

My suggestion is to add documentation for each class, describing the consequences and limitations of using a specific class. At least for the `thermostat` but also for any other class that introduces limitations of similar magnitude.

**Comment by jeroenwienk** [comment]
I've added a warning section here https://apps.developer.homey.app/the-basics/devices/capabilities#device-indicators-and-custom-capabilities. Thanks for the suggestion.
