### ISSUE TITLE
Feature request: Display Booleans in Insights

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#354]
As a user I need to be able to analyze my smart home sensors in relation to boolean values. E.g. in order to understand how my garden watering system performs, I need to be able to track the humidity levels (sensors) in relation to when the water pipelines were opened and closed (booleans).

A suggested solution to this need is to display Booleans in Insights. They seem to already be logged, given that they are shown on the Timeline. Thus, displaying them also in Insights should be more of a UI/UX challenge than a technical challenge. Hopefully your UX designers will accept that challenge 😉

**Comment by jeroenwienk** [comment]
They are not logged to the same extent as number values. We only keep track of the last 50 boolean values at the moment to save space. The current insights for numbers are also stored in a https://en.wikipedia.org/wiki/RRDtool. I will add your suggestion to our feature request board.
