### ISSUE TITLE
Incorrect/Missing documentation: Information about uiQuickAction

### ISSUE THREAD

**Issue by wentzel** [athombv/apps-sdk-issues#355]
As a developer I would expect to find information in the documentation about how the uiQuickAction works, sufficient enough to successfully implement the uiQuickAction behavior. Currently, this is not the case.

The property uiQuickAction is briefly mentioned in the section around [Custom Capabilities](https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities). However, from [discussions in the community](https://community.homey.app/t/how-do-i-use-uiquickaction/112549) I have understood that it is not true that this property can be applied to any Boolean, even though this is what is claimed in the documentation. It seems like there are restrictions on what UI component needs to be used in order for it to work. If this is truly the case, this information should be included in the documentation.

**Comment by jeroenwienk** [comment]
> As a developer I would expect to find information in the documentation about how the uiQuickAction works, sufficient enough to successfully implement the uiQuickAction behavior. Currently, this is not the case.
> 
> The property uiQuickAction is briefly mentioned in the section around [Custom Capabilities](https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities). However, from [discussions in the community](https://community.homey.app/t/how-do-i-use-uiquickaction/112549) I have understood that it is not true that this property can be applied to any Boolean, even though this is what is claimed in the documentation. It seems like there are restrictions on what UI component needs to be used in order for it to work. If this is truly the case, this information should be included in the documentation.

It seems that in the topic you provided the user has set the uiQuickAction field to the string "true" and not to the boolean true. I've created an internal issue that should prevent users from making this mistake in the future.
