### ISSUE TITLE
`setUnavailable` not working when called in `onInit`

### ISSUE THREAD

**Issue by ChrisTerBeke** [athombv/apps-sdk-issues#356]
Hi,

I'm running into an issue where I want to mark a device as unavailable by default when the device is initialized, and only set it to available after confirming over the network that the device is indeed alive (it's a client-initiated heartbeat setup over WebSockets). When I try to call `this.setUnavailable` inside `onInit`, the device is not marked as unavailable. When I add a brief timeout and then call `this.setUnavailable`, it works fine.

Example code:

```typescript
async onInit(): Promise<void> {
    // does not work
    this.setUnavailable('Waiting for charging station to connect')
    // works!
    setTimeout(() => { this.setUnavailable('Waiting for charging station to connect') }, 500)
}
```

> Note that I'm also working with auto discovery, but I cannot get the needed behavior via `onDiscoveryAvailable`.

The entire codebase of my app (in early development) can be found here: https://github.com/ChrisTerBeke/homey-ocpp.

Running on Homey Pro 2023, version 12.0.0

**Comment by jeroenwienk** [comment]
> Hi,
> 
> I'm running into an issue where I want to mark a device as unavailable by default when the device is initialized, and only set it to available after confirming over the network that the device is indeed alive (it's a client-initiated heartbeat setup over WebSockets). When I try to call `this.setUnavailable` inside `onInit`, the device is not marked as unavailable. When I add a brief timeout and then call `this.setUnavailable`, it works fine.
> 
> Example code:
> 
> ```ts
> async onInit(): Promise<void> {
>     // does not work
>     this.setUnavailable('Waiting for charging station to connect')
>     // works!
>     setTimeout(() => { this.setUnavailable('Waiting for charging station to connect') }, 500)
> }
> ```
> 
> > Note that I'm also working with auto discovery, but I cannot get the needed behavior via `onDiscoveryAvailable`.
> 
> The entire codebase of my app (in early development) can be found here: https://github.com/ChrisTerBeke/homey-ocpp.
> 
> Running on Homey Pro 2023, version 12.0.0

It's an async method you should await it.

```await this.setUnavailable('Waiting for charging station to connect')```
