### ISSUE TITLE
Device with 4 onoff capabilities can be toggled, but that does not make sense

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/apps-sdk-issues#36]
I have a device with multiple onoff capabilities: onoff.opt1, onoff.opt2, etc.

That device is also toggle-able from the device-tile. That does not make sense and I would like to turn that off with a setting when pairing. How can I do that?

**Comment by WeeJeWel** [comment]
You cannot. I advice to use a custom capability instead of onoff.
