### ISSUE TITLE
[GitHub Actions][Publish] Make `changelog` optional

### ISSUE THREAD

**Issue by OlivierZal** [athombv/apps-sdk-issues#360]
With CLI changelog is not requested while publishing a new version if there's already a changelog for the version to publish. 

This is the only way to have a changelog in multiple languages, since the CLI dialog requests it only in English. 

That's why it would be great to have the same behavior for the corresponding GitHub action. 

Kind regards

**Comment by WeeJeWel** [comment]
Fixed
