### ISSUE TITLE
Capability set to non-settable still gets action card, which always errors out

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#363]
I have configured `thermostat_mode` as follows:
```
"capabilitiesOptions": {
  "thermostat_mode" : {
    "getable" : true,
    "setable" : false
  }
}
```

However, making the capability non-settable doesn't prevent an action card for it being generated that allows setting. The card always fails though, because "Capability Not Setable" 🤦🏼‍♂️

![image](https://github.com/user-attachments/assets/2fdcfdb9-4657-4ca0-9562-416d5e722918)

Is there a way to prevent this card from being offered to the user?

As an aside: the correct spelling of the word is "settable".

**Comment by robertklep** [comment]
Bump.

**Comment by jeroenwienk** [comment]
> I have configured `thermostat_mode` as follows:
> 
> ```
> "capabilitiesOptions": {
>   "thermostat_mode" : {
>     "getable" : true,
>     "setable" : false
>   }
> }
> ```
> 
> However, making the capability non-settable doesn't prevent an action card for it being generated that allows setting. The card always fails though, because "Capability Not Setable" 🤦🏼‍♂️
> 
> ![image](https://private-user-images.githubusercontent.com/1190916/368529650-2fdcfdb9-4657-4ca0-9562-416d5e722918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODc5MjYsIm5iZiI6MTcyOTA4NzYyNiwicGF0aCI6Ii8xMTkwOTE2LzM2ODUyOTY1MC0yZmRjZmRiOS00NjU3LTRjYTAtOTU2Mi00MTZkNWU3MjI5MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMTQwNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I3OTEwYjllODRmYjZhNWM5M2Q1NDg0NDU3NTJiZDVmYWJjNjdiNTIwN2MyODEyZTgwZTFmZGZlNjJkNzI1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CNrOLDgql64_z-JKnPb5k87hkRJqfTpCUoJwDPD-pTE)
> 
> Is there a way to prevent this card from being offered to the user?
> 
> As an aside: the correct spelling of the word is "settable".

No that's not possible. Wondering the use case here why use thermostat capability if it's not setable?

**Comment by robertklep** [comment]
As a read-only (status) indicator.
