### ISSUE TITLE
race condition on api.js flow triggers

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#38]
Api.js endpoints are available before all flow triggers are initialized resulting in crashes during app install process when api's are called from automated processes, but flow triggers are not available yet, while flow triggers are registered on app init.
I receive these crashes since Homey V2.0 from time to time soon after publised app updates.

```
A crash occurred for your app (version 2.0.5) at Jan 16, 2019 11:17 AM (UTC).

Homey software version: 2.0.0

Crash report:

    /api.js:73
      Homey.ManagerFlow.getCard('trigger', 'http_get').trigger(
                                                       ^

TypeError: Homey.ManagerFlow.getCard(...).trigger is not a function
    at Object.fn (/api.js:73:56)
    at ManagerApi._onRest (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/api.js:1:720)
```

**Comment by WeeJeWel** [comment]
You should use the reference you got, e.g.

```
Homey.app.myTrigger = new Homey.FlowCardTrigger().register();
```

```
const myTrigger = await Homey.app.myTrigger;
myTrigger.trigger(...);
```

**Comment by irritanterik** [comment]
Thanks, this improves error handling and prevents app crashing, but race conditions still apply. If the api is called before the register process is ready the api returns error 500. 
Could be solved by explicitly init api.js from app.js
