### ISSUE TITLE
Homey.Device.setSettings() not assigning setting.

### ISSUE THREAD

**Issue by hive** [athombv/apps-sdk-issues#4]
Using the code from the documentation 

With in the app.json 

```

{
    "id": "text1",
    "type": "text",
    "label": {
        "en": "Text label 1"
    },
    "value": "Text value 1",
    "hint": {
        "en": "If needed, add an additional description to explain this setting."
    }
},

```
Works correctly, displays 'Text value 1' as the **device** setting.

Once again from the documentation : device.js

```
async onInit() {
        let settings = await this.getSettings();
        this.setSettings({
            text1: "newValue",
            // only provide keys for the settings you want to change
        });
    }
```

**Expected** : text1 setting to be updated to "newValue"
**Experienced** : Setting retained its original value.

**Comment by Maxmudjon** [comment]
some problem

**Comment by hive** [comment]
Thank god, I thought It was just me and I was loosing my mind. 

:-)

**Comment by Maxmudjon** [comment]
@hive please open topic here https://community.athom.com/c/developers

**Comment by WeeJeWel** [comment]
Fixed in 2.0.0-rc.4

**Comment by peterjohnsson** [comment]
Would be nice to use settings..

**Comment by alcsverige** [comment]
Settings doesn't work.. 2.0 Rc8.
App v2.0.208

**Comment by PeetersJan** [comment]
Does not work in RC9...

**Comment by PeetersJan** [comment]
RC13, still no cigar...  
App v2.0.208

**Comment by WeeJeWel** [comment]
I tested this and it works here. Could you elaborate what doesn't work exactly?
