### ISSUE TITLE
suggestion: show device store & settings on https://developer.athom.com/tools/devices

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#41]
showing actual content of the device store and device settings on https://developer.athom.com/tools/devices would help me develop and debug apps faster.

**Comment by WeeJeWel** [comment]
I've added `Settings` to a device. Store is not returned using the Web API because it can contain sensitive information such as OAuth2 access tokens etc.

**Comment by irritanterik** [comment]
Thanks!
