### ISSUE TITLE
checkbox on settings screen looks disabled when unselected

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#43]
I had some questions about this checkbox on the app settings screen regarding its actual state.
It looks disabled when unselected. 
![image](https://user-images.githubusercontent.com/15232724/51532180-c77ad680-1e3f-11e9-8798-d9f2b32d4823.png)

**Comment by daneedk** [comment]
I've solved this by using sliding switches:

![image](https://user-images.githubusercontent.com/16610696/51751881-47aa7180-20b6-11e9-9ab9-2eab1b23ed93.png)

html:
https://github.com/daneedk/com.uc.heimdall/blob/26b2a423a00285e7acfe5b8053a031225ea60e3b/settings/index.html#L138

css:
https://github.com/daneedk/com.uc.heimdall/blob/26b2a423a00285e7acfe5b8053a031225ea60e3b/settings/styles.css#L481

**Comment by WeeJeWel** [comment]
Using switches for checkbox items is a better idea. The checkmark symbol is mainly used in lists within Homey.
