### ISSUE TITLE
Device as argument crashes

### ISSUE THREAD

**Issue by StefanIndustries** [athombv/apps-sdk-issues#44]
https://community.athom.com/t/device-as-argument-in-flows-broken-on-homey-2-0/7009
Using device as argument in flow actions/conditions is crashes app on Homey v2.
```
  {
    "id": "create_zone_with",
    "title": {
      "en": "Create zone with",
      "nl": "Maak zone met"
    },
    "fluidArgs": true,
    "args":[
      {
        "name": "device",
        "type": "device",
        "filter": "driver_id=soundtouch"
      },
      {
        "name": "slave",
        "type": "device",
        "placeholder": {
          "en": "Soundtouch device",
          "nl": "Soundtouch apparaat"
        },
        "filter": "driver_id=soundtouch"
      }
    ]
  }
```

Homey app crashes when trying to pick a device from the device list.
This was working on Homey 1.5.3 (and still is)

**Comment by Christian-Athom** [comment]
Hi,

i tried to reproduce your problem but was unable to do so.

Is is possible that you can invite me to your Homey so i can diagnose this problem?

Greetings,
Christian

**Comment by StefanIndustries** [comment]
Yes that certainly is possible. How would you prefer to get in contact?

**Comment by Christian-Athom** [comment]
Hi, you can send the invite to christian - at - athom.nl. Also please add the name of the the specific device in question

**Comment by Christian-Athom** [comment]
Hi, 
i have located the problem, and this will be fixed in a upcoming version of the Homey app.
Thank you for helping us diagnose this problem, i have removed myself from your Homey.

Greetings,
Christian

**Comment by StefanIndustries** [comment]
The app no longer crashes, but I was using the complete device argument that was passed in. I was able to use the args.slave.getSettings() for example, this is no longer possible since only the icon and name of the device are passed on as argument. Is this intentional?
