### ISSUE TITLE
Capability automatically creates flowcards

### ISSUE THREAD

**Issue by daneedk** [athombv/apps-sdk-issues#45]
In Homey 2.0 having a certain capability (in this case homealarm_state) automatically creates flow cards. Is there a way to prevent the automatically creation of flow cards?

I ask this because there are undesired flow cards for the  **Surveillance Mode Switch** in **Heimdall**. This is undesired because **Heimdall** has the option to delay the arming so a user has time to leave the house for example. I've added flow cards that represent the actual **Surveillance Mode** but it's confusing for users because of the automatically created cards that show the wrong state and don't work as expected.

**Comment by WeeJeWel** [comment]
This is intended behavior and generally shouldn't be changed.

However, you can create a capability with the same ID and properties, and the Flow cards will disappear.

**Comment by daneedk** [comment]
Great, that works!

For future reference or anyone else who needs this:

Go to https://developer.athom.com/docs/apps-reference 
and click on the dots behind the required capability to see the full capability configuration.
