### ISSUE TITLE
Overriding device `onSettings` always shows an error

### ISSUE THREAD

**Issue by nlrb** [athombv/apps-sdk-issues#47]
For security reasons, the Visonic alarm panel app only allows changes to device settings to users that know the panels installer pin code.
The way this was achieved in the past (before v2), was to add a pin code (password) field in the device settings and check this before updating the settings. By overriding `onSettings`, this enabled to save all fields -except the pin code!- when the code was OK or not save any setting when the code was wrong.
However, in the new API implementation there is always an error shown to the user. So now even when the pin code is OK and we save all the settings (programmatically), the user gets an 'unknown error': ![](https://user-images.githubusercontent.com/1661824/51635793-ea001300-1f57-11e9-958e-9cdb186311a6.PNG)

Please enable that one can override `onSettings`, without generating a user error.
Possible solutions:
- add an option in the JSON for a 'read-only' field (a field that is not saved in the settings)
- make sure no error is displayed to the user in case of an empty string or null

**Comment by WeeJeWel** [comment]
Are you saving settings programmatically in `onSettings`? That's not supported and might trigger your error.

**Comment by nlrb** [comment]
No, that doesn't trigger the error - that would give another error (something like 'cannot update the settings while....'). The settings are updated after the callback.

**Comment by Brendvm** [comment]
@WeeJewel, any news on this issue? Waiting on submitter isn't the correct status anymore. Kind regards!

**Comment by WeeJeWel** [comment]
@nlrb Could you provide me with a small reproducible example that triggers the same problem? I really have no clue how you implemented this hack.

Settings are really not meant to be not saved.

**Comment by WeeJeWel** [comment]
Closed due to inactivity.

**Comment by nlrb** [comment]
Wow, first you call my implementation a hack and then you close the issue as I did not create separate example code within 7 days... Why do I even put effort into Homey apps?

**Comment by Javiast** [comment]
@WeeJeWel could you please reopen this ticket to allow nlrb to create the example you have requested?
Thanks in advance

**Comment by WeeJeWel** [comment]
When a reproducible example has been provided I will re-open the issue of course.

**Comment by rhannink** [comment]
Hallo,

Can we please re-open this Problem? I really need the Visonic app.

I guess @nlrb has to provide Some Example code?

**Comment by Brendvm** [comment]
Please reopen @WeejeWel and give @nlrb some more time. There are people who really need the visonic app and has allot of flows depending on it.

**Comment by nlrb** [comment]
Attached requested reproducible example and screenshot behavior on 1.5.13 and 2.0.x.
[silly_demo.zip](https://github.com/athombv/homey-apps-sdk-issues/files/2958552/silly_demo.zip)
![Device_save_v1_vs_v2](https://user-images.githubusercontent.com/11725674/54231561-073d7080-4509-11e9-992a-c5e0c258679c.jpg)

**Comment by WeeJeWel** [comment]
I've inspected your example (thanks for that!). You are returning an error in the onSettings method, which shows the error to the user. This behavior will not change because it's correct.

If you want to do it anyway I suggest you remove the PIN in a `process.nextTick` using `Device.setSettings({ pin: '' })`
