### ISSUE TITLE
Disable tag input in text argument

### ISSUE THREAD

**Issue by SailingDuck** [athombv/apps-sdk-issues#48]
Since 2.0 several people tried to add tags in one of the cards of Better Logic.  Unfortunately this does not give me the tagnames but the values. So there's no way to see what tags where used. Is it possible to disable the tag selector with an option? 

Issues where this happened:
- https://github.com/PatrickSannes/BetterLogic/issues/36
- https://github.com/PatrickSannes/BetterLogic/issues/32
- https://community.athom.com/t/app-better-logic-variable-management-v1-0-0/5568/39

Can expand the hint but would be nice if the interface could be made a bit more intuitive by not offering this possiblity.

**Comment by WeeJeWel** [comment]
I see your problem but it's not something we want to fix by hiding the tag field. That would only make it less consistent and therefore more confusing.

You could try to find a way by using an `autocomplete` field.
