### ISSUE TITLE
FlowCardTriggerDevice not triggering in app

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#5]
On 2.0.0-rc-2 all the `FlowCardTriggerDevice` trigger cards won't trigger. The object don't throw an exception and the promise resolved like it should except that the flow not is triggered.

**Comment by twendt** [comment]
I was just opening the same issue. So I will respond here now.

I created a Homematic app which uses FlowCardTriggerDevice in several drivers. This worked fine on v.15, but since the experimental update to v2 flows do not trigger anymore.

An example can be found here:
https://github.com/twendt/homey-matic/blob/master/drivers/HM-PB-4-WM/driver.js

**Comment by koktaildotcom** [comment]
Moving the `FlowCardTriggerDevice` `register` function from the device to the app didn't result in a working trigger.

**Comment by TedTolboom** [comment]
I'm running into the same issue(s): but some fail and some don't

Example of the failing triggers; the runListener is never activated (when adding log to it)
device.js trigger: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/cube/device.js#L193
flowcard definition in device.js: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/cube/device.js#L112

On the other hand, I do have some working scene triggers:
device.js trigger: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/remote.b1acn01/device.js#L77
flowcard definition in app.js: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/app.js#L11

**Comment by TedTolboom** [comment]
@WeeJeWel Did some testing in my favorite app (Xiaomi Zigbee)

```
vibration sensor
sensorMotionTriggerDevice	not working (+ test working)
+ manual trigger
+ tokens
- runListener

tiltReferenceTriggerDevice		not working (+ test not working)
+ manual trigger
+ tokens
- runListener

tiltDeltaTriggerDevice		not working (+ test not working)
+ manual trigger
+ tokens
- runListener

alarm_tiltTrueTriggerDevice	not working (+ test working)
+ capability trigger
- tokens
- runListener

alarm_tiltFalseTriggerDevice	not working (+ test working)
+ capability trigger
- tokens
- runListener

Aqara wireless switch
Homey.app.triggerButton1_scene	working (+ test working, + runListener working)
+ manual trigger
+ getArgument
+ registerAutocompleteListener
- tokens
+ runListener

this.triggerButton1_button		not working (+ test working)
+ manual trigger
+ tokens
- runListener
```
Note that the `Homey.app.triggerButton1_scene` was the only one working yesterday also.
Today I tested it again, but didn't work... Several PTP's and RROD's further and all of the sudden this trigger is working again.

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.4. Thank you @TedTolboom for testing so thoroughly!

**Comment by TedTolboom** [comment]
Nice, would be happy to test rc.4!

**Comment by koktaildotcom** [comment]
Confirmed in rc-4

```
Successful triggered flow card sensor_changed global.
Successful triggered flow card sensor_changed.
Successful triggered flow card globalSensorOutsideThreshold.
Successful triggered flow card deviceSensorOutsideThreshold.
Successful triggered flow card globalSensorThresholdMaxExceeds.
Successful triggered flow card deviceSensorThresholdMaxExceeds.
Successful triggered flow card sensor_changed.
Successful triggered flow card sensor_changed global.
Successful triggered flow card sensor_changed global.
Successful triggered flow card sensor_changed.
Successful triggered flow card globalSensorOutsideThreshold.
Successful triggered flow card deviceSensorOutsideThreshold.
Successful triggered flow card globalSensorThresholdMaxExceeds.
Successful triggered flow card deviceSensorThresholdMaxExceeds.
Successful triggered flow card sensor_changed.
Successful triggered flow card sensor_changed global.
Successful triggered flow card sensor_changed global.
Successful triggered flow card sensor_changed.
Successful triggered flow card globalSensorOutsideThreshold.
Successful triggered flow card deviceSensorOutsideThreshold.
Successful triggered flow card globalSensorThresholdMaxExceeds.
Successful triggered flow card deviceSensorThresholdMaxExceeds.
Successful triggered flow card sensor_changed global.
Successful triggered flow card globalSensorOutsideThreshold.
Successful triggered flow card globalSensorThresholdMaxExceeds.
Successful triggered flow card sensor_changed.
Successful triggered flow card sensor_changed.
Successful triggered flow card sensor_changed global.
Successful triggered flow card deviceSensorOutsideThreshold.
Successful triggered flow card deviceSensorThresholdMaxExceeds.
```
