### ISSUE TITLE
set_volume/dimmer slider in V2 interface goes to 0 or 100% when - or + is pressed

### ISSUE THREAD

**Issue by abaretta** [athombv/apps-sdk-issues#51]
In the mobile interface the set_volume slider has a speaker with a '-' and a '+' sign on the bottom and the top of the slider. This suggests volume_up / volume_down will be called when pressing the '+' or '-' sign. This is not the case, the volume either directly goes to '0' or, and this can be problematic in case of an amplifier, directly to 100%!

The dimmer for lights has the same behavior, however in that case there's no '-' or '+' sign, and with a light it is less of a problem.
![volume-edited](https://user-images.githubusercontent.com/25007256/52518719-6fb9d900-2c4f-11e9-9550-930f4f338497.png)

**Comment by WeeJeWel** [comment]
This is actually intended behavior to min/max the slider. I'll see internally if we can find a better icon.
