### ISSUE TITLE
Suggestion: do news ticker effect on longer string capabillity values 

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#52]
There is little space for string type capabillities. 
Will you consider to show strings that do not fit the value space with a news ticker effect?

Example issue: adress as a capabillity:
![image](https://user-images.githubusercontent.com/15232724/52520732-4740d780-2c6d-11e9-9a60-6bddb2069daa.png)

**Comment by WeeJeWel** [comment]
Thanks for the suggestion. It's been noted internally!
