### ISSUE TITLE
HomeyAPI.ManagerDevices.Device.CapabilityInstance setValue() triggers listeners function

### ISSUE THREAD

**Issue by specialcircumstances** [athombv/apps-sdk-issues#54]
SDKv2. Latest stable Homey.

Documentation indicates:

listener | function | A function to invoke when the capability is changed by anything other than the returned capabilityInstance

When I use the setValue() method of the returned capabilityInstance the listener function is triggered.

Creation of instance:
```
device['cInst']['target_temperature'] = device.makeCapabilityInstance('target_temperature', function(device) {
                this.stateChange(device);
            }.bind(this, device));
```

Trigger of method:

`await thisDevice.cInst.target_temperature.setValue(targetTemp);
`

Result is that "stateChange(device)" is triggered.

**Comment by WeeJeWel** [comment]
Please re-create this issue here: https://github.com/athombv/homey-web-api-issues/issues
