### ISSUE TITLE
[Z-wave core] Add ability for add S2 DSK keys to bring Homey security level on par for S2

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#57]
Currently, Homey Z-wave core does not support to add the S2 Device Specific Key (DSK) to bring Z-wave security to the S2 specifications.

> The S2 security enhances Z-Wave Plus with an additional layer of AES 128-bit encryption of the wireless Z-Wave communication in order to prevent hacking and man-in-middle attacks of the home network. The Heatit Z-Relay supports S2 and has a QR-code label that can be used when the module is included into the Z-Wave home network. The including Controller will ask for a 5-digit code, which can be identified beneath the QR-code, and will then ask to confirm the rest of the code that is contained in the QR-code.

Please add the option to request the DSK key from the user to the Z-wave inclusion process.

**Comment by WeeJeWel** [comment]
Thanks for the suggestion. As we do not track feature requests in this tracker I will now close this issue.
