### ISSUE TITLE
Add option to override uiQuickAction of default capability

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#58]
Please add an option to override the uiQuickAction of a default capability to the generic capabilityOptions available for all capabilities.

There is no option (working) to override the uiQuickAction available to the developer

**Comment by hive** [comment]
I too would find this really useful, 

it would allow us to no longer need to create custom capabilities and would give us more control of which capability should have the uiQuickAction.

**Comment by WeeJeWel** [comment]
Could you provide some examples when this would be really useful?

**Comment by hive** [comment]
I created an app which contained 6 buttons, each on related to an action on an Alexa device. - Say the weather, tell me my daily travel time, whats my news briefing, stop, etc. 

Rather the being able to just define that either 'stop' should be the default action or in the end I decided that there should be no default action.   I had to create custom capabilities for all buttons.

I am also considering how a dynamic group might work which has multiple capabilities which 'could' be the default action. 

Honestly I just expected to be able to change the value using uiQuickAction: false, it was also what several people suggest on slack when I was unable to get it to work.

**Comment by WeeJeWel** [comment]
> I created an app which contained 6 buttons, each on related to an action on an Alexa device. - Say the weather, tell me my daily travel time, whats my news briefing, stop, etc.
> 
> Rather the being able to just define that either 'stop' should be the default action or in the end I decided that there should be no default action. I had to create custom capabilities for all buttons.
> 
> I am also considering how a dynamic group might work which has multiple capabilities which 'could' be the default action.
> 
> Honestly I just expected to be able to change the value using uiQuickAction: false, it was also what several people suggest on slack when I was unable to get it to work.

This is not a use case we will support because it's _very_ custom.

**Comment by WeeJeWel** [comment]
Closed due to inactivity.
