### ISSUE TITLE
Device with multiple onoff capabilities toggles device state representation in the app incorrectly

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#59]
Currently, with a Zigbee device that has two `onoff` capabilities (Zigbee does not support multiChannelNodes), the state of the device (in the app) is toggled based on the state of one of the capabilities; which is incorrect.

The deivce state change in the Homey app should not change when multiple `onoff` capabilities are present. Or the developer should get the option to disable this state representation.

**Comment by WeeJeWel** [comment]
What are the exact capability ID's you're using?

**Comment by TedTolboom** [comment]
I'm using `onoff` and `onoff.1`

**Comment by TedTolboom** [comment]
See e.g. https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/config/drivers/ctrl_neutral2.json

**Comment by WeeJeWel** [comment]
This is not something we'll change anytime soon. You can use a custom capability, or create two devices if it's a dual-switch, for example.
