### ISSUE TITLE
App settings screen is flickering because page is shown before Homey.ready()

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#61]
Homey v 2.0.2

I'm hiding settings page elements (like Bootstrap alert warnings) in the `function onHomeyReady( Homey ){` function before calling `Homey.ready();`. 
Docs say :
> The settings view will be hidden until this method has been called. Use the extra time to make required API calls to prevent flickering on screen.

But I'm getting a lot of flickering (once for the homey.js loading which change font sizes, once with elements visable and final layout.

**Comment by WeeJeWel** [comment]
You are right. This has been fixed on developer.athom.com.

@Christian-Athom Please also fix this in the Homey app.

**Comment by Christian-Athom** [comment]
This issue was fixed in mobile app version 2.1.2
