### ISSUE TITLE
Button-bar still visible even without buttons

### ISSUE THREAD

**Issue by FricoRico** [athombv/apps-sdk-issues#62]
I'm having a long page with instructional content during my device pairing. However, although I don't use the default `nav` buttons, the bar is still visible and taking up precious screen space. See the screenshot for a better explanation.

![image](https://user-images.githubusercontent.com/1057823/52978808-2138d700-33d3-11e9-9fe3-39d6ee5b217c.png)

**Comment by WeeJeWel** [comment]
This is intended behavior. If we wouldn't do this, content would jump around during transitioning between views.

**Comment by FricoRico** [comment]
I see, but can I at least bind my own functions to the buttons in the button bar then? Couldn't find this in the documentation
