### ISSUE TITLE
no Icon for SDK App is shown

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/apps-sdk-issues#63]
When a custom svg item is used, it is not displayed as App icon. Both on iOS and Android it show an empty dot instead of the Item.
When used an "existing" Icon (e.g. Kodi, Log app) it works fine, but as soon as something changes (e.g. remove one square form the kodi logo) it refuses to work.

Allready contacted you for a custom icon over here: https://github.com/athombv/homey-vectors-public/issues/52
but this then made icon also doesn't work.

As requested over at this topic: https://github.com/athombv/homey-vectors-public/issues/51
opened a Issue over here as it seems this has nothing to do with the Icon itself.

For your Info:
Using Homey Firmware 2.0.2
App Version iOS: 2.0.8.257
Android Version: 2.0.8

Screenshots to capture the Issue:
iOS:
![img_0011](https://user-images.githubusercontent.com/28244954/53086790-10d54900-3506-11e9-92df-8ea288875324.jpg)

Android:
![bildschirmfoto 2019-02-20 um 11 42 00](https://user-images.githubusercontent.com/28244954/53086740-f7cc9800-3505-11e9-933f-4f92a0b1c956.png)

**Comment by abaretta** [comment]
Same issue with svg icons for capabilities. Custom icons that were added earlier work, newly added icons (even 'known good' icons) do not display, instead a rotating ('loading') icon is displayed (see screenshot below). 

![image](https://user-images.githubusercontent.com/25007256/53087475-90174c80-3507-11e9-8c3a-23ff499c369a.png)

**Comment by ricott** [comment]
Same problem for me, my icons only displays on the add device list screen on iOS. On all other screens icons are missing (except for device detail page where the loading spinner is shown).

**Comment by WeeJeWel** [comment]
Could you attach the svg's to this issue please?

**Comment by abaretta** [comment]
Hi Emile,

I have attached a zipfile with the icons. The icon sunriseGH.svg has been checked/edited by Ivo Derksen and should work (but doesn't). I have also included Real-tux_mono.svg which is another 'known-good' icon which does not work when added to the app. 

Note that other custom icons that were added to the app before V2 do work, for instance clouds.svg. I have also included wind_angle.svg, this icon displays in the iPhone app, but not in the Android app.

Homey v2.0.4, iPhone app 2.0.8.257, Android app 2.0.6.250.

[icons.zip](https://github.com/athombv/homey-apps-sdk-issues/files/2902173/icons.zip)

I hope this helps 👍

**Comment by ricott** [comment]
This icon in Tesla app doesn't display, shows a loading spinner
https://github.com/irritanterik/homey-tesla.com/blob/master/drivers/ev/assets/distance.svg

**Comment by ricott** [comment]
In my local app that I'm developing the attached icon displays on list devices screen (when listing devices to add them), but not on device tab (after they are added).
[icon.svg.zip](https://github.com/athombv/homey-apps-sdk-issues/files/2902659/icon.svg.zip)

**Comment by carp3-noctem** [comment]
Ok, my Icon was allready added from @ricott , thanks for that. 
BTW: Releasing the App on Alpha Channel also doesn't show the Icon for the App.

**Comment by PeterEIER** [comment]
Same issue for me, attached icon will only show in the "Select the devices you..." dialog during paring.

[icon.svg.zip](https://github.com/athombv/homey-apps-sdk-issues/files/2907556/icon.svg.zip)

![img_0672 2](https://user-images.githubusercontent.com/25422313/53446990-78aef680-3a14-11e9-8075-a8510bac273c.jpg)

![img_0671](https://user-images.githubusercontent.com/25422313/53446998-7d73aa80-3a14-11e9-8b2a-4decf5cc6660.jpg)

**Comment by AdyRock** [comment]
I have the same issue. Spent hours trying different editors. The icons appear in the select devices screen during pairing but not on the tile once added.
Also general app icon is not displayed after I replaced the default one with my own. The icons display fine in all other editors I have tried (4 now) and in IE and Chrome.

**Comment by carp3-noctem** [comment]
I just found, that the icon is correctly displayed in the Simulator Icon. Just for your Info

**Comment by irritanterik** [comment]
> This icon in Tesla app doesn't display, shows a loading spinner
> https://github.com/irritanterik/homey-tesla.com/blob/master/drivers/ev/assets/distance.svg

Strange, icon is ok on my cli installed version

**Comment by irritanterik** [comment]
Ok, I have the same issue now on 2.0.4. When adding new icons to an app, like for capabillities, these are not shown in the (android) app.

**Comment by WeeJeWel** [comment]
Thanks guys, we can reproduce the issue and @Christian-Athom will look into it.

**Comment by WeeJeWel** [comment]
This issue has been resolved and should work immediately.
