### ISSUE TITLE
Some capabilities do not have flow triggers

### ISSUE THREAD

**Issue by FricoRico** [athombv/apps-sdk-issues#65]
Some capabilities such as `volume_up` and `volume_down` do not have the flow triggers as `onoff` or `volume_set` capabilities do.

For example:
`onoff` has `Turned on` and `Turned off` triggers by default.

Triggers I'm specifically missing:
- volume_up
- volume_down
- volume_mute
- channel_up
- channel_down

**Comment by WeeJeWel** [comment]
These are capabilities that can only be set, so the device cannot report that these have changed. That's why they do not have a trigger.

**Comment by FricoRico** [comment]
Same could be set about `onoff` and `volume_set` without custom reporting back both of these features are fire and forget.

Or are you referring to the visual feedback inside the app? Where volume sliders show an X value and power button has a state?

**Comment by WeeJeWel** [comment]
Yes, the latter.
