### ISSUE TITLE
Download file (generated Log) from Settings in mobile App 

### ISSUE THREAD

**Issue by Dijker** [athombv/apps-sdk-issues#66]
Apps like Papertrails or Simple Log want to provide a download of the Logs.

This is done using a client-side in memory generated log that users where able to download from the settings.

Something like in both the Apps or as seen here: 
- http://danml.com/download.html
- https://ourcodeworld.com/articles/read/189/how-to-create-a-file-and-generate-a-download-with-javascript-in-the-browser-without-a-server 
- https://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server (2nd answer)

From https://developer.athom.com/tools/app-settings it works but from the mobile Android App it crashes the app. (without that we can see what happens) 

Please help us by fixing this in the App or show a good download example code for the settings html page so we don't have to let users who want to download be redirected to the Dev. Tools.

**Comment by Christian-Athom** [comment]
Hi,

unfortunately at the moment it is not possible to support this functionality. 
The mobile Android application crashes because there is no support for the data: url's see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

Greetings,
Christian

**Comment by WeeJeWel** [comment]
I advice you to create a Web API application so users can visit it in their browser.
