### ISSUE TITLE
Device warnings are not implemented in front-end

### ISSUE THREAD

**Issue by FricoRico** [athombv/apps-sdk-issues#67]
The `setWarning` SDK function does not actually trigger a warning in the front-end. This is the documentation for the function: https://apps.developer.athom.com/Device.html#setWarning

My application heavily relies on authorization with the device, so upon authentication failure (when user changes pre-shared key in settings), I have no way to notify the user.

**Comment by WeeJeWel** [comment]
You should use setUnavailable in this case — the user will still be able to change the device's settings.
