### ISSUE TITLE
iOS keyboard push on input fields contain render issues

### ISSUE THREAD

**Issue by FricoRico** [athombv/apps-sdk-issues#70]
When implementing the `login_credentials` pairing template, as [shown here](https://apps.developer.athom.com/tutorial-Drivers-Pairing-System%20Views-Credentials%20Login.html), a black bar is visible on the bottom of the page.

I experience the same issues with my custom templates and this only occurs on iOS devices. Both Android and developer pairing simulator work fine. Tested on iPhone X.

**Comment by FricoRico** [comment]
![brokenlogin](https://user-images.githubusercontent.com/1057823/53694870-da74b500-3db4-11e9-9047-accccf8933df.png)

**Comment by Christian-Athom** [comment]
This issue was solved in version Mobile app version 2.1.0
