### ISSUE TITLE
Homey Flow Webeditor - Flowcard Text space gets deleted

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/apps-sdk-issues#72]
Using the Following:
- MacBook Air with Mac OSX 10.14.3
- Mozilla Firefox 65.0.1 (64-Bit)

When Typing Text into a Flowcard using the Format "1|10|Hello World!" the space between Hello & World will be deleted when the "W" is typed.
It is the same when an other Format is used and a space is in the Text. The Issue is not linked to one app, it is in different Apps.

using Safari it is working fine. Due to lag of Chrome i was unable to test it.
If a video would be helpfull to understand, i can make one.

**Comment by WeeJeWel** [comment]
Could you create a screencast of the issue happening?

**Comment by carp3-noctem** [comment]
Done it, you can find the file over here:
https://www.dropbox.com/s/6b4fvy69xfung3v/Homey%20Flow%20Editor.mov?dl=0

**Comment by carp3-noctem** [comment]
@WeeJeWel Any fixes in line of sight?

**Comment by WeeJeWel** [comment]
Yes, this is a known issue but only seems to occur in Firefox so it's not very high-priority.
