### ISSUE TITLE
BLE connection gives an exception:Cannot read property 'startHandle' of undefined #7

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#73]
In process of trying to make the update of the device work the seconds iteration (and all iterations after) i've found another issue.

I've tried to rewrite all the promises to async await to prevent the callback hell in promises.

The issue looks related to: https://github.com/athombv/homey-apps-sdk-issues/issues/11 https://github.com/athombv/homey-apps-sdk-issues/issues/7

```
{ Error: Cannot read property 'startHandle' of undefined
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
  message: 'Cannot read property \'startHandle\' of undefined' }
```

I've commited the code to reproduce in: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-async-await-strategy

**Comment by koktaildotcom** [comment]
1. Checkout: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-async-await-strategy and run the code.
1. Add a new device (or use an existing)
1. Wait until the second iteration kicks in, this is the point the error occur.

**Comment by WeeJeWel** [comment]
Heads-up: This is an error from noble so can take a while to fix.

**Comment by koktaildotcom** [comment]
Thanks for looking into this issue

**Comment by koktaildotcom** [comment]
Did you mean this issue: https://github.com/noble/noble/issues/141? Isn't this related to the issue https://github.com/athombv/homey-apps-sdk-issues/issues/11. It always triggers the second iteration and looks to me that the state of the device cache isn't updated properly or is invalid.

**Comment by Ziglar1** [comment]
@WeeJeWel any chance on a fix ?

**Comment by vWijngaardenR** [comment]
+1

**Comment by koktaildotcom** [comment]
This issue is still not resolved in v2.1.0-rcx.

**Comment by koktaildotcom** [comment]
This issue is still not resolved in v2.1.0.

**Comment by koktaildotcom** [comment]
This issue is still not resolved in v2.1.0.

**Comment by jeroenvano** [comment]
This is still an issue in v2.1.1, when will this be resolved?

**Comment by WeeJeWel** [comment]
Fixed in v2.1.2-rc.4

**Comment by WeeJeWel** [comment]
Note that this error occurs when you have disconnected from a device, and then tries the short-hand method of reading/writing to a characteristic.

After disconnecting a device, you should discover the services & characteristics again using `discoverServices()` respectively `discoverCharacteristics()`.

In Homey v2.1.2-rc.4, an appropriate error is thrown (e.g. `Could not find service with UUID 0000120400001000800000805f9b34fb`).

**Comment by ekouters** [comment]
> After disconnecting a device, you should discover the services & characteristics again using `discoverServices()` respectively `discoverCharacteristics()`.

Worth adding as a note to [BlePeripheral.assertConnected()](https://apps.developer.athom.com/BlePeripheral.html#assertConnected)
