### ISSUE TITLE
App Manifest Doku - Contributors Translator crashes app

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/apps-sdk-issues#75]
In the Dokumentation the Translator Spec is written as:
` "contributors": {
        "translators": [
            {
                "name": "Klemens Kohlmann"
            }
        ]`
but when used it stops the app with the following error during cli handling:
`✖ [
    {
        "keyword": "additionalProperties",
        "dataPath": ".contributors",
        "schemaPath": "#/properties/contributors/additionalProperties",
        "params": {
            "additionalProperty": "translators"
        },
        "message": "should NOT have additional properties"
    }
]
`
This one was discussed at Slack i think, but is was unable to find something related here, so i thought open it would be helpfull. Also due to i would like to use this for my App.

**Comment by WeeJeWel** [comment]
You should update athom-cli :)

**Comment by WeeJeWel** [comment]
I'll publish a version that forces the latest node-homey-lib in a sec.
