### ISSUE TITLE
Subcapability documentation and front-end display is lacking

### ISSUE THREAD

**Issue by DiedB** [athombv/apps-sdk-issues#76]
https://apps.developer.athom.com/tutorial-Drivers-Capabilities.html mentions: 

> **Using the same capability more than once**
> In certain cases it might occur that a device should use a capability more than once. You can use a sub-capability for this purpose.
> An example would be a device with an outside and inside temperature sensor. Simply append a dot followed by an identifier after the capability string during in your driver, e.g. measure_temperature.inside & measure_temperature.outside.

When using this feature, I receive an `invalid_capability` error. Defining the capability (including its identifier) in app.json does not help either.

**Comment by DiedB** [comment]
Never mind, including it in app.json works, but devices that were added before the app.json change have to be re-added. It would be more clear if the documentation mentions that each subcapability has to be registered in app.json, not just the main capability.

Another problem: there is no way to distinguish different subcapabilities:
![IMG_D9F9F3735137-1](https://user-images.githubusercontent.com/7628001/54652926-1dbf6b00-4ab9-11e9-9671-a25b9d209e5f.jpeg)

**Comment by WeeJeWel** [comment]
You can use `capabilitiesOptions.measure_power.title` to overwrite the title! :) Add this in your app.json or during pairing.
