### ISSUE TITLE
BleManager `discovery` promise won't resolve

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#77]
Since Homey 2.0 the app: beacon exits without exception and without a specific time that the app is running.

This app integrate the basic flows for BLE beacons into Homey. Once the app is installed it will do a discovery of BLE devices, after a short adjustable timeout it wil keep discovering. After each discovery the app compares the found devices with the one paired. If the beacon is not found within the new "discovered list" the beacon is changed in state.

You can add device by adding every public discoverable BLE device. After some time running, the app stops discovering.

Looks like it isn't a memory leak:
![Screenshot_20190321-063404](https://user-images.githubusercontent.com/10741929/54736723-cef2fd80-4bac-11e9-8a97-34af7fbc0272.png)

**Comment by koktaildotcom** [comment]
Looks like the discovery function freezes for a long time

**Comment by koktaildotcom** [comment]
I've investigated the issue. The `discovery` timeout of the BleManager does not result in an timeout exception. Looks like there is something missing.

**Comment by koktaildotcom** [comment]
device 1 is in range
device 2 is not in range

calling BleManager ::find
device 1 result in an Advertisement
device 2 result in an Advertisement (looks like Homey is caching this for a long time)

calling BleManager ::discovery
device 1 result in a Peripheral
device 2 result in that the app is not responding anymore

**Comment by koktaildotcom** [comment]
After some time the BleManager won't respond to the `discovery` anymore. A full reboot is needed to get the BleManager connecting again. See comments above.

**Comment by WeeJeWel** [comment]
Can you post a snippet of code that shows these symptoms?

**Comment by koktaildotcom** [comment]
1. Instal the beacon app
2. Add a generic BLE device
3. Keep the app running for half an hour

Then the BLE connect won't resolve at some time.

**Comment by koktaildotcom** [comment]
I cannot provide a snippet, because it is over time that the app freezes

**Comment by koktaildotcom** [comment]
This issue is still not resolved in v2.1.0.

**Comment by WeeJeWel** [comment]
Fixed in Homey v2.1.2-rc.4

**Comment by koktaildotcom** [comment]
Thanks! What did you find?

**Comment by WeeJeWel** [comment]
A 🐛
