### ISSUE TITLE
Update Zigbee to support different alarm sensors

### ISSUE THREAD

**Issue by jwikman** [athombv/apps-sdk-issues#79]
We are still waiting for support for different zigbee alarm sensors. Eg. water alarm, intruder alarm etc.

Please read https://github.com/athombv/homey/issues/2005 (in the now archived repo) for details.

What is the plan for this? We've been waiting on this for quite some time now...

(Btw, why won't you migrate the open issues from https://github.com/athombv/homey/issues/ to this new repo?)

**Comment by jwikman** [comment]
related issues:
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/26
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/27
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/28

**Comment by mauricesundermann** [comment]
Yes, this would be great!

**Comment by mannri** [comment]
+1

Protocol limits and deficiency should really have high priority as it blocks whole rage of products. If anything at least athom could give us rought estimate when this deficiency will be resolved.

**Comment by rutgerpuntnet** [comment]
+1
Come on Athom, the original issue was raised 1,5 year ago. Time for some progress.

**Comment by Danne-J** [comment]
+1 to this.
1,5 years is a long time of waiting

**Comment by merolen** [comment]
This is actually a show stopper for me and I am considering abandoning this platform. It seems a bit half-finished. I admit I bought the Athome Homey without doing a lot of research, I am regretting that now.

**Comment by WeeJeWel** [comment]
We are aware of the zigbee issues and will work on them in the near future. I do not have a timeline to share yet, but when I do I'll definitely share it here.

**Comment by ronald2404** [comment]
HI Athom, is there any news yet? Looking forward for the zigbee rewrite after waiting a very long time....

**Comment by ezwep** [comment]
I am also very curious. I have 7 water leakage sensors connected to a Xiomi Home gateway. But I prefer to connect this to my Homey!

**Comment by korkmazk** [comment]
Same here, any updates from Athom? Would love to add some flood and smoke detectors...

**Comment by guestus** [comment]
Need this too. Will be good to know release date.

**Comment by gizmodok** [comment]
Last time I’ve heard from Athom @WeeJeWel   about een issue regarding the app that they are maintaining ( Fibaro ) and the issues with z-wave I’ve waited 8 months and they were aware of the issue too... I’ve decided to buy different controllers because nobody was doing anything. Like they say it in Dutch slappe zakken.... they just sell the product and the are NOT interested about the issues afterwards.

**Comment by MiteZZ** [comment]
Yeah it is a pitty..  At the moment looking for an other Home Controller, more and more issues are starting to pop up and no 'real' innovative new features. or improvements..

**Comment by WeeJeWel** [comment]
Hey guys, we're aware of these issues and I can assure you our team is working on it very actively!

**Comment by CaspiePi** [comment]
> Hey guys, we're aware of these issues and I can assure you our team is working on it very actively!

Hi Athom, any progress on this zigbee issue? We all look forward to be able to connect our devices to the homey! Still stuck with all these other hubs, because of this. Thank you

**Comment by WeeJeWel** [comment]
There's a lot of progress we hope to release soon :)

**Comment by ludwich** [comment]
@WeeJeWel any better time frame? Alot of us devs have more time now to work on side projects when working remote.

**Comment by RobinBol** [comment]
We are making progress, soon we will contact the current Zigbee Homey App developers for an internal beta period in which they can give us feedback and prepare their apps for the update. I understand it is difficult to keep patient after all this time, but we are getting there!

**Comment by psy0rz** [comment]
btw i love the new widget feature in the homey app. it was something i really missed. :)

**Comment by luuk97h** [comment]
> We are making progress, soon we will contact the current Zigbee Homey App developers for an internal beta period in which they can give us feedback and prepare their apps for the update. I understand it is difficult to keep patient after all this time, but we are getting there!

Any more info on this topic/release date?

**Comment by guestus** [comment]
> internal beta period

Has it started yet?

**Comment by RobinBol** [comment]
Minor update; yes the internal beta started, some selected Zigbee developers are currently working with the new ZIgbee engine. We hope to make this available to the experimental channel in a couple of weeks time.

**Comment by RobinBol** [comment]
The new Zigbee engine is currently released in Experimental and we expect it to be available to all users shortly. As far as we know there is no limitation to implementing various alarm sensors. Therefore, I will close this issue. Thanks for reporting!
