### ISSUE TITLE
A capability with state `null` should be greyed out, not triggering the battery alarm

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#8]
Follow-up of support ticket 9617, which was followed-up in https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/110

The behavior in V2 has been changed; in V1 the battery status with state `null` would show up as greyed out (which does make sense), in V2 it is marked as empty, triggering the alarm (also in homekit)...

See screenshots originating out of the above referenced issue:
> Screenshot 1 is the screenshot of the sensors device, this is the only thing that shows regarding to the battery:
> ![sensors from ap](https://user-images.githubusercontent.com/36899598/49802598-99d54480-fd4d-11e8-9c70-d6d9e60d0e36.jpeg)
> 
> Screenshot 2 shows how this is shown inside HomeKit:
> ![sensors from homekit](https://user-images.githubusercontent.com/36899598/49802631-b2ddf580-fd4d-11e8-9f27-808a4a8698e1.jpeg)

In general, a capability with the state `null` should result in a greyed out capability; 

For battery, the alarm should only be triggered when a battery report is received: state not equal to `null`

Also for other applications, I use this actively with e.g. the thermostats, where some thermostat modes don't support a setpoint and are de-activated by giving it a `null` state

Please make the behavior in V2 similar to V1

**Comment by WeeJeWel** [comment]
The grey battery has been fixed in the newest app release.

I've debugged and the value sent to HomeKit is `false` ...

**Comment by TedTolboom** [comment]
Thanks. Notice the change already in 234
