### ISSUE TITLE
Bluetooth: notification and indication support

### ISSUE THREAD

**Issue by denniedegroot** [athombv/apps-sdk-issues#81]
The Fluxo light sends data back via a indication after a write has been done.
Currently this is not possible in Homey. Can this be implement?

Also see:
https://github.com/noble/noble#characteristic-1

characteristic.subscribe([callback(error)]);
characteristic.on('data', callback(data, isNotification));

**Comment by emilohman** [comment]
[Plejd](https://www.plejd.com/en) (swedish smart light) also send all data back as notifications, so it isn't possible to get state changes back to Homey. 
Do you have any plans for bringing this feature to Homey? If so, whats the current status?

**Comment by denniedegroot** [comment]
I know it's only been 6 months but is there any progress on this?

**Comment by KrakenTyio** [comment]
Many of ble devices communicating by indicators and notifications, for power save reasons.

This is now hard to try workaround.

I see many issues here
- notify command not present
- indicator command not present
- write without response not sure if work
- cannot optain correct descriptor (always stack in command line)
- noble lib not work bc. missing linux lib for communication

Someone could resolve this issues with ble

Thx.

**Comment by Cross-roads** [comment]
>     * write without response not sure if work

Anybody who can confirm this is in fact not possible atm?

**Comment by prfafa** [comment]
So what's going on with this?

**Comment by prfafa** [comment]
@WeeJeWel ?

**Comment by WeeJeWel** [comment]
As usual we cannot say anything about ETAs but adding notification support to the BLE API is on our radar.

**Comment by prfafa** [comment]
@WeeJeWel how can something be "on the radar" for 2 years..? This has been notified to you in different threads since 2018.

**Comment by WeeJeWel** [comment]
It's _on_ our radar ;)

**Comment by prfafa** [comment]
> It's _on_ our radar ;)

lol, sorry, typo. Yeah, _on_ your radar. I mean, seriously, this is pretty much an important implementation feature; so will it be _on_ your radar for another 2 years or what..?

**Comment by WeeJeWel** [comment]
I surely hope shorter than that! :)

**Comment by prfafa** [comment]
..and I guess there's no way in hell you'll announce any form av gossip when this can be released? :)

**Comment by prfafa** [comment]
no @WeeJeWel ? ;)

**Comment by notabene00** [comment]
Happy birthday 🥇 
Any updates on this?

**Comment by mrquincle** [comment]
[Crownstone](https://github.com/crownstone/bluenet) also uses notifications. We truly want to support Homey, see this [plugin](https://github.com/crownstone/crownstone-homey). It's not for a lack of trying.

**Comment by prfafa** [comment]
So @WeeJeWel , soon 2 months. And no update on this? What's going on? Some transparency would be appriciated!

**Comment by denniedegroot** [comment]
I know it's only been 18 months but is there any progress on this?

**Comment by robertklep** [comment]
@denniedegroot my request for support for these (in the currently-closed-or-removed `athombv/homey` repository) is from July 4th 2018. So we passed the 2-year mark a few months ago already 😉

**Comment by shaarkys** [comment]
So happy anniversary to everybody ! ;-) 
But to stay on topic, does anyone knows which kind of devices/functionality this prevent to implement and get supported by Homey ?

**Comment by robertklep** [comment]
@shaarkys notify functionality is used by a lot of sensor devices to push state changes to the controller, so for instance a temperature sensor would notify the controller when the temperature has changed, as opposed to the controller having to poll the device periodically to check what the current temperature is.

**Comment by shaarkys** [comment]
So such fully basic stuff...thank you.

**Comment by joco73** [comment]
@WeeJeWel Any news on this request ( we keep on naging ), I have seen that @mrlukasbos  has been taking some BLE issues - maybe can have a look on this at the same time :-)

**Comment by WeeJeWel** [comment]
Yes, this is on the roadmap for Q2 2021.

**Comment by AdyRock** [comment]
BLE notifications would be great so glad to hear it's on the road map. I am trying to make an app for the Switchbot curtain motors but the only way to get the current position is via notifications, Using them instead of polling is also much better for battery life of the devices as they don't have to constantly wake up to send the same old data over and over. Plus Homey would be a lot more responsive as it gets notified almost straight away instead of having to wait for many seconds in the case of polling.

**Comment by mrlukasbos** [comment]
BLE notifications have arrived in Homey v6.0.0 which is currently available as an experimental release.
