### ISSUE TITLE
Driver showView breaks list_devices flow. 

### ISSUE THREAD

**Issue by hive** [athombv/apps-sdk-issues#82]
I have an application which loads the 'list_devices' template, then if the  app has been authorised, it will gather the devices and then load the 'devices_add' template - This flow works as expected. 

However, the app may not already have been setup with an account. So its important to catch this and then allow the user to login. I have struggled to do this with in the current flow and consequently found this bug.

If the 'list_devices' template calls 'showView' when you return to list_devices, rather then showing the 'next button' a close button is shown and no devices are added.  

In the real world example :  when .on('list_devices'), if there is no established authorisation, it will show the 'login_credentials' template, when the user is authorised - the 'list_devices' will load - showing all of the devices. However rather then showing the `[next]` button which leads to the 'add_devices' template, a `[close]` button is displayed, when clicked - no devices are added. 

Below is the app.json Pair information

```
{
          "id": "list_devices",
          "template": "list_devices",
          "navigation": {
            "next": "add_devices"
          }
        },
        {
          "id": "add_devices",
          "template": "add_devices",
          "navigation": {
            "next": "done"
          }
        },
        {
          "id": "loading",
          "template": "loading"
        },
        {
          "id": "done",
          "template": "done"
        },
        {
          "id": "login_credentials",
          "template": "login_credentials",
          "options":{
            "logo":"../assets/logo.png",
            "usernameLabel": {"en": "E-mail address"},
            "passwordLabel": {"en": "Password"},
            "usernamePlaceholder":{"en": "jamie@email.com"}
          }
        }
```

Current Expected Flow

![image](https://user-images.githubusercontent.com/239140/59740117-749c3280-92aa-11e9-84fd-3ad00854713f.png)

# Fixes 

Fix the bug so that the list_devices flow continues to be correct, after returning from a showView. 

As well as fix bug where a .showView() will not activate with in the onPair (as per documentation)

Thanks

**Comment by hive** [comment]
I was able to use the socket.on('showView') upon the loading template, AFTER force resetting the app. Prior to the force restart the app while triggering the event listener did not show the actual view.

**Comment by WeeJeWel** [comment]
You should start with a view using the ‘loading’ template and move to list_devices from there when the user is authenticated.
