### ISSUE TITLE
Homey.ManagerBLE.discover() gives results with the same advertisement.serviceData all the time

### ISSUE THREAD

**Issue by notabene00** [athombv/apps-sdk-issues#85]
Been asked three months ago.
Here: https://github.com/athombv/homey-apps-sdk-issues/issues/6#issuecomment-482125893
Still not working as expected at Homey 2.5.0 firmware.

**Comment by nklerk** [comment]
Have you provided a service UUID? As for my app the discovery works.

https://github.com/nklerk/nl.nielsdeklerk.XiaomiYeelightCandela/blob/master/drivers/candela/driver.js

**Comment by notabene00** [comment]
@nklerk discovery works. But the same `advertisement.serviceData` every time. Inside of this `serviceData` Mi Hygrothermograph sends temperature, humidity and battery data. They're remain the same between app restarts.

**Comment by nklerk** [comment]
That’s what I see as well. Sorry for misunderstanding.

**Comment by mrlukasbos** [comment]
This issue should have been resolved in Homey v6.0.0 which is currently available as an experimental release.

**Comment by notabene00** [comment]
Can confirm. Almost two years and it's working right now!
