### ISSUE TITLE
Hitting next button on login_credentials template breaks pairing with SQLITE_CONSTRAINT

### ISSUE THREAD

**Issue by jghaanstra** [athombv/apps-sdk-issues#87]
The pairing system view "login_credentials" has two buttons when there is next navigation template defined. A green one with the text "Log In" and a grey one with the text "Next".

When hitting the green button after entering the credentials all is ok but when hitting the next button the pairing wizard breaks and the user is presented with the error "Error: SQLITE_CONTRAINT: NOT NULL constaint failed: Device.name 

Best would be to remove the grey "next" button and leave the green button as the only button, similar to the screenshot of this system template in the documentation.

**Comment by WeeJeWel** [comment]
This sounds like you're calling a `Homey.createDevice({})` somewhere without a `name` property.

The next button can be removed by removing it from the `navigation` object in your app.json's `driver.pair`. The `login_credentials` view will automatically go to the next view when the username & password have been validated.
