### ISSUE TITLE
Missing [[device]] in flow.actions[0].titleFormatted.de

### ISSUE THREAD

**Issue by mapulu** [athombv/apps-sdk-issues#90]
I have to add [[device]] in to titleformatted in all languages except english.
When I add [[device]] into english then I got Invalid [[device]] in flow.actions[0].titleFormatted.en.titleFormatted

[[device]] got translated to an empty string

**Comment by mapulu** [comment]
This was present in athom-cli@2.1.98
and is fixed in athom-cli@2.1.99 ...

**Comment by mapulu** [comment]
No error still appear after Installing the app

**Comment by WeeJeWel** [comment]
This error has been solved and the fix will be included in the next Homey version. Sorry for the inconvenience!
