### ISSUE TITLE
Homey thermostat_mode values not set

### ISSUE THREAD

**Issue by Maxmudjon** [athombv/apps-sdk-issues#92]
`capabilitiesOptions = {
          thermostat_mode: {
            values: [
              {
                id: "auto",
                title: {
                  en: "Automatic"
                }
              },
              {
                id: "heat",
                title: {
                  en: "Heat"
                }
              },
              {
                id: "off",
                title: {
                  en: "Off"
                }
              }
            ]
          },
          target_temperature: {
            min: 5,
            max: 30,
            step: 0.5
          }
        }`

**Comment by WeeJeWel** [comment]
You cannot overwrite the thermostat modes.
