### ISSUE TITLE
Driver.onMapDeviceClass does not wok properly - settings issue

### ISSUE THREAD

**Issue by JirLap** [athombv/apps-sdk-issues#93]
I am working on an app for system with bridge (eQ-3 MAX) and i would like to add all the devices connected to bridge (outside Homey) at once after discovery - like it works in OpenHAB.
But in Homey, I can only "pair" the specific device - in my case the discovered bridge, but it does not matter, I tried extend common driver with no success.

Issue 1: I tried to use Driver.onMapDeviceClass(device) (https://apps.developer.athom.com/Driver.html#onMapDeviceClass) to change the device type during pairing. It change the device itself (OK), but not its driver - device.getDriver() always returns original driver of pairing process, with different capabilities, settings and so.

Issue 2: I tried to set the device property in collecting process for list_devices event:
let device = {
  data: { ..some id data..},
  name: .......,
  icon: .........,
  capabilities:  ......,
  settings: ........ }
It works like a charm for name, icon, capabilities, but not for settings  - it stays always from the pairing device.
I can't find any other way to set the proper settings (in UI, of course, in code I can use anything).
Thanks

**Comment by WeeJeWel** [comment]
You cannot change the driver during or after pairing. So if you really want to add all devices at once, use a single driver.

**Comment by JirLap** [comment]
With different settings?
How?
Thanks.

**Comment by WeeJeWel** [comment]
In that case you should indeed create different drivers.
