### ISSUE TITLE
[com.tado] Flow action do not include tags

### ISSUE THREAD

**Issue by pimviergever** [athombv/apps-sdk-issues#94]
Homey FW: 2.5.2
tado app V.3.0.3

When creating a flow I would like to set the tado thermostat temperature according to a tag (until the SmartSchedule changes).
Now I can only set it to fixed temperatures at steps of 5 degrees Celsius.

Can you change the input to tags and number input?

**Comment by WeeJeWel** [comment]
This issue tracker is meant for developer issues. Please report your problem to Homey Support.
