### ISSUE TITLE
Device class "Garage port"

### ISSUE THREAD

**Issue by nerdtechse** [athombv/apps-sdk-issues#95]
Isnt it time for a device class named "Garage port"?  All apps now uses device class "lock" instead and that wont play well with for example homekit.

**Comment by WeeJeWel** [comment]
Could you give an example how it doesn't work well with Homekit?

**Comment by nerdtechse** [comment]
There is a device class in Homekit just for Garage port. And if the homey is pass it as lock you will miss the graphics of garageport but also the features in Carplay when you arrive at home it puts a button on the car stereo for opening the garageport.

**Comment by bckp** [comment]
Suggest device class gate :-) not sure about homekit implementation... but it is not only about garage, for me, it is about opening fence gate when i get home...

**Comment by tjallingt** [comment]
@nerdtechse are you looking for something that behaves exactly like lock except it should be specifically for a garage door or do you also expect this device class to have different capabilities?

@bckp it seems the goal here is to integrate with carplay, we can make it more generic than "garage door" but then it would also become more confusing to explain how/why it integrates with carplay like that. When we talked on Slack I believe you mentioned that you where looking for something that behaves different from the lock device class, it would be very helpful if you could describe the desired behavior exactly :)

**Comment by bckp** [comment]
@tjallingt my use case is simple, i have gate outside of my house, powered by Nice IBT4ZWAVE device, right now, im using onoff capability for open/close state... but, App says ON/OFF, becouse only windowcoverings, sunshade and 2 more types have filter that change ON/OFF to OPEN/CLOSE. What I want is, if you can add GATE/DOOR/GARAGE as new device class, so other people, when use this have on capability ONOFF proper texts.

Yeah, I can accomplish same result with customCapability, but joke is, that only thing i need to change is texts, all other stuff is working as expected. And I belive for integration with Homekit/Google Home, gate/door is better then other with custom capability.

Btw: in google home, there is device class GATE and device class GARAGE.

**Comment by nerdtechse** [comment]
@tjallingt Carplay is just one thing.. But also its impossible to get the symbols in homekit right for a gate or a port when the only class that is availible in homey is lock..

@bckp Your so right!

**Comment by torarnv** [comment]
Can this issue be closed, based on the fix in https://github.com/athombv/node-homey-lib/pull/247 ?

**Comment by nerdtechse** [comment]
Yes it sure can!
