### ISSUE TITLE
Missing presence flow condition

### ISSUE THREAD

**Issue by lucasvdh** [athombv/apps-sdk-issues#96]
There's currently a flow condition for checking if someone is sleeping. This can also be inverted to check if nobody is sleeping.

## Someone is awake
There is currently no condition to check if someone is awake or if nobody is awake and it would be great if it was added.

### Why?
This condition would take care of a lot of duplicate flows or at least simplify them. For example, I currently have flows to check if person `x` is sleeping and person `y` is not and the other way around.

**Comment by WeeJeWel** [comment]
Thank you for your feature request. This is a developer-only issue tracker for Apps SDK issues.

Please submit your feature request here: https://go.athom.com/request-homey-feature

**Comment by lucasvdh** [comment]
Thanks, didn't know there was a dedicated place for this.
