### ISSUE TITLE
energy.batteries possible value CR14250 is missing

### ISSUE THREAD

**Issue by aartse** [athombv/apps-sdk-issues#97]
app.json device config energy.batteries does not accept the value CR14250.
the zipato device VS-ZD2301.EU has this type of battery according to the manual:
https://doc.eedomus.com/files/vs-zd2301-Zipato-4-in-1-Multisensor-User-Manual-v1.0.pdf

**Comment by WeeJeWel** [comment]
You can use LS14250 for this as they’re interchangeable.

**Comment by WeeJeWel** [comment]
But I've added it regardless. The voltage differs so maybe some devices won't like that :)

https://github.com/athombv/node-homey-lib/commit/877ab0fbefddaa1abf3b1c644a18945ec1e7097b
