### ISSUE TITLE
Removing old custom capabilities

### ISSUE THREAD

**Issue by DiedB** [athombv/apps-sdk-issues#98]
I wrote a small migration script to upgrade old devices to 3.0 for the Solar Panels app and stumbled upon an issue. Each device has two or four custom capabilities currently. I'd like to migrate them towards the built-in `measure_power` and `meter_power` capabilities.

In order to do this, I removed the custom capabilities from `app.json` (they would never be used in the app anymore), and wrote a migration script which changes a device's capabilities on initialization. Within this migration script, I'm using the Device API (`removeCapability` and `addCapability`). However, on each of these operations, an error is thrown because the old custom capabilities that still exist in the device are unknown to the app. Each operation seems to check on all existing capabilities and throws the following error:
```{ Error: invalid_capability at Remote IPC Process, message: 'invalid_capability', code: 404 }```

One solution would be to keep the unused custom capabilities in the `app.json` and remove them in a later update. Another solution is to put try/catch blocks around each individual remove/add operation, which works since the operations themselves do still complete. These are not very elegant solutions, though.

Can any more elegant solution be implemented in this situation? I think it would require a change in the SDK.

**Comment by WeeJeWel** [comment]
Thank you for your issue. For now, please keep the capabilities in your JSON because Homey has no way of knowing that those will be programmatically removed. I cannot think of a better solution at this time.
